
// This file has been generated by the GUI designer. Do not modify.
namespace MPfm.GTK
{
	public partial class SyncWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label lblTitle;
		private global::Gtk.Label lblSubtitle;
		private global::Gtk.ProgressBar progressBar;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeViewDevices;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button btnRefreshDeviceList;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Button btnConnectManual;
		private global::Gtk.Button btnSyncLibraryWithDevice;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MPfm.GTK.SyncWindow
			this.Name = "MPfm.GTK.SyncWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SyncWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MPfm.GTK.SyncWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 4;
			this.vbox1.BorderWidth = ((uint)(8));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblTitle = new global::Gtk.Label ();
			this.lblTitle.Name = "lblTitle";
			this.lblTitle.Xalign = 0F;
			this.lblTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Sync library with other devices");
			this.vbox2.Add (this.lblTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblTitle]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblSubtitle = new global::Gtk.Label ();
			this.lblSubtitle.Name = "lblSubtitle";
			this.lblSubtitle.Xalign = 0F;
			this.lblSubtitle.LabelProp = global::Mono.Unix.Catalog.GetString ("My IP address is: 192.168.1.101");
			this.vbox2.Add (this.lblSubtitle);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblSubtitle]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
			w3.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.progressBar = new global::Gtk.ProgressBar ();
			this.progressBar.Name = "progressBar";
			this.hbox2.Add (this.progressBar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.progressBar]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeViewDevices = new global::Gtk.TreeView ();
			this.treeViewDevices.CanFocus = true;
			this.treeViewDevices.Name = "treeViewDevices";
			this.GtkScrolledWindow.Add (this.treeViewDevices);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w7.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnRefreshDeviceList = new global::Gtk.Button ();
			this.btnRefreshDeviceList.CanFocus = true;
			this.btnRefreshDeviceList.Name = "btnRefreshDeviceList";
			this.btnRefreshDeviceList.UseUnderline = true;
			this.btnRefreshDeviceList.Label = global::Mono.Unix.Catalog.GetString ("Cancel refresh");
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.btnRefreshDeviceList.Image = w8;
			this.hbox1.Add (this.btnRefreshDeviceList);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnRefreshDeviceList]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w10.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnConnectManual = new global::Gtk.Button ();
			this.btnConnectManual.CanFocus = true;
			this.btnConnectManual.Name = "btnConnectManual";
			this.btnConnectManual.UseUnderline = true;
			this.btnConnectManual.Label = global::Mono.Unix.Catalog.GetString ("Connect manually to a device");
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			this.btnConnectManual.Image = w11;
			this.hbox1.Add (this.btnConnectManual);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnConnectManual]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSyncLibraryWithDevice = new global::Gtk.Button ();
			this.btnSyncLibraryWithDevice.CanFocus = true;
			this.btnSyncLibraryWithDevice.Name = "btnSyncLibraryWithDevice";
			this.btnSyncLibraryWithDevice.UseUnderline = true;
			this.btnSyncLibraryWithDevice.Label = global::Mono.Unix.Catalog.GetString ("Connect to device");
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			this.btnSyncLibraryWithDevice.Image = w13;
			this.hbox1.Add (this.btnSyncLibraryWithDevice);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnSyncLibraryWithDevice]));
			w14.Position = 3;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 604;
			this.DefaultHeight = 363;
			this.Show ();
			this.btnRefreshDeviceList.Clicked += new global::System.EventHandler (this.OnClickRefreshDeviceList);
			this.btnConnectManual.Clicked += new global::System.EventHandler (this.OnClickConnectManual);
			this.btnSyncLibraryWithDevice.Clicked += new global::System.EventHandler (this.OnClickConnect);
		}
	}
}
