
// This file has been generated by the GUI designer. Do not modify.
namespace MPfm.GTK
{
	public partial class SyncMenuWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label lblTitle;
		private global::Gtk.Label lblSubtitle;
		private global::Gtk.Label lblLoading;
		private global::Gtk.ProgressBar progressBar;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeView;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.Button btnAdd;
		private global::Gtk.Button btnRemove;
		private global::Gtk.Button btnAddAll;
		private global::Gtk.Button btnRemoveAll;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView treeViewSelection;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label lblTotal;
		private global::Gtk.Label lblFreeSpace;
		private global::Gtk.Button btnSync;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MPfm.GTK.SyncMenuWindow
			this.Name = "MPfm.GTK.SyncMenuWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SyncMenuWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MPfm.GTK.SyncMenuWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 4;
			this.vbox2.BorderWidth = ((uint)(8));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblTitle = new global::Gtk.Label ();
			this.lblTitle.Name = "lblTitle";
			this.lblTitle.Xalign = 0F;
			this.lblTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Sync library with");
			this.vbox4.Add (this.lblTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblTitle]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblSubtitle = new global::Gtk.Label ();
			this.lblSubtitle.Name = "lblSubtitle";
			this.lblSubtitle.Xalign = 0F;
			this.lblSubtitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose audio files to sync");
			this.vbox4.Add (this.lblSubtitle);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblSubtitle]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox4]));
			w3.Position = 0;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblLoading = new global::Gtk.Label ();
			this.lblLoading.Name = "lblLoading";
			this.lblLoading.LabelProp = global::Mono.Unix.Catalog.GetString ("Loading...");
			this.vbox2.Add (this.lblLoading);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblLoading]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.progressBar = new global::Gtk.ProgressBar ();
			this.progressBar.Name = "progressBar";
			this.vbox2.Add (this.progressBar);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.progressBar]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 331;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeView = new global::Gtk.TreeView ();
			this.treeView.CanFocus = true;
			this.treeView.Name = "treeView";
			this.GtkScrolledWindow.Add (this.treeView);
			this.hpaned1.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
			w8.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.vbox1.Add (this.alignment2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment2]));
			w9.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnAdd = new global::Gtk.Button ();
			this.btnAdd.CanFocus = true;
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.UseUnderline = true;
			this.btnAdd.Label = global::Mono.Unix.Catalog.GetString (">");
			this.vbox1.Add (this.btnAdd);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnAdd]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnRemove = new global::Gtk.Button ();
			this.btnRemove.CanFocus = true;
			this.btnRemove.Name = "btnRemove";
			this.btnRemove.UseUnderline = true;
			this.btnRemove.Label = global::Mono.Unix.Catalog.GetString ("<");
			this.vbox1.Add (this.btnRemove);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnRemove]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnAddAll = new global::Gtk.Button ();
			this.btnAddAll.CanFocus = true;
			this.btnAddAll.Name = "btnAddAll";
			this.btnAddAll.UseUnderline = true;
			this.btnAddAll.Label = global::Mono.Unix.Catalog.GetString (">>");
			this.vbox1.Add (this.btnAddAll);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnAddAll]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnRemoveAll = new global::Gtk.Button ();
			this.btnRemoveAll.CanFocus = true;
			this.btnRemoveAll.Name = "btnRemoveAll";
			this.btnRemoveAll.UseUnderline = true;
			this.btnRemoveAll.Label = global::Mono.Unix.Catalog.GetString ("<<");
			this.vbox1.Add (this.btnRemoveAll);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnRemoveAll]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			// Container child alignment3.Gtk.Container+ContainerChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.alignment3.Add (this.alignment4);
			this.vbox1.Add (this.alignment3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment3]));
			w15.Position = 5;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeViewSelection = new global::Gtk.TreeView ();
			this.treeViewSelection.CanFocus = true;
			this.treeViewSelection.Name = "treeViewSelection";
			this.GtkScrolledWindow1.Add (this.treeViewSelection);
			this.hbox1.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow1]));
			w18.Position = 1;
			this.hpaned1.Add (this.hbox1);
			this.vbox2.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hpaned1]));
			w20.Position = 3;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblTotal = new global::Gtk.Label ();
			this.lblTotal.Name = "lblTotal";
			this.lblTotal.Xalign = 0F;
			this.lblTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total: 0 files (0.0 MB)");
			this.vbox3.Add (this.lblTotal);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblTotal]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblFreeSpace = new global::Gtk.Label ();
			this.lblFreeSpace.Name = "lblFreeSpace";
			this.lblFreeSpace.Xalign = 0F;
			this.lblFreeSpace.LabelProp = global::Mono.Unix.Catalog.GetString ("Free space: 3204.3 MB");
			this.vbox3.Add (this.lblFreeSpace);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblFreeSpace]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
			w23.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnSync = new global::Gtk.Button ();
			this.btnSync.CanFocus = true;
			this.btnSync.Name = "btnSync";
			this.btnSync.UseUnderline = true;
			this.btnSync.Label = global::Mono.Unix.Catalog.GetString ("Sync");
			global::Gtk.Image w24 = new global::Gtk.Image ();
			w24.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			this.btnSync.Image = w24;
			this.hbox2.Add (this.btnSync);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnSync]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w26.Position = 4;
			w26.Expand = false;
			w26.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 640;
			this.DefaultHeight = 485;
			this.Show ();
			this.treeView.RowExpanded += new global::Gtk.RowExpandedHandler (this.OnTreeViewRowExpanded);
			this.btnAdd.Clicked += new global::System.EventHandler (this.OnClickAdd);
			this.btnRemove.Clicked += new global::System.EventHandler (this.OnClickRemove);
			this.btnAddAll.Clicked += new global::System.EventHandler (this.OnClickAddAll);
			this.btnRemoveAll.Clicked += new global::System.EventHandler (this.OnClickRemoveAll);
			this.treeViewSelection.RowExpanded += new global::Gtk.RowExpandedHandler (this.OnTreeViewRowExpanded);
			this.btnSync.Clicked += new global::System.EventHandler (this.OnClickSync);
		}
	}
}
