#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MPfm.Android.Resource", IsApplication=true)]

namespace MPfm.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_in_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_out_right = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int fade_in = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int fade_out = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int slide_in = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int slide_out = 2131034115;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int color_black = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_cloud = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_earth = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_equalizer = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_info = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_mobile = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_settings = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_share = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_transparent = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Splash = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0003
			public const int equalizerPresetDetails_lblTitle = 2131361795;
			
			// aapt resource value: 0x7f0a0002
			public const int equalizerPresetDetails_mainLayout = 2131361794;
			
			// aapt resource value: 0x7f0a0005
			public const int equalizerPresets_lblTitle = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int equalizerPresets_mainLayout = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public const int fragment_audioSettings_lblTitle = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int fragment_audioSettings_mainLayout = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int fragment_generalSettings_lblTitle = 2131361799;
			
			// aapt resource value: 0x7f0a0006
			public const int fragment_generalSettings_mainLayout = 2131361798;
			
			// aapt resource value: 0x7f0a0040
			public const int fragment_updateLibrary_button = 2131361856;
			
			// aapt resource value: 0x7f0a003f
			public const int fragment_updateLibrary_lblSubtitle = 2131361855;
			
			// aapt resource value: 0x7f0a003e
			public const int fragment_updateLibrary_lblTitle = 2131361854;
			
			// aapt resource value: 0x7f0a003b
			public const int fragment_updateLibrary_mainLayout = 2131361851;
			
			// aapt resource value: 0x7f0a003d
			public const int fragment_updateLibrary_progressBar = 2131361853;
			
			// aapt resource value: 0x7f0a003c
			public const int fragment_updateLibrary_relativeLayout = 2131361852;
			
			// aapt resource value: 0x7f0a0008
			public const int genericcell_image = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int genericcell_title = 2131361801;
			
			// aapt resource value: 0x7f0a000d
			public const int libraryPreferences_btnEnableSync = 2131361805;
			
			// aapt resource value: 0x7f0a0010
			public const int libraryPreferences_btnResetLibrary = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int libraryPreferences_btnUpdateLibrary = 2131361809;
			
			// aapt resource value: 0x7f0a000c
			public const int libraryPreferences_lblEnableSync = 2131361804;
			
			// aapt resource value: 0x7f0a000e
			public const int libraryPreferences_lblHTTPPort = 2131361806;
			
			// aapt resource value: 0x7f0a000b
			public const int libraryPreferences_lblTitle = 2131361803;
			
			// aapt resource value: 0x7f0a000a
			public const int libraryPreferences_mainLayout = 2131361802;
			
			// aapt resource value: 0x7f0a000f
			public const int libraryPreferences_txtHTTPPort = 2131361807;
			
			// aapt resource value: 0x7f0a0012
			public const int main_layout = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int main_miniplayer = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int main_miniplayer_imageView = 2131361812;
			
			// aapt resource value: 0x7f0a0017
			public const int main_miniplayer_lblAlbumTitle = 2131361815;
			
			// aapt resource value: 0x7f0a0016
			public const int main_miniplayer_lblArtistName = 2131361814;
			
			// aapt resource value: 0x7f0a0018
			public const int main_miniplayer_lblSongTitle = 2131361816;
			
			// aapt resource value: 0x7f0a0015
			public const int main_miniplayer_text = 2131361813;
			
			// aapt resource value: 0x7f0a0019
			public const int main_pager = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int main_pager_title_strip = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int markers_lblTitle = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int markers_listView = 2131361820;
			
			// aapt resource value: 0x7f0a002b
			public const int playerMetadata_lblAlbumTitle = 2131361835;
			
			// aapt resource value: 0x7f0a002a
			public const int playerMetadata_lblArtistName = 2131361834;
			
			// aapt resource value: 0x7f0a002c
			public const int playerMetadata_lblSongTitle = 2131361836;
			
			// aapt resource value: 0x7f0a0029
			public const int player_btnNext = 2131361833;
			
			// aapt resource value: 0x7f0a0028
			public const int player_btnPlayPause = 2131361832;
			
			// aapt resource value: 0x7f0a0027
			public const int player_btnPrevious = 2131361831;
			
			// aapt resource value: 0x7f0a0024
			public const int player_imageViewAlbumArt = 2131361828;
			
			// aapt resource value: 0x7f0a0026
			public const int player_layoutButtons = 2131361830;
			
			// aapt resource value: 0x7f0a001e
			public const int player_layoutPosition = 2131361822;
			
			// aapt resource value: 0x7f0a0022
			public const int player_layoutWaveForm = 2131361826;
			
			// aapt resource value: 0x7f0a0021
			public const int player_lblLength = 2131361825;
			
			// aapt resource value: 0x7f0a001f
			public const int player_lblPosition = 2131361823;
			
			// aapt resource value: 0x7f0a0023
			public const int player_linearLayoutSubviews = 2131361827;
			
			// aapt resource value: 0x7f0a001d
			public const int player_mainLayout = 2131361821;
			
			// aapt resource value: 0x7f0a0025
			public const int player_pager = 2131361829;
			
			// aapt resource value: 0x7f0a0020
			public const int player_seekBar = 2131361824;
			
			// aapt resource value: 0x7f0a002d
			public const int preferences_mainLayout = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public const int preferences_pager = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int preferences_pager_title_strip = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int splash_layout = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int splash_text = 2131361841;
			
			// aapt resource value: 0x7f0a0038
			public const int syncDownload_lblTitle = 2131361848;
			
			// aapt resource value: 0x7f0a0037
			public const int syncDownload_mainLayout = 2131361847;
			
			// aapt resource value: 0x7f0a003a
			public const int syncMenu_lblTitle = 2131361850;
			
			// aapt resource value: 0x7f0a0039
			public const int syncMenu_mainLayout = 2131361849;
			
			// aapt resource value: 0x7f0a0036
			public const int sync_btnConnectManually = 2131361846;
			
			// aapt resource value: 0x7f0a0033
			public const int sync_lblIPAddress = 2131361843;
			
			// aapt resource value: 0x7f0a0035
			public const int sync_lblStatus = 2131361845;
			
			// aapt resource value: 0x7f0a0032
			public const int sync_mainLayout = 2131361842;
			
			// aapt resource value: 0x7f0a0034
			public const int sync_progressBar = 2131361844;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AudioPreferences = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EqualizerPresetDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EqualizerPresets = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GeneralPreferences = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GenericCell = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LibraryPreferences = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Loops = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Markers = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PitchShifting = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Player = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PlayerMetadata = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Preferences = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Splash = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Sync = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SyncDownload = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SyncMenu = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int TimeShifting = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int UpdateLibrary = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int main_menu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080005
			public const int DialogAnimation = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int MyActionBar = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int MyAppTheme = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int MyAppTheme_ActionBar_TitleTextStyle = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int SplashTheme = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int UpdateLibraryTheme = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
