#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MPfm.Android.Resource", IsApplication=true)]

namespace MPfm.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int color_black = 2131034112;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Splash = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090001
			public const int fragment_audioSettings_lblTitle = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int fragment_audioSettings_mainLayout = 2131296256;
			
			// aapt resource value: 0x7f090003
			public const int fragment_generalSettings_lblTitle = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int fragment_generalSettings_mainLayout = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int fragment_librarySettings_lblTitle = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int fragment_librarySettings_mainLayout = 2131296260;
			
			// aapt resource value: 0x7f090013
			public const int fragment_player_btnNext = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int fragment_player_btnPlayPause = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int fragment_player_btnPrevious = 2131296273;
			
			// aapt resource value: 0x7f090007
			public const int fragment_player_frameLayout = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int fragment_player_imageViewAlbumArt = 2131296264;
			
			// aapt resource value: 0x7f09000b
			public const int fragment_player_lblAlbumTitle = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int fragment_player_lblArtistName = 2131296266;
			
			// aapt resource value: 0x7f09000e
			public const int fragment_player_lblLength = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int fragment_player_lblPosition = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int fragment_player_lblSongTitle = 2131296268;
			
			// aapt resource value: 0x7f090009
			public const int fragment_player_linearLayout = 2131296265;
			
			// aapt resource value: 0x7f090010
			public const int fragment_player_linearLayoutButtons = 2131296272;
			
			// aapt resource value: 0x7f090006
			public const int fragment_player_mainLayout = 2131296262;
			
			// aapt resource value: 0x7f09000f
			public const int fragment_player_seekBar = 2131296271;
			
			// aapt resource value: 0x7f090019
			public const int fragment_updateLibrary_button = 2131296281;
			
			// aapt resource value: 0x7f090018
			public const int fragment_updateLibrary_lblSubtitle = 2131296280;
			
			// aapt resource value: 0x7f090017
			public const int fragment_updateLibrary_lblTitle = 2131296279;
			
			// aapt resource value: 0x7f090014
			public const int fragment_updateLibrary_mainLayout = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int fragment_updateLibrary_progressBar = 2131296278;
			
			// aapt resource value: 0x7f090015
			public const int fragment_updateLibrary_relativeLayout = 2131296277;
			
			// aapt resource value: 0x7f09001a
			public const int genericcell_image = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int genericcell_title = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int main_layout = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int main_pager = 2131296285;
			
			// aapt resource value: 0x7f090025
			public const int menu_item_about = 2131296293;
			
			// aapt resource value: 0x7f090022
			public const int menu_item_effects = 2131296290;
			
			// aapt resource value: 0x7f090024
			public const int menu_item_preferences = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int menu_item_updateLibrary = 2131296291;
			
			// aapt resource value: 0x7f09001e
			public const int settings_layout = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int settings_pager = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int splash_layout = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int splash_text = 2131296289;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Fragment_AudioPreferences = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragment_GeneralPreferences = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Fragment_LibraryPreferences = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fragment_Player = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fragment_UpdateLibrary = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GenericCell = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Splash = 2130903048;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_menu = 2131230720;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070004
			public const int DialogAnimation = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int MyActionBar = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int MyAppTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int SplashTheme = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int UpdateLibraryTheme = 2131165187;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
