#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MPfm.Android.Resource", IsApplication=true)]

namespace MPfm.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int flipper_back_slide_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int flipper_back_slide_out = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int flipper_changetab_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int flipper_changetab_out = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int flipper_slide_in = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int flipper_slide_out = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int gridviewoptions_fade_in = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int gridviewoptions_fade_out = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int listviewoptions_fade_in = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int listviewoptions_fade_out = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int scale_test = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int slide_in_left = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int slide_out_right = 2130968590;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int fade_in = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int fade_out = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int slide_in = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int slide_out = 2131034115;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int action_list = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int updateInterval = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int updateIntervalValues = 2131230722;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public const int actionbar = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int actionbar_selected = 2131165188;
			
			// aapt resource value: 0x7f07000e
			public const int albumcellbutton_background = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int albumcellbutton_selected = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int albumcellbutton_textcolor = 2131165200;
			
			// aapt resource value: 0x7f070002
			public const int background = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int button_background = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int button_selected = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int button_textcolor = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int color_black = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int dialogbutton_background = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int dialogbutton_selected = 2131165196;
			
			// aapt resource value: 0x7f070014
			public const int dialogbutton_text = 2131165204;
			
			// aapt resource value: 0x7f07000d
			public const int dialogbutton_textcolor = 2131165197;
			
			// aapt resource value: 0x7f070015
			public const int dialoglist_text = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int list_secondarytext = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int list_text = 2131165207;
			
			// aapt resource value: 0x7f070011
			public const int listitem_background = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int listitem_selected = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int listitem_textcolor = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int transparentbutton_background = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int transparentbutton_selected = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int transparentbutton_textcolor = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int white = 2131165185;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_audio = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_cancel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_cloud = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_download = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int actionbar_dropbox = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int actionbar_earth = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int actionbar_equalizer = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int actionbar_folder = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int actionbar_frequency = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int actionbar_info = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int actionbar_library = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int actionbar_mobile = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int actionbar_play = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int actionbar_playlist = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int actionbar_reset = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int actionbar_resume = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int actionbar_save = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int actionbar_select = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int actionbar_select_disabled = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int actionbar_settings = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int actionbar_share = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int actionbar_sync = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int actionbar_trash = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int actionbar_update = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int albumcellbutton = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int button = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int carrouseldot = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int checkbox_checked = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int checkbox_partial = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int checkbox_unchecked = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int dialogbutton = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Icon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int icon_add = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int icon_android = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int icon_artist = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int icon_check = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int icon_equalizer = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int icon_linux = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int icon_move = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int icon_osx = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int icon_phone = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int icon_play = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int icon_speaker = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int icon_tablet = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int icon_transparent = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int icon_trash = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int icon_vinyl = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int icon_windows = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int list = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int listgradient = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int miniplayer_chevronleft = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int miniplayer_chevronleft_on = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int miniplayer_chevronright = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int miniplayer_chevronright_on = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int miniplayerchevron = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int optionsmenu = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int player_close = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int player_close_on = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int player_next = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int player_next_on = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int player_pause = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int player_pause_on = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int player_play = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int player_play_on = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int player_playlist = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int player_playlist_on = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int player_previous = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int player_previous_on = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int player_repeat = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int player_repeat_on = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int player_shuffle = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int player_shuffle_on = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int progress = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int progress_background = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int progress_fill = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int roundbutton = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int selectimage = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int spinner = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int Splash = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int thumb = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int thumb_big = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int transparentbutton = 2130837586;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0000
			public const int about_layout = 2131492864;
			
			// aapt resource value: 0x7f0c0002
			public const int about_lblLoading = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int about_progressBar = 2131492867;
			
			// aapt resource value: 0x7f0c0001
			public const int about_webView = 2131492865;
			
			// aapt resource value: 0x7f0c0008
			public const int addMarker_btnCancel = 2131492872;
			
			// aapt resource value: 0x7f0c0009
			public const int addMarker_btnCreate = 2131492873;
			
			// aapt resource value: 0x7f0c0006
			public const int addMarker_radioBridge = 2131492870;
			
			// aapt resource value: 0x7f0c0005
			public const int addMarker_radioChorus = 2131492869;
			
			// aapt resource value: 0x7f0c0007
			public const int addMarker_radioSolo = 2131492871;
			
			// aapt resource value: 0x7f0c0004
			public const int addMarker_radioVerse = 2131492868;
			
			// aapt resource value: 0x7f0c000b
			public const int addPlaylist_btnCancel = 2131492875;
			
			// aapt resource value: 0x7f0c000c
			public const int addPlaylist_btnCreate = 2131492876;
			
			// aapt resource value: 0x7f0c000a
			public const int addPlaylist_txtName = 2131492874;
			
			// aapt resource value: 0x7f0c0013
			public const int albumCell_albumTitle = 2131492883;
			
			// aapt resource value: 0x7f0c0012
			public const int albumCell_artistName = 2131492882;
			
			// aapt resource value: 0x7f0c0010
			public const int albumCell_btnAddToPlaylist = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int albumCell_btnDelete = 2131492881;
			
			// aapt resource value: 0x7f0c000f
			public const int albumCell_btnPlay = 2131492879;
			
			// aapt resource value: 0x7f0c000e
			public const int albumCell_image = 2131492878;
			
			// aapt resource value: 0x7f0c000d
			public const int albumCell_layout = 2131492877;
			
			// aapt resource value: 0x7f0c0016
			public const int bigNotificationPlayer = 2131492886;
			
			// aapt resource value: 0x7f0c0017
			public const int bigNotificationPlayer_btnClose = 2131492887;
			
			// aapt resource value: 0x7f0c001e
			public const int bigNotificationPlayer_btnNext = 2131492894;
			
			// aapt resource value: 0x7f0c001d
			public const int bigNotificationPlayer_btnPlayPause = 2131492893;
			
			// aapt resource value: 0x7f0c001c
			public const int bigNotificationPlayer_btnPrevious = 2131492892;
			
			// aapt resource value: 0x7f0c0018
			public const int bigNotificationPlayer_imageAlbum = 2131492888;
			
			// aapt resource value: 0x7f0c001a
			public const int bigNotificationPlayer_lblAlbumTitle = 2131492890;
			
			// aapt resource value: 0x7f0c0019
			public const int bigNotificationPlayer_lblArtistName = 2131492889;
			
			// aapt resource value: 0x7f0c001b
			public const int bigNotificationPlayer_lblSongTitle = 2131492891;
			
			// aapt resource value: 0x7f0c0022
			public const int cloudConnect_btnCancel = 2131492898;
			
			// aapt resource value: 0x7f0c0021
			public const int cloudConnect_btnOK = 2131492897;
			
			// aapt resource value: 0x7f0c0020
			public const int cloudConnect_lblStatus = 2131492896;
			
			// aapt resource value: 0x7f0c001f
			public const int cloudConnect_progressBar = 2131492895;
			
			// aapt resource value: 0x7f0c0024
			public const int equalizerPresetCell_imageCheck = 2131492900;
			
			// aapt resource value: 0x7f0c0023
			public const int equalizerPresetCell_lblName = 2131492899;
			
			// aapt resource value: 0x7f0c0141
			public const int equalizerPresetDetailsMenu_item_save = 2131493185;
			
			// aapt resource value: 0x7f0c002c
			public const int equalizerPresetDetails_btnDelete = 2131492908;
			
			// aapt resource value: 0x7f0c002a
			public const int equalizerPresetDetails_btnNormalize = 2131492906;
			
			// aapt resource value: 0x7f0c002b
			public const int equalizerPresetDetails_btnReset = 2131492907;
			
			// aapt resource value: 0x7f0c0026
			public const int equalizerPresetDetails_graphView = 2131492902;
			
			// aapt resource value: 0x7f0c0027
			public const int equalizerPresetDetails_lblPresetName = 2131492903;
			
			// aapt resource value: 0x7f0c0029
			public const int equalizerPresetDetails_listView = 2131492905;
			
			// aapt resource value: 0x7f0c0025
			public const int equalizerPresetDetails_mainLayout = 2131492901;
			
			// aapt resource value: 0x7f0c0028
			public const int equalizerPresetDetails_txtPresetName = 2131492904;
			
			// aapt resource value: 0x7f0c002d
			public const int equalizerPresetFaderCell_lblFrequency = 2131492909;
			
			// aapt resource value: 0x7f0c002f
			public const int equalizerPresetFaderCell_lblValue = 2131492911;
			
			// aapt resource value: 0x7f0c002e
			public const int equalizerPresetFaderCell_seekBar = 2131492910;
			
			// aapt resource value: 0x7f0c0142
			public const int equalizerPresetsMenu_item_add = 2131493186;
			
			// aapt resource value: 0x7f0c0036
			public const int equalizerPresets_btnBypass = 2131492918;
			
			// aapt resource value: 0x7f0c0035
			public const int equalizerPresets_lblBypass = 2131492917;
			
			// aapt resource value: 0x7f0c0033
			public const int equalizerPresets_lblMasterVolume = 2131492915;
			
			// aapt resource value: 0x7f0c0037
			public const int equalizerPresets_listView = 2131492919;
			
			// aapt resource value: 0x7f0c0030
			public const int equalizerPresets_mainLayout = 2131492912;
			
			// aapt resource value: 0x7f0c0032
			public const int equalizerPresets_outputMeterView = 2131492914;
			
			// aapt resource value: 0x7f0c0034
			public const int equalizerPresets_seekBarVolume = 2131492916;
			
			// aapt resource value: 0x7f0c0031
			public const int equalizerPresets_topLayout = 2131492913;
			
			// aapt resource value: 0x7f0c0038
			public const int firstRun_btnClose = 2131492920;
			
			// aapt resource value: 0x7f0c0039
			public const int foldercell_checkbox = 2131492921;
			
			// aapt resource value: 0x7f0c003a
			public const int foldercell_title = 2131492922;
			
			// aapt resource value: 0x7f0c0015
			public const int fragment_audioSettings_lblTitle = 2131492885;
			
			// aapt resource value: 0x7f0c0014
			public const int fragment_audioSettings_mainLayout = 2131492884;
			
			// aapt resource value: 0x7f0c003c
			public const int fragment_generalSettings_lblTitle = 2131492924;
			
			// aapt resource value: 0x7f0c003b
			public const int fragment_generalSettings_mainLayout = 2131492923;
			
			// aapt resource value: 0x7f0c0136
			public const int fragment_updateLibrary_button = 2131493174;
			
			// aapt resource value: 0x7f0c0135
			public const int fragment_updateLibrary_lblSubtitle = 2131493173;
			
			// aapt resource value: 0x7f0c0134
			public const int fragment_updateLibrary_lblTitle = 2131493172;
			
			// aapt resource value: 0x7f0c0131
			public const int fragment_updateLibrary_mainLayout = 2131493169;
			
			// aapt resource value: 0x7f0c0133
			public const int fragment_updateLibrary_progressBar = 2131493171;
			
			// aapt resource value: 0x7f0c0132
			public const int fragment_updateLibrary_relativeLayout = 2131493170;
			
			// aapt resource value: 0x7f0c003d
			public const int genericcell_image = 2131492925;
			
			// aapt resource value: 0x7f0c003e
			public const int genericcell_title = 2131492926;
			
			// aapt resource value: 0x7f0c0042
			public const int libraryPreferences_btnEnableSync = 2131492930;
			
			// aapt resource value: 0x7f0c0046
			public const int libraryPreferences_btnResetLibrary = 2131492934;
			
			// aapt resource value: 0x7f0c0045
			public const int libraryPreferences_btnSelectFolders = 2131492933;
			
			// aapt resource value: 0x7f0c0047
			public const int libraryPreferences_btnUpdateLibrary = 2131492935;
			
			// aapt resource value: 0x7f0c0041
			public const int libraryPreferences_lblEnableSync = 2131492929;
			
			// aapt resource value: 0x7f0c0043
			public const int libraryPreferences_lblHTTPPort = 2131492931;
			
			// aapt resource value: 0x7f0c0040
			public const int libraryPreferences_lblTitle = 2131492928;
			
			// aapt resource value: 0x7f0c003f
			public const int libraryPreferences_mainLayout = 2131492927;
			
			// aapt resource value: 0x7f0c0044
			public const int libraryPreferences_txtHTTPPort = 2131492932;
			
			// aapt resource value: 0x7f0c0056
			public const int lockScreen_btnClose = 2131492950;
			
			// aapt resource value: 0x7f0c0054
			public const int lockScreen_btnNext = 2131492948;
			
			// aapt resource value: 0x7f0c0053
			public const int lockScreen_btnPlayPause = 2131492947;
			
			// aapt resource value: 0x7f0c0052
			public const int lockScreen_btnPrevious = 2131492946;
			
			// aapt resource value: 0x7f0c0051
			public const int lockScreen_btnRepeat = 2131492945;
			
			// aapt resource value: 0x7f0c0055
			public const int lockScreen_btnShuffle = 2131492949;
			
			// aapt resource value: 0x7f0c004d
			public const int lockScreen_imageAlbum = 2131492941;
			
			// aapt resource value: 0x7f0c0049
			public const int lockScreen_layoutPosition = 2131492937;
			
			// aapt resource value: 0x7f0c004f
			public const int lockScreen_lblAlbumTitle = 2131492943;
			
			// aapt resource value: 0x7f0c004e
			public const int lockScreen_lblArtistName = 2131492942;
			
			// aapt resource value: 0x7f0c004c
			public const int lockScreen_lblLength = 2131492940;
			
			// aapt resource value: 0x7f0c004a
			public const int lockScreen_lblPosition = 2131492938;
			
			// aapt resource value: 0x7f0c0050
			public const int lockScreen_lblSongTitle = 2131492944;
			
			// aapt resource value: 0x7f0c0048
			public const int lockScreen_mainLayout = 2131492936;
			
			// aapt resource value: 0x7f0c004b
			public const int lockScreen_seekBar = 2131492939;
			
			// aapt resource value: 0x7f0c0058
			public const int loops_btnAdd = 2131492952;
			
			// aapt resource value: 0x7f0c0057
			public const int loops_lblTitle = 2131492951;
			
			// aapt resource value: 0x7f0c0059
			public const int loops_listView = 2131492953;
			
			// aapt resource value: 0x7f0c006f
			public const int main_fragmentContainer = 2131492975;
			
			// aapt resource value: 0x7f0c005a
			public const int main_layout = 2131492954;
			
			// aapt resource value: 0x7f0c005c
			public const int main_miniplayer = 2131492956;
			
			// aapt resource value: 0x7f0c0064
			public const int main_miniplayer_btnNext = 2131492964;
			
			// aapt resource value: 0x7f0c0063
			public const int main_miniplayer_btnPlayPause = 2131492963;
			
			// aapt resource value: 0x7f0c0062
			public const int main_miniplayer_btnPrevious = 2131492962;
			
			// aapt resource value: 0x7f0c0066
			public const int main_miniplayer_btnRight = 2131492966;
			
			// aapt resource value: 0x7f0c005d
			public const int main_miniplayer_imageAlbum = 2131492957;
			
			// aapt resource value: 0x7f0c0060
			public const int main_miniplayer_lblAlbumTitle = 2131492960;
			
			// aapt resource value: 0x7f0c005f
			public const int main_miniplayer_lblArtistName = 2131492959;
			
			// aapt resource value: 0x7f0c0065
			public const int main_miniplayer_lblSongPosition = 2131492965;
			
			// aapt resource value: 0x7f0c0061
			public const int main_miniplayer_lblSongTitle = 2131492961;
			
			// aapt resource value: 0x7f0c005e
			public const int main_miniplayer_text = 2131492958;
			
			// aapt resource value: 0x7f0c0067
			public const int main_miniplaylist = 2131492967;
			
			// aapt resource value: 0x7f0c0068
			public const int main_miniplaylist_btnLeft = 2131492968;
			
			// aapt resource value: 0x7f0c006a
			public const int main_miniplaylist_btnPlaylist = 2131492970;
			
			// aapt resource value: 0x7f0c006d
			public const int main_miniplaylist_btnRepeat = 2131492973;
			
			// aapt resource value: 0x7f0c006e
			public const int main_miniplaylist_btnShuffle = 2131492974;
			
			// aapt resource value: 0x7f0c0069
			public const int main_miniplaylist_cboPlaylist = 2131492969;
			
			// aapt resource value: 0x7f0c006b
			public const int main_miniplaylist_lblPlaylistCount = 2131492971;
			
			// aapt resource value: 0x7f0c006c
			public const int main_miniplaylist_lblPlaylistLength = 2131492972;
			
			// aapt resource value: 0x7f0c005b
			public const int main_viewflipper = 2131492955;
			
			// aapt resource value: 0x7f0c0070
			public const int markerCell_letter = 2131492976;
			
			// aapt resource value: 0x7f0c0071
			public const int markerCell_name = 2131492977;
			
			// aapt resource value: 0x7f0c0072
			public const int markerCell_position = 2131492978;
			
			// aapt resource value: 0x7f0c0074
			public const int markerDetails_lblTitle = 2131492980;
			
			// aapt resource value: 0x7f0c0073
			public const int markerDetails_mainLayout = 2131492979;
			
			// aapt resource value: 0x7f0c0076
			public const int markers_btnAdd = 2131492982;
			
			// aapt resource value: 0x7f0c0075
			public const int markers_lblTitle = 2131492981;
			
			// aapt resource value: 0x7f0c0077
			public const int markers_listView = 2131492983;
			
			// aapt resource value: 0x7f0c0093
			public const int mobileLibraryBrowserCell_imageAdd = 2131493011;
			
			// aapt resource value: 0x7f0c0087
			public const int mobileLibraryBrowserCell_imageAlbum1 = 2131492999;
			
			// aapt resource value: 0x7f0c0088
			public const int mobileLibraryBrowserCell_imageAlbum2 = 2131493000;
			
			// aapt resource value: 0x7f0c0089
			public const int mobileLibraryBrowserCell_imageAlbum3 = 2131493001;
			
			// aapt resource value: 0x7f0c0094
			public const int mobileLibraryBrowserCell_imageDelete = 2131493012;
			
			// aapt resource value: 0x7f0c0095
			public const int mobileLibraryBrowserCell_imageNowPlaying = 2131493013;
			
			// aapt resource value: 0x7f0c0092
			public const int mobileLibraryBrowserCell_imagePlay = 2131493010;
			
			// aapt resource value: 0x7f0c008c
			public const int mobileLibraryBrowserCell_index = 2131493004;
			
			// aapt resource value: 0x7f0c008a
			public const int mobileLibraryBrowserCell_layoutAlbumCount = 2131493002;
			
			// aapt resource value: 0x7f0c0086
			public const int mobileLibraryBrowserCell_layoutAlbums = 2131492998;
			
			// aapt resource value: 0x7f0c0091
			public const int mobileLibraryBrowserCell_layoutMenu = 2131493009;
			
			// aapt resource value: 0x7f0c008e
			public const int mobileLibraryBrowserCell_layoutSubtitle = 2131493006;
			
			// aapt resource value: 0x7f0c008b
			public const int mobileLibraryBrowserCell_lblAlbumCount = 2131493003;
			
			// aapt resource value: 0x7f0c0090
			public const int mobileLibraryBrowserCell_lblSubtitle = 2131493008;
			
			// aapt resource value: 0x7f0c008d
			public const int mobileLibraryBrowserCell_lblTitle = 2131493005;
			
			// aapt resource value: 0x7f0c008f
			public const int mobileLibraryBrowserCell_lblTitleWithSubtitle = 2131493007;
			
			// aapt resource value: 0x7f0c007d
			public const int mobileLibraryBrowser_gridViewAlbums = 2131492989;
			
			// aapt resource value: 0x7f0c0080
			public const int mobileLibraryBrowser_imageAlbum = 2131492992;
			
			// aapt resource value: 0x7f0c007f
			public const int mobileLibraryBrowser_layoutAlbum = 2131492991;
			
			// aapt resource value: 0x7f0c0078
			public const int mobileLibraryBrowser_layoutBreadcrumb = 2131492984;
			
			// aapt resource value: 0x7f0c007e
			public const int mobileLibraryBrowser_layoutSongs = 2131492990;
			
			// aapt resource value: 0x7f0c0084
			public const int mobileLibraryBrowser_lblAlbumLength = 2131492996;
			
			// aapt resource value: 0x7f0c0083
			public const int mobileLibraryBrowser_lblAlbumSongCount = 2131492995;
			
			// aapt resource value: 0x7f0c0082
			public const int mobileLibraryBrowser_lblAlbumTitle = 2131492994;
			
			// aapt resource value: 0x7f0c0081
			public const int mobileLibraryBrowser_lblArtistName = 2131492993;
			
			// aapt resource value: 0x7f0c0079
			public const int mobileLibraryBrowser_lblBreadcrumb = 2131492985;
			
			// aapt resource value: 0x7f0c007c
			public const int mobileLibraryBrowser_listViewArtists = 2131492988;
			
			// aapt resource value: 0x7f0c007b
			public const int mobileLibraryBrowser_listViewPlaylists = 2131492987;
			
			// aapt resource value: 0x7f0c0085
			public const int mobileLibraryBrowser_listViewSongs = 2131492997;
			
			// aapt resource value: 0x7f0c007a
			public const int mobileLibraryBrowser_viewFlipper = 2131492986;
			
			// aapt resource value: 0x7f0c0096
			public const int notificationPlayer = 2131493014;
			
			// aapt resource value: 0x7f0c009c
			public const int notificationPlayer_btnClose = 2131493020;
			
			// aapt resource value: 0x7f0c009b
			public const int notificationPlayer_btnNext = 2131493019;
			
			// aapt resource value: 0x7f0c009a
			public const int notificationPlayer_btnPlayPause = 2131493018;
			
			// aapt resource value: 0x7f0c0099
			public const int notificationPlayer_btnPrevious = 2131493017;
			
			// aapt resource value: 0x7f0c0098
			public const int notificationPlayer_lblSubtitle = 2131493016;
			
			// aapt resource value: 0x7f0c0097
			public const int notificationPlayer_lblTitle = 2131493015;
			
			// aapt resource value: 0x7f0c00a0
			public const int pitchShifting_btnChangeKey = 2131493024;
			
			// aapt resource value: 0x7f0c00a6
			public const int pitchShifting_btnDecrement = 2131493030;
			
			// aapt resource value: 0x7f0c00a7
			public const int pitchShifting_btnIncrement = 2131493031;
			
			// aapt resource value: 0x7f0c00a8
			public const int pitchShifting_btnReset = 2131493032;
			
			// aapt resource value: 0x7f0c00a1
			public const int pitchShifting_lblCurrentInterval = 2131493025;
			
			// aapt resource value: 0x7f0c00a3
			public const int pitchShifting_lblCurrentIntervalValue = 2131493027;
			
			// aapt resource value: 0x7f0c00a2
			public const int pitchShifting_lblNewKey = 2131493026;
			
			// aapt resource value: 0x7f0c00a4
			public const int pitchShifting_lblNewKeyValue = 2131493028;
			
			// aapt resource value: 0x7f0c009e
			public const int pitchShifting_lblReferenceKey = 2131493022;
			
			// aapt resource value: 0x7f0c009f
			public const int pitchShifting_lblReferenceKeyValue = 2131493023;
			
			// aapt resource value: 0x7f0c009d
			public const int pitchShifting_lblTitle = 2131493021;
			
			// aapt resource value: 0x7f0c00a5
			public const int pitchShifting_seekBar = 2131493029;
			
			// aapt resource value: 0x7f0c0144
			public const int playerMenu_item_effects = 2131493188;
			
			// aapt resource value: 0x7f0c0143
			public const int playerMenu_item_playlist = 2131493187;
			
			// aapt resource value: 0x7f0c00bf
			public const int playerMetadata_lblAlbumTitle = 2131493055;
			
			// aapt resource value: 0x7f0c00be
			public const int playerMetadata_lblArtistName = 2131493054;
			
			// aapt resource value: 0x7f0c00c0
			public const int playerMetadata_lblSongTitle = 2131493056;
			
			// aapt resource value: 0x7f0c00bb
			public const int player_btnNext = 2131493051;
			
			// aapt resource value: 0x7f0c00ba
			public const int player_btnPlayPause = 2131493050;
			
			// aapt resource value: 0x7f0c00bc
			public const int player_btnPlaylist = 2131493052;
			
			// aapt resource value: 0x7f0c00b9
			public const int player_btnPrevious = 2131493049;
			
			// aapt resource value: 0x7f0c00b8
			public const int player_btnRepeat = 2131493048;
			
			// aapt resource value: 0x7f0c00bd
			public const int player_btnShuffle = 2131493053;
			
			// aapt resource value: 0x7f0c00b2
			public const int player_carrouselDot1 = 2131493042;
			
			// aapt resource value: 0x7f0c00b3
			public const int player_carrouselDot2 = 2131493043;
			
			// aapt resource value: 0x7f0c00b4
			public const int player_carrouselDot3 = 2131493044;
			
			// aapt resource value: 0x7f0c00b5
			public const int player_carrouselDot4 = 2131493045;
			
			// aapt resource value: 0x7f0c00b6
			public const int player_carrouselDot5 = 2131493046;
			
			// aapt resource value: 0x7f0c00b0
			public const int player_imageViewAlbumArt = 2131493040;
			
			// aapt resource value: 0x7f0c00b7
			public const int player_layoutButtons = 2131493047;
			
			// aapt resource value: 0x7f0c00aa
			public const int player_layoutPosition = 2131493034;
			
			// aapt resource value: 0x7f0c00ad
			public const int player_lblLength = 2131493037;
			
			// aapt resource value: 0x7f0c00ab
			public const int player_lblPosition = 2131493035;
			
			// aapt resource value: 0x7f0c00af
			public const int player_linearLayoutSubviews = 2131493039;
			
			// aapt resource value: 0x7f0c00a9
			public const int player_mainLayout = 2131493033;
			
			// aapt resource value: 0x7f0c00b1
			public const int player_pager = 2131493041;
			
			// aapt resource value: 0x7f0c00ac
			public const int player_seekBar = 2131493036;
			
			// aapt resource value: 0x7f0c00ae
			public const int player_waveFormScrollView = 2131493038;
			
			// aapt resource value: 0x7f0c00ca
			public const int playlistItemCell_imageDelete = 2131493066;
			
			// aapt resource value: 0x7f0c00cc
			public const int playlistItemCell_imageMove = 2131493068;
			
			// aapt resource value: 0x7f0c00cb
			public const int playlistItemCell_imageNowPlaying = 2131493067;
			
			// aapt resource value: 0x7f0c00c9
			public const int playlistItemCell_imagePlay = 2131493065;
			
			// aapt resource value: 0x7f0c00c6
			public const int playlistItemCell_lblIndex = 2131493062;
			
			// aapt resource value: 0x7f0c00c8
			public const int playlistItemCell_lblSubtitle = 2131493064;
			
			// aapt resource value: 0x7f0c00c7
			public const int playlistItemCell_lblTitle = 2131493063;
			
			// aapt resource value: 0x7f0c00c2
			public const int playlist_btnNew = 2131493058;
			
			// aapt resource value: 0x7f0c00c3
			public const int playlist_btnShuffle = 2131493059;
			
			// aapt resource value: 0x7f0c00c1
			public const int playlist_listView = 2131493057;
			
			// aapt resource value: 0x7f0c00c5
			public const int playlistcell_count = 2131493061;
			
			// aapt resource value: 0x7f0c00c4
			public const int playlistcell_title = 2131493060;
			
			// aapt resource value: 0x7f0c00d1
			public const int resumePlaybackCell_imageAlbum = 2131493073;
			
			// aapt resource value: 0x7f0c00d3
			public const int resumePlaybackCell_lblAlbumTitle = 2131493075;
			
			// aapt resource value: 0x7f0c00d2
			public const int resumePlaybackCell_lblArtistName = 2131493074;
			
			// aapt resource value: 0x7f0c00d4
			public const int resumePlaybackCell_lblSongTitle = 2131493076;
			
			// aapt resource value: 0x7f0c00d0
			public const int resumePlaybackCell_lblSubtitle = 2131493072;
			
			// aapt resource value: 0x7f0c00d5
			public const int resumePlaybackCell_lblTimestamp = 2131493077;
			
			// aapt resource value: 0x7f0c00cf
			public const int resumePlaybackCell_lblTitle = 2131493071;
			
			// aapt resource value: 0x7f0c00ce
			public const int resumePlayback_listView = 2131493070;
			
			// aapt resource value: 0x7f0c00cd
			public const int resumePlayback_mainLayout = 2131493069;
			
			// aapt resource value: 0x7f0c00d9
			public const int seekBarPreference_layoutSeekBar = 2131493081;
			
			// aapt resource value: 0x7f0c00d6
			public const int seekBarPreference_layoutTitle = 2131493078;
			
			// aapt resource value: 0x7f0c00dc
			public const int seekBarPreference_lblMaxValue = 2131493084;
			
			// aapt resource value: 0x7f0c00da
			public const int seekBarPreference_lblMinValue = 2131493082;
			
			// aapt resource value: 0x7f0c00d7
			public const int seekBarPreference_lblTitle = 2131493079;
			
			// aapt resource value: 0x7f0c00d8
			public const int seekBarPreference_lblValue = 2131493080;
			
			// aapt resource value: 0x7f0c00db
			public const int seekBarPreference_seekBar = 2131493083;
			
			// aapt resource value: 0x7f0c00df
			public const int selectFolders_btnCancel = 2131493087;
			
			// aapt resource value: 0x7f0c00e0
			public const int selectFolders_btnOK = 2131493088;
			
			// aapt resource value: 0x7f0c00dd
			public const int selectFolders_layoutLoading = 2131493085;
			
			// aapt resource value: 0x7f0c00de
			public const int selectFolders_listView = 2131493086;
			
			// aapt resource value: 0x7f0c00e1
			public const int selectPlaylist_btnAddNewPlaylist = 2131493089;
			
			// aapt resource value: 0x7f0c00e3
			public const int selectPlaylist_btnCancel = 2131493091;
			
			// aapt resource value: 0x7f0c00e4
			public const int selectPlaylist_btnSelect = 2131493092;
			
			// aapt resource value: 0x7f0c00e2
			public const int selectPlaylist_listView = 2131493090;
			
			// aapt resource value: 0x7f0c00e5
			public const int splash_progressBar = 2131493093;
			
			// aapt resource value: 0x7f0c00e6
			public const int splash_text = 2131493094;
			
			// aapt resource value: 0x7f0c00ef
			public const int startResumePlayback_btnCancel = 2131493103;
			
			// aapt resource value: 0x7f0c00ee
			public const int startResumePlayback_btnResume = 2131493102;
			
			// aapt resource value: 0x7f0c00e9
			public const int startResumePlayback_imageAlbum = 2131493097;
			
			// aapt resource value: 0x7f0c00eb
			public const int startResumePlayback_lblAlbumTitle = 2131493099;
			
			// aapt resource value: 0x7f0c00ea
			public const int startResumePlayback_lblArtistName = 2131493098;
			
			// aapt resource value: 0x7f0c00e7
			public const int startResumePlayback_lblDeviceName = 2131493095;
			
			// aapt resource value: 0x7f0c00e8
			public const int startResumePlayback_lblPlaylistName = 2131493096;
			
			// aapt resource value: 0x7f0c00ec
			public const int startResumePlayback_lblSongTitle = 2131493100;
			
			// aapt resource value: 0x7f0c00ed
			public const int startResumePlayback_lblTimestamp = 2131493101;
			
			// aapt resource value: 0x7f0c00fe
			public const int syncCloud_btnDelete = 2131493118;
			
			// aapt resource value: 0x7f0c00fa
			public const int syncCloud_btnLogin = 2131493114;
			
			// aapt resource value: 0x7f0c00fb
			public const int syncCloud_btnLogout = 2131493115;
			
			// aapt resource value: 0x7f0c00fc
			public const int syncCloud_btnPull = 2131493116;
			
			// aapt resource value: 0x7f0c00fd
			public const int syncCloud_btnPush = 2131493117;
			
			// aapt resource value: 0x7f0c00f7
			public const int syncCloud_lblConnected = 2131493111;
			
			// aapt resource value: 0x7f0c00f8
			public const int syncCloud_lblDataChanged = 2131493112;
			
			// aapt resource value: 0x7f0c00f9
			public const int syncCloud_lblValue = 2131493113;
			
			// aapt resource value: 0x7f0c00f6
			public const int syncCloud_mainLayout = 2131493110;
			
			// aapt resource value: 0x7f0c0104
			public const int syncDownload_lblCompleted = 2131493124;
			
			// aapt resource value: 0x7f0c0103
			public const int syncDownload_lblCompletedValue = 2131493123;
			
			// aapt resource value: 0x7f0c010a
			public const int syncDownload_lblCurrentFileProgress = 2131493130;
			
			// aapt resource value: 0x7f0c0109
			public const int syncDownload_lblCurrentFileProgressValue = 2131493129;
			
			// aapt resource value: 0x7f0c010c
			public const int syncDownload_lblDownloadSpeed = 2131493132;
			
			// aapt resource value: 0x7f0c010b
			public const int syncDownload_lblDownloadSpeedValue = 2131493131;
			
			// aapt resource value: 0x7f0c010e
			public const int syncDownload_lblErrors = 2131493134;
			
			// aapt resource value: 0x7f0c010d
			public const int syncDownload_lblErrorsValue = 2131493133;
			
			// aapt resource value: 0x7f0c0102
			public const int syncDownload_lblFileName = 2131493122;
			
			// aapt resource value: 0x7f0c0106
			public const int syncDownload_lblFilesDownloaded = 2131493126;
			
			// aapt resource value: 0x7f0c0105
			public const int syncDownload_lblFilesDownloadedValue = 2131493125;
			
			// aapt resource value: 0x7f0c0101
			public const int syncDownload_lblTitle = 2131493121;
			
			// aapt resource value: 0x7f0c0108
			public const int syncDownload_lblTotalFiles = 2131493128;
			
			// aapt resource value: 0x7f0c0107
			public const int syncDownload_lblTotalFilesValue = 2131493127;
			
			// aapt resource value: 0x7f0c00ff
			public const int syncDownload_mainLayout = 2131493119;
			
			// aapt resource value: 0x7f0c0100
			public const int syncDownload_progressBar = 2131493120;
			
			// aapt resource value: 0x7f0c010f
			public const int syncManualConnect_lblIPAddress = 2131493135;
			
			// aapt resource value: 0x7f0c0111
			public const int syncManualConnect_lblPort = 2131493137;
			
			// aapt resource value: 0x7f0c0110
			public const int syncManualConnect_txtIPAddress = 2131493136;
			
			// aapt resource value: 0x7f0c0112
			public const int syncManualConnect_txtPort = 2131493138;
			
			// aapt resource value: 0x7f0c011e
			public const int syncMenuCell_checkmark = 2131493150;
			
			// aapt resource value: 0x7f0c011b
			public const int syncMenuCell_image = 2131493147;
			
			// aapt resource value: 0x7f0c011c
			public const int syncMenuCell_index = 2131493148;
			
			// aapt resource value: 0x7f0c011d
			public const int syncMenuCell_title = 2131493149;
			
			// aapt resource value: 0x7f0c0145
			public const int syncMenuMenu_item_sync = 2131493189;
			
			// aapt resource value: 0x7f0c011a
			public const int syncMenu_btnSelectAll = 2131493146;
			
			// aapt resource value: 0x7f0c0119
			public const int syncMenu_lblFreeSpace = 2131493145;
			
			// aapt resource value: 0x7f0c0115
			public const int syncMenu_lblStatus = 2131493141;
			
			// aapt resource value: 0x7f0c0118
			public const int syncMenu_lblTotal = 2131493144;
			
			// aapt resource value: 0x7f0c0117
			public const int syncMenu_listView = 2131493143;
			
			// aapt resource value: 0x7f0c0113
			public const int syncMenu_loadingLayout = 2131493139;
			
			// aapt resource value: 0x7f0c0116
			public const int syncMenu_mainLayout = 2131493142;
			
			// aapt resource value: 0x7f0c0114
			public const int syncMenu_progressBar = 2131493140;
			
			// aapt resource value: 0x7f0c0124
			public const int syncWebBrowser_lblCode = 2131493156;
			
			// aapt resource value: 0x7f0c0120
			public const int syncWebBrowser_lblStep1 = 2131493152;
			
			// aapt resource value: 0x7f0c0121
			public const int syncWebBrowser_lblStep1Details = 2131493153;
			
			// aapt resource value: 0x7f0c0123
			public const int syncWebBrowser_lblStep2 = 2131493155;
			
			// aapt resource value: 0x7f0c0122
			public const int syncWebBrowser_lblUrl = 2131493154;
			
			// aapt resource value: 0x7f0c011f
			public const int syncWebBrowser_mainLayout = 2131493151;
			
			// aapt resource value: 0x7f0c00f5
			public const int sync_btnConnectManually = 2131493109;
			
			// aapt resource value: 0x7f0c00f1
			public const int sync_lblIPAddress = 2131493105;
			
			// aapt resource value: 0x7f0c00f3
			public const int sync_lblStatus = 2131493107;
			
			// aapt resource value: 0x7f0c00f4
			public const int sync_listView = 2131493108;
			
			// aapt resource value: 0x7f0c00f0
			public const int sync_mainLayout = 2131493104;
			
			// aapt resource value: 0x7f0c00f2
			public const int sync_progressBar = 2131493106;
			
			// aapt resource value: 0x7f0c012e
			public const int timeShifting_btnDecrement = 2131493166;
			
			// aapt resource value: 0x7f0c0128
			public const int timeShifting_btnDetectTempo = 2131493160;
			
			// aapt resource value: 0x7f0c012f
			public const int timeShifting_btnIncrement = 2131493167;
			
			// aapt resource value: 0x7f0c0130
			public const int timeShifting_btnReset = 2131493168;
			
			// aapt resource value: 0x7f0c0129
			public const int timeShifting_lblCurrentTempo = 2131493161;
			
			// aapt resource value: 0x7f0c012b
			public const int timeShifting_lblCurrentTempoValue = 2131493163;
			
			// aapt resource value: 0x7f0c0126
			public const int timeShifting_lblDetectedTempo = 2131493158;
			
			// aapt resource value: 0x7f0c0127
			public const int timeShifting_lblDetectedTempoValue = 2131493159;
			
			// aapt resource value: 0x7f0c012a
			public const int timeShifting_lblReferenceTempo = 2131493162;
			
			// aapt resource value: 0x7f0c012c
			public const int timeShifting_lblReferenceTempoValue = 2131493164;
			
			// aapt resource value: 0x7f0c0125
			public const int timeShifting_lblTitle = 2131493157;
			
			// aapt resource value: 0x7f0c012d
			public const int timeShifting_seekBar = 2131493165;
			
			// aapt resource value: 0x7f0c0137
			public const int widgetPlayer = 2131493175;
			
			// aapt resource value: 0x7f0c013f
			public const int widgetPlayerLoading = 2131493183;
			
			// aapt resource value: 0x7f0c0140
			public const int widgetPlayerLoading_lblMessage = 2131493184;
			
			// aapt resource value: 0x7f0c013e
			public const int widgetPlayer_btnNext = 2131493182;
			
			// aapt resource value: 0x7f0c013d
			public const int widgetPlayer_btnPlayPause = 2131493181;
			
			// aapt resource value: 0x7f0c013c
			public const int widgetPlayer_btnPrevious = 2131493180;
			
			// aapt resource value: 0x7f0c0138
			public const int widgetPlayer_imageAlbum = 2131493176;
			
			// aapt resource value: 0x7f0c013a
			public const int widgetPlayer_lblAlbumTitle = 2131493178;
			
			// aapt resource value: 0x7f0c0139
			public const int widgetPlayer_lblArtistName = 2131493177;
			
			// aapt resource value: 0x7f0c013b
			public const int widgetPlayer_lblSongTitle = 2131493179;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_spinner_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AddMarker = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AddPlaylist = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AlbumCell = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int AudioPreferences = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int BigNotificationPlayer = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int CloudConnect = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int EqualizerPresetCell = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int EqualizerPresetDetails = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int EqualizerPresetFaderCell = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int EqualizerPresets = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int FirstRun = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int FolderCell = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int GeneralPreferences = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int GenericCell = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Launch = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int LibraryPreferences = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int LockScreen = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Loops = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Main = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int MarkerCell = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int MarkerDetails = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Markers = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int MobileLibraryBrowser = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int MobileLibraryBrowserCell = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int NotificationPlayer = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int PitchShifting = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Player = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int PlayerMetadata = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Playlist = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int playlist_spinner_item = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int PlaylistCell = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int PlaylistItemCell = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int ResumePlayback = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int ResumePlaybackCell = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int seekbar_preference = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int SelectFolders = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int SelectPlaylist = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int Splash = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int StartResumePlayback = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int Sync = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int SyncCloud = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int SyncDownload = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int SyncManualConnect = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int SyncMenu = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int SyncMenuCell = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int SyncWebBrowser = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int TimeShifting = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int UpdateLibrary = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int WidgetPlayer = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int WidgetPlayerLoading = 2130903091;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int equalizerpresetdetails_menu = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int equalizerpresets_menu = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int main_menu = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int player_menu = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int syncmenu_menu = 2131427332;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int ApplicationName = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int Hello = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0007
			public const int DialogAnimation = 2131361799;
			
			// aapt resource value: 0x7f0a0005
			public const int DialogTheme = 2131361797;
			
			// aapt resource value: 0x7f0a0001
			public const int MyActionBar = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int MyAppTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0003
			public const int MyAppTheme_ActionBar_MenuTextStyle = 2131361795;
			
			// aapt resource value: 0x7f0a0002
			public const int MyAppTheme_ActionBar_TitleTextStyle = 2131361794;
			
			// aapt resource value: 0x7f0a0006
			public const int PreferencesTheme = 2131361798;
			
			// aapt resource value: 0x7f0a0004
			public const int SplashTheme = 2131361796;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f060000
			public const int preferences_audio = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int preferences_cloud = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int preferences_general = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int preferences_headers = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int preferences_library = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int widget_player = 2131099653;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
