// Copyright © 2011-2013 Yanick Castonguay
//
// This file is part of MPfm.
//
// MPfm is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// MPfm is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with MPfm. If not, see <http://www.gnu.org/licenses/>.

using System;
using System.Runtime.InteropServices;

namespace MPfm.Sound.BassWrapper
{
    public enum BASS3DAlgorithm
    {
        BASS_3DALG_DEFAULT,
        BASS_3DALG_OFF,
        BASS_3DALG_FULL,
        BASS_3DALG_LIGHT
    }

    public enum BASS3DMode
    {
        BASS_3DMODE_LEAVECURRENT = -1,
        BASS_3DMODE_NORMAL,
        BASS_3DMODE_RELATIVE,
        BASS_3DMODE_OFF
    }

    public enum BASSActive
    {
        BASS_ACTIVE_STOPPED,
        BASS_ACTIVE_PLAYING,
        BASS_ACTIVE_STALLED,
        BASS_ACTIVE_PAUSED
    }

    public enum BASSAttribute
    {
        BASS_ATTRIB_FREQ = 1,
        BASS_ATTRIB_VOL,
        BASS_ATTRIB_PAN,
        BASS_ATTRIB_EAXMIX,
        BASS_ATTRIB_NOBUFFER,
        BASS_ATTRIB_CPU = 7,
        BASS_ATTRIB_MUSIC_AMPLIFY = 256,
        BASS_ATTRIB_MUSIC_PANSEP,
        BASS_ATTRIB_MUSIC_PSCALER,
        BASS_ATTRIB_MUSIC_BPM,
        BASS_ATTRIB_MUSIC_SPEED,
        BASS_ATTRIB_MUSIC_VOL_GLOBAL,
        BASS_ATTRIB_MUSIC_VOL_CHAN = 512,
        BASS_ATTRIB_MUSIC_VOL_INST = 768,
        BASS_ATTRIB_TEMPO = 65536,
        BASS_ATTRIB_TEMPO_PITCH,
        BASS_ATTRIB_TEMPO_FREQ,
        BASS_ATTRIB_TEMPO_OPTION_USE_AA_FILTER = 65552,
        BASS_ATTRIB_TEMPO_OPTION_AA_FILTER_LENGTH,
        BASS_ATTRIB_TEMPO_OPTION_USE_QUICKALGO,
        BASS_ATTRIB_TEMPO_OPTION_SEQUENCE_MS,
        BASS_ATTRIB_TEMPO_OPTION_SEEKWINDOW_MS,
        BASS_ATTRIB_TEMPO_OPTION_OVERLAP_MS,
        BASS_ATTRIB_TEMPO_OPTION_PREVENT_CLICK,
        BASS_ATTRIB_REVERSE_DIR = 69632,
        BASS_ATTRIB_MIDI_PPQN = 73728,
        BASS_ATTRIB_MIDI_CPU,
        BASS_ATTRIB_MIDI_CHANS,
        BASS_ATTRIB_MIDI_VOICES,
        BASS_ATTRIB_MIDI_TRACK_VOL = 73984
    }

    [Flags]
    public enum BASSChannelType
    {
        BASS_CTYPE_UNKNOWN = 0,
        BASS_CTYPE_SAMPLE = 1,
        BASS_CTYPE_RECORD = 2,
        BASS_CTYPE_MUSIC_MO3 = 256,
        BASS_CTYPE_STREAM = 65536,
        BASS_CTYPE_STREAM_OGG = 65538,
        BASS_CTYPE_STREAM_MP1 = 65539,
        BASS_CTYPE_STREAM_MP2 = 65540,
        BASS_CTYPE_STREAM_MP3 = 65541,
        BASS_CTYPE_STREAM_AIFF = 65542,
        BASS_CTYPE_STREAM_CA = 65543,
        BASS_CTYPE_STREAM_MF = 65544,
        BASS_CTYPE_STREAM_MIXER = 67584,
        BASS_CTYPE_STREAM_SPLIT = 67585,
        BASS_CTYPE_STREAM_WAV = 262144,
        BASS_CTYPE_STREAM_WAV_PCM = 327681,
        BASS_CTYPE_STREAM_WAV_FLOAT = 327683,
        BASS_CTYPE_MUSIC_MOD = 131072,
        BASS_CTYPE_MUSIC_MTM = 131073,
        BASS_CTYPE_MUSIC_S3M = 131074,
        BASS_CTYPE_MUSIC_XM = 131075,
        BASS_CTYPE_MUSIC_IT = 131076,
        BASS_CTYPE_STREAM_WV = 66816,
        BASS_CTYPE_STREAM_WV_H = 66817,
        BASS_CTYPE_STREAM_WV_L = 66818,
        BASS_CTYPE_STREAM_WV_LH = 66819,
        BASS_CTYPE_STREAM_CD = 66048,
        BASS_CTYPE_STREAM_WMA = 66304,
        BASS_CTYPE_STREAM_WMA_MP3 = 66305,
        BASS_CTYPE_STREAM_FLAC = 67840,
        BASS_CTYPE_STREAM_FLAC_OGG = 67841,
        BASS_CTYPE_STREAM_OFR = 67072,
        BASS_CTYPE_STREAM_APE = 67328,
        BASS_CTYPE_STREAM_MPC = 68096,
        BASS_CTYPE_STREAM_AAC = 68352,
        BASS_CTYPE_STREAM_MP4 = 68353,
        BASS_CTYPE_STREAM_SPX = 68608,
        BASS_CTYPE_STREAM_ALAC = 69120,
        BASS_CTYPE_STREAM_TTA = 69376,
        BASS_CTYPE_STREAM_AC3 = 69632,
        BASS_CTYPE_STREAM_WINAMP = 66560,
        BASS_CTYPE_STREAM_MIDI = 68864,
        BASS_CTYPE_STREAM_ADX = 126976,
        BASS_CTYPE_STREAM_VIDEO = 69888
    }

    public enum BASSConfig
    {
        BASS_CONFIG_BUFFER,
        BASS_CONFIG_UPDATEPERIOD,
        BASS_CONFIG_GVOL_SAMPLE = 4,
        BASS_CONFIG_GVOL_STREAM,
        BASS_CONFIG_GVOL_MUSIC,
        BASS_CONFIG_CURVE_VOL,
        BASS_CONFIG_CURVE_PAN,
        BASS_CONFIG_FLOATDSP,
        BASS_CONFIG_3DALGORITHM,
        BASS_CONFIG_NET_TIMEOUT,
        BASS_CONFIG_NET_BUFFER,
        BASS_CONFIG_PAUSE_NOPLAY,
        BASS_CONFIG_NET_PREBUF = 15,
        BASS_CONFIG_NET_AGENT,
        BASS_CONFIG_NET_PROXY,
        BASS_CONFIG_NET_PASSIVE,
        BASS_CONFIG_REC_BUFFER,
        BASS_CONFIG_NET_PLAYLIST = 21,
        BASS_CONFIG_MUSIC_VIRTUAL,
        BASS_CONFIG_VERIFY,
        BASS_CONFIG_UPDATETHREADS,
        BASS_CONFIG_DEV_BUFFER = 27,
        BASS_CONFIG_VISTA_TRUEPOS = 30,
        BASS_CONFIG_MP3_ERRORS = 35,
        BASS_CONFIG_DEV_DEFAULT,
        BASS_CONFIG_NET_READTIMEOUT,
        BASS_CONFIG_AC3_DYNRNG = 65537,
        BASS_CONFIG_WMA_PREBUF = 65793,
        BASS_CONFIG_WMA_BASSFILE = 65795,
        BASS_CONFIG_WMA_NETSEEK,
        BASS_CONFIG_WMA_VIDEO,
        BASS_CONFIG_WMA_ASYNC = 65807,
        BASS_CONFIG_CD_FREEOLD = 66048,
        BASS_CONFIG_CD_RETRY,
        BASS_CONFIG_CD_AUTOSPEED,
        BASS_CONFIG_CD_SKIPERROR,
        BASS_CONFIG_CD_CDDB_SERVER,
        BASS_CONFIG_ENCODE_PRIORITY = 66304,
        BASS_CONFIG_ENCODE_QUEUE,
        BASS_CONFIG_ENCODE_CAST_TIMEOUT = 66320,
        BASS_CONFIG_ENCODE_CAST_PROXY,
        BASS_CONFIG_MIDI_COMPACT = 66560,
        BASS_CONFIG_MIDI_VOICES,
        BASS_CONFIG_MIDI_AUTOFONT,
        BASS_CONFIG_MIDI_DEFFONT,
        BASS_CONFIG_MIXER_FILTER = 67072,
        BASS_CONFIG_MIXER_BUFFER,
        BASS_CONFIG_MIXER_POSEX,
        BASS_CONFIG_SPLIT_BUFFER = 67088,
        BASS_CONFIG_MP4_VIDEO = 67328,
        BASS_CONFIG_AAC_MP4,
        BASS_CONFIG_WINAMP_INPUT_TIMEOUT = 67584,
        BASS_CONFIG_IOS_MIXAUDIO = 34,
        BASS_CONFIG_IOS_SPEAKER = 39,
        BASS_CONFIG_IOS_NOTIFY = 46
    }

    [Flags]
    public enum BASSData
    {
        BASS_DATA_AVAILABLE = 0,
        BASS_DATA_FFT_INDIVIDUAL = 16,
        BASS_DATA_FFT_NOWINDOW = 32,
        BASS_DATA_FFT_REMOVEDC = 64,
        BASS_DATA_FLOAT = 1073741824,
        BASS_DATA_FFT256 = -2147483648,
        BASS_DATA_FFT512 = -2147483647,
        BASS_DATA_FFT1024 = -2147483646,
        BASS_DATA_FFT2048 = -2147483645,
        BASS_DATA_FFT4096 = -2147483644,
        BASS_DATA_FFT8192 = -2147483643,
        BASS_DATA_FFT16384 = -2147483642
    }

    [Flags]
    public enum BASSDeviceInfo
    {
        BASS_DEVICE_NONE = 0,
        BASS_DEVICE_ENABLED = 1,
        BASS_DEVICE_DEFAULT = 2,
        BASS_DEVICE_INIT = 4
    }

    public enum BASSDirectSound
    {
        BASS_OBJECT_DS = 1,
        BASS_OBJECT_DS3DL
    }

    public enum BASSError
    {
        BASS_OK,
        BASS_ERROR_MEM,
        BASS_ERROR_FILEOPEN,
        BASS_ERROR_DRIVER,
        BASS_ERROR_BUFLOST,
        BASS_ERROR_HANDLE,
        BASS_ERROR_FORMAT,
        BASS_ERROR_POSITION,
        BASS_ERROR_INIT,
        BASS_ERROR_START,
        BASS_ERROR_NOCD = 12,
        BASS_ERROR_CDTRACK,
        BASS_ERROR_ALREADY,
        BASS_ERROR_NOPAUSE = 16,
        BASS_ERROR_NOTAUDIO,
        BASS_ERROR_NOCHAN,
        BASS_ERROR_ILLTYPE,
        BASS_ERROR_ILLPARAM,
        BASS_ERROR_NO3D,
        BASS_ERROR_NOEAX,
        BASS_ERROR_DEVICE,
        BASS_ERROR_NOPLAY,
        BASS_ERROR_FREQ,
        BASS_ERROR_NOTFILE = 27,
        BASS_ERROR_NOHW = 29,
        BASS_ERROR_EMPTY = 31,
        BASS_ERROR_NONET,
        BASS_ERROR_CREATE,
        BASS_ERROR_NOFX,
        BASS_ERROR_PLAYING,
        BASS_ERROR_NOTAVAIL = 37,
        BASS_ERROR_DECODE,
        BASS_ERROR_DX,
        BASS_ERROR_TIMEOUT,
        BASS_ERROR_FILEFORM,
        BASS_ERROR_SPEAKER,
        BASS_ERROR_VERSION,
        BASS_ERROR_CODEC,
        BASS_ERROR_ENDED,
        BASS_ERROR_BUSY,
        BASS_ERROR_UNKNOWN = -1,
        BASS_ERROR_WMA_LICENSE = 1000,
        BASS_ERROR_WMA_WM9,
        BASS_ERROR_WMA_DENIED,
        BASS_ERROR_WMA_CODEC,
        BASS_ERROR_WMA_INDIVIDUAL,
        BASS_ERROR_ACM_CANCEL = 2000,
        BASS_ERROR_CAST_DENIED = 2100,
        BASS_VST_ERROR_NOINPUTS = 3000,
        BASS_VST_ERROR_NOOUTPUTS,
        BASS_VST_ERROR_NOREALTIME,
        BASS_FX_ERROR_NODECODE = 4000,
        BASS_FX_ERROR_BPMINUSE,
        BASS_ERROR_VIDEO_ABORT = 47,
        BASS_ERROR_VIDEO_CANNOT_CONNECT,
        BASS_ERROR_VIDEO_CANNOT_READ,
        BASS_ERROR_VIDEO_CANNOT_WRITE,
        BASS_ERROR_VIDEO_FAILURE,
        BASS_ERROR_VIDEO_FILTER,
        BASS_ERROR_VIDEO_INVALID_CHAN,
        BASS_ERROR_VIDEO_INVALID_DLL,
        BASS_ERROR_VIDEO_INVALID_FORMAT,
        BASS_ERROR_VIDEO_INVALID_HANDLE,
        BASS_ERROR_VIDEO_INVALID_PARAMETER,
        BASS_ERROR_VIDEO_NO_AUDIO,
        BASS_ERROR_VIDEO_NO_EFFECT,
        BASS_ERROR_VIDEO_NO_INTERFACE,
        BASS_ERROR_VIDEO_NO_RENDERER,
        BASS_ERROR_VIDEO_NO_SUPPORT,
        BASS_ERROR_VIDEO_NO_VIDEO,
        BASS_ERROR_VIDEO_NOT_ALLOWED,
        BASS_ERROR_VIDEO_NOT_CONNECTED,
        BASS_ERROR_VIDEO_NOT_EXISTS,
        BASS_ERROR_VIDEO_NOT_FOUND,
        BASS_ERROR_VIDEO_NOT_READY,
        BASS_ERROR_VIDEO_NULL_DEVICE,
        BASS_ERROR_VIDEO_OPEN,
        BASS_ERROR_VIDEO_OUTOFMEMORY,
        BASS_ERROR_VIDEO_PARTIAL_RENDER,
        BASS_ERROR_VIDEO_TIME_OUT,
        BASS_ERROR_VIDEO_UNKNOWN_FILE_TYPE,
        BASS_ERROR_VIDEO_UNSUPPORT_STREAM,
        BASS_ERROR_VIDEO_VIDEO_FILTER,
        BASS_ERROR_WASAPI = 5000
    }

    [Flags]
    public enum BASSFlag
    {
        BASS_DEFAULT = 0,
        BASS_SAMPLE_8BITS = 1,
        BASS_SAMPLE_MONO = 2,
        BASS_SAMPLE_LOOP = 4,
        BASS_SAMPLE_3D = 8,
        BASS_SAMPLE_SOFTWARE = 16,
        BASS_SAMPLE_MUTEMAX = 32,
        BASS_SAMPLE_VAM = 64,
        BASS_SAMPLE_FX = 128,
        BASS_SAMPLE_FLOAT = 256,
        BASS_RECORD_PAUSE = 32768,
        BASS_STREAM_PRESCAN = 131072,
        BASS_STREAM_AUTOFREE = 262144,
        BASS_STREAM_RESTRATE = 524288,
        BASS_STREAM_BLOCK = 1048576,
        BASS_STREAM_DECODE = 2097152,
        BASS_STREAM_STATUS = 8388608,
        BASS_SPEAKER_FRONT = 16777216,
        BASS_SPEAKER_REAR = 33554432,
        BASS_SPEAKER_CENLFE = 50331648,
        BASS_SPEAKER_REAR2 = 67108864,
        BASS_SPEAKER_LEFT = 268435456,
        BASS_SPEAKER_RIGHT = 536870912,
        BASS_SPEAKER_FRONTLEFT = 285212672,
        BASS_SPEAKER_FRONTRIGHT = 553648128,
        BASS_SPEAKER_REARLEFT = 301989888,
        BASS_SPEAKER_REARRIGHT = 570425344,
        BASS_SPEAKER_CENTER = 318767104,
        BASS_SPEAKER_LFE = 587202560,
        BASS_SPEAKER_REAR2LEFT = 335544320,
        BASS_SPEAKER_REAR2RIGHT = 603979776,
        BASS_SPEAKER_PAIR1 = 16777216,
        BASS_SPEAKER_PAIR2 = 33554432,
        BASS_SPEAKER_PAIR3 = 50331648,
        BASS_SPEAKER_PAIR4 = 67108864,
        BASS_SPEAKER_PAIR5 = 83886080,
        BASS_SPEAKER_PAIR6 = 100663296,
        BASS_SPEAKER_PAIR7 = 117440512,
        BASS_SPEAKER_PAIR8 = 134217728,
        BASS_SPEAKER_PAIR9 = 150994944,
        BASS_SPEAKER_PAIR10 = 167772160,
        BASS_SPEAKER_PAIR11 = 184549376,
        BASS_SPEAKER_PAIR12 = 201326592,
        BASS_SPEAKER_PAIR13 = 218103808,
        BASS_SPEAKER_PAIR14 = 234881024,
        BASS_SPEAKER_PAIR15 = 251658240,
        BASS_UNICODE = -2147483648,
        BASS_SAMPLE_OVER_VOL = 65536,
        BASS_SAMPLE_OVER_POS = 131072,
        BASS_SAMPLE_OVER_DIST = 196608,
        BASS_WV_STEREO = 4194304,
        BASS_AC3_DOWNMIX_2 = 512,
        BASS_AC3_DOWNMIX_4 = 1024,
        BASS_AC3_DOWNMIX_DOLBY = 1536,
        BASS_AC3_DYNAMIC_RANGE = 2048,
        BASS_AAC_STEREO = 4194304,
        BASS_MIXER_END = 65536,
        BASS_MIXER_PAUSE = 131072,
        BASS_MIXER_NONSTOP = 131072,
        BASS_MIXER_RESUME = 4096,
        BASS_MIXER_POSEX = 8192,
        BASS_MIXER_LIMIT = 16384,
        BASS_MIXER_MATRIX = 65536,
        BASS_MIXER_DOWNMIX = 4194304,
        BASS_MIXER_NORAMPIN = 8388608,
        BASS_MIXER_FILTER = 4096,
        BASS_MIXER_BUFFER = 8192,
        BASS_CD_SUBCHANNEL = 512,
        BASS_CD_SUBCHANNEL_NOHW = 1024,
        BASS_CD_C2ERRORS = 2048,
        BASS_MIDI_DECAYEND = 4096,
        BASS_MIDI_NOFX = 8192,
        BASS_MIDI_DECAYSEEK = 16384,
        BASS_FX_FREESOURCE = 65536,
        BASS_FX_BPM_BKGRND = 1,
        BASS_FX_BPM_MULT2 = 2,
        BASS_MUSIC_FLOAT = 256,
        BASS_MUSIC_MONO = 2,
        BASS_MUSIC_LOOP = 4,
        BASS_MUSIC_3D = 8,
        BASS_MUSIC_FX = 128,
        BASS_MUSIC_AUTOFREE = 262144,
        BASS_MUSIC_DECODE = 2097152,
        BASS_MUSIC_PRESCAN = 131072,
        BASS_MUSIC_RAMP = 512,
        BASS_MUSIC_RAMPS = 1024,
        BASS_MUSIC_SURROUND = 2048,
        BASS_MUSIC_SURROUND2 = 4096,
        BASS_MUSIC_FT2MOD = 8192,
        BASS_MUSIC_PT1MOD = 16384,
        BASS_MUSIC_NONINTER = 65536,
        BASS_MUSIC_SINCINTER = 8388608,
        BASS_MUSIC_POSRESET = 32768,
        BASS_MUSIC_POSRESETEX = 4194304,
        BASS_MUSIC_STOPBACK = 524288,
        BASS_MUSIC_NOSAMPLE = 1048576
    }

    public enum BASSFXPhase
    {
        BASS_FX_PHASE_NEG_180,
        BASS_FX_PHASE_NEG_90,
        BASS_FX_PHASE_ZERO,
        BASS_FX_PHASE_90,
        BASS_FX_PHASE_180
    }

    public enum BASSFXType
    {
        BASS_FX_DX8_CHORUS,
        BASS_FX_DX8_COMPRESSOR,
        BASS_FX_DX8_DISTORTION,
        BASS_FX_DX8_ECHO,
        BASS_FX_DX8_FLANGER,
        BASS_FX_DX8_GARGLE,
        BASS_FX_DX8_I3DL2REVERB,
        BASS_FX_DX8_PARAMEQ,
        BASS_FX_DX8_REVERB,
        BASS_FX_BFX_ROTATE = 65536,
        BASS_FX_BFX_ECHO,
        BASS_FX_BFX_FLANGER,
        BASS_FX_BFX_VOLUME,
        BASS_FX_BFX_PEAKEQ,
        BASS_FX_BFX_REVERB,
        BASS_FX_BFX_LPF,
        BASS_FX_BFX_MIX,
        BASS_FX_BFX_DAMP,
        BASS_FX_BFX_AUTOWAH,
        BASS_FX_BFX_ECHO2,
        BASS_FX_BFX_PHASER,
        BASS_FX_BFX_ECHO3,
        BASS_FX_BFX_CHORUS,
        BASS_FX_BFX_APF,
        BASS_FX_BFX_COMPRESSOR,
        BASS_FX_BFX_DISTORTION,
        BASS_FX_BFX_COMPRESSOR2,
        BASS_FX_BFX_VOLUME_ENV,
        BASS_FX_BFX_BQF
    }

    [Flags]
    public enum BASSInfo
    {
        DSCAPS_NONE = 0,
        DSCAPS_CONTINUOUSRATE = 16,
        DSCAPS_EMULDRIVER = 32,
        DSCAPS_CERTIFIED = 64,
        DSCAPS_SECONDARYMONO = 256,
        DSCAPS_SECONDARYSTEREO = 512,
        DSCAPS_SECONDARY8BIT = 1024,
        DSCAPS_SECONDARY16BIT = 2048
    }

    [Flags]
    public enum BASSInit
    {
        BASS_DEVICE_DEFAULT = 0,
        BASS_DEVICE_8BITS = 1,
        BASS_DEVICE_MONO = 2,
        BASS_DEVICE_3D = 4,
        BASS_DEVICE_LATENCY = 256,
        BASS_DEVICE_CPSPEAKERS = 1024,
        BASS_DEVICE_SPEAKERS = 2048,
        BASS_DEVICE_NOSPEAKER = 4096,
        BASS_DEVIDE_DMIX = 8192
    }

    [Flags]
    public enum BASSInput
    {
        BASS_INPUT_NONE = 0,
        BASS_INPUT_OFF = 65536,
        BASS_INPUT_ON = 131072
    }

    [Flags]
    public enum BASSInputType
    {
        BASS_INPUT_TYPE_ERROR = -1,
        BASS_INPUT_TYPE_MASK = -16777216,
        BASS_INPUT_TYPE_UNDEF = 0,
        BASS_INPUT_TYPE_DIGITAL = 16777216,
        BASS_INPUT_TYPE_LINE = 33554432,
        BASS_INPUT_TYPE_MIC = 50331648,
        BASS_INPUT_TYPE_SYNTH = 67108864,
        BASS_INPUT_TYPE_CD = 83886080,
        BASS_INPUT_TYPE_PHONE = 100663296,
        BASS_INPUT_TYPE_SPEAKER = 117440512,
        BASS_INPUT_TYPE_WAVE = 134217728,
        BASS_INPUT_TYPE_AUX = 150994944,
        BASS_INPUT_TYPE_ANALOG = 167772160
    }

    [Flags]
    public enum BASSMode
    {
        BASS_POS_BYTES = 0,
        BASS_POS_MUSIC_ORDERS = 1,
        BASS_POS_MIDI_TICK = 2,
        BASS_MUSIC_POSRESET = 32768,
        BASS_MUSIC_POSRESETEX = 4194304,
        BASS_MIXER_NORAMPIN = 8388608,
        BASS_POS_DECODE = 268435456,
        BASS_POS_DECODETO = 536870912,
        BASS_MIDI_DECAYSEEK = 16384
    }

    [Flags]
    public enum BASSRecordFormat
    {
        WAVE_FORMAT_UNKNOWN = 0,
        WAVE_FORMAT_1M08 = 1,
        WAVE_FORMAT_1S08 = 2,
        WAVE_FORMAT_1M16 = 4,
        WAVE_FORMAT_1S16 = 8,
        WAVE_FORMAT_2M08 = 16,
        WAVE_FORMAT_2S08 = 32,
        WAVE_FORMAT_2M16 = 64,
        WAVE_FORMAT_2S16 = 128,
        WAVE_FORMAT_4M08 = 256,
        WAVE_FORMAT_4S08 = 512,
        WAVE_FORMAT_4M16 = 1024,
        WAVE_FORMAT_4S16 = 2048,
        WAVE_FORMAT_48M08 = 4096,
        WAVE_FORMAT_48S08 = 8192,
        WAVE_FORMAT_48M16 = 16384,
        WAVE_FORMAT_48S16 = 32768,
        WAVE_FORMAT_96M08 = 65536,
        WAVE_FORMAT_96S08 = 131072,
        WAVE_FORMAT_96M16 = 262144,
        WAVE_FORMAT_96S16 = 524288
    }

    [Flags]
    public enum BASSRecordInfo
    {
        DSCAPS_NONE = 0,
        DSCAPS_EMULDRIVER = 32,
        DSCAPS_CERTIFIED = 64
    }

    public enum BASSStreamFilePosition
    {
        BASS_FILEPOS_CURRENT,
        BASS_FILEPOS_DOWNLOAD,
        BASS_FILEPOS_END,
        BASS_FILEPOS_START,
        BASS_FILEPOS_CONNECTED,
        BASS_FILEPOS_BUFFER,
        BASS_FILEPOS_WMA_BUFFER = 1000
    }

    public enum BASSStreamProc
    {
        STREAMPROC_DUMMY,
        STREAMPROC_PUSH = -1,
        BASS_STREAMPROC_END = -2147483648
    }

    public enum BASSStreamSystem
    {
        STREAMFILE_NOBUFFER,
        STREAMFILE_BUFFER,
        STREAMFILE_BUFFERPUSH
    }

    [Flags]
    public enum BASSSync
    {
        BASS_SYNC_POS = 0,
        BASS_SYNC_MUSICINST = 1,
        BASS_SYNC_END = 2,
        BASS_SYNC_MUSICFX = 3,
        BASS_SYNC_META = 4,
        BASS_SYNC_SLIDE = 5,
        BASS_SYNC_STALL = 6,
        BASS_SYNC_DOWNLOAD = 7,
        BASS_SYNC_FREE = 8,
        BASS_SYNC_MUSICPOS = 10,
        BASS_SYNC_SETPOS = 11,
        BASS_SYNC_OGG_CHANGE = 12,
        BASS_SYNC_MIXTIME = 1073741824,
        BASS_SYNC_ONETIME = -2147483648,
        BASS_SYNC_MIXER_ENVELOPE = 66048,
        BASS_SYNC_MIXER_ENVELOPE_NODE = 66049,
        BASS_SYNC_WMA_CHANGE = 65792,
        BASS_SYNC_WMA_META = 65793,
        BASS_SYNC_CD_ERROR = 1000,
        BASS_SYNC_CD_SPEED = 1002,
        BASS_WINAMP_SYNC_BITRATE = 100,
        BASS_SYNC_MIDI_MARKER = 65536,
        BASS_SYNC_MIDI_CUE = 65537,
        BASS_SYNC_MIDI_LYRIC = 65538,
        BASS_SYNC_MIDI_TEXT = 65539,
        BASS_SYNC_MIDI_EVENT = 65540,
        BASS_SYNC_MIDI_TICK = 65541,
        BASS_SYNC_MIDI_TIMESIG = 65542,
        BASS_SYNC_MIDI_KEYSIG = 65543
    }

    public enum BASSTag
    {
        BASS_TAG_ID3,
        BASS_TAG_ID3V2,
        BASS_TAG_OGG,
        BASS_TAG_HTTP,
        BASS_TAG_ICY,
        BASS_TAG_META,
        BASS_TAG_APE,
        BASS_TAG_MP4,
        BASS_TAG_WMA,
        BASS_TAG_VENDOR,
        BASS_TAG_LYRICS3,
        BASS_TAG_WMA_META,
        BASS_TAG_CA_CODEC = 11,
        BASS_TAG_FLAC_CUE,
        BASS_TAG_WMA_CODEC = 12,
        BASS_TAG_MF,
        BASS_TAG_WAVEFORMAT,
        BASS_TAG_RIFF_INFO = 256,
        BASS_TAG_RIFF_BEXT,
        BASS_TAG_RIFF_CART,
        BASS_TAG_RIFF_DISP,
        BASS_TAG_APE_BINARY = 4096,
        BASS_TAG_MUSIC_NAME = 65536,
        BASS_TAG_MUSIC_MESSAGE,
        BASS_TAG_MUSIC_ORDERS,
        BASS_TAG_MUSIC_INST = 65792,
        BASS_TAG_MUSIC_SAMPLE = 66304,
        BASS_TAG_MIDI_TRACK = 69632,
        BASS_TAG_ADX_LOOP = 73728,
        BASS_TAG_FLAC_PICTURE = 73728,
        BASS_TAG_UNKNOWN = -1
    }

    [Flags]
    public enum BASSVam
    {
        BASS_VAM_HARDWARE = 1,
        BASS_VAM_SOFTWARE = 2,
        BASS_VAM_TERM_TIME = 4,
        BASS_VAM_TERM_DIST = 8,
        BASS_VAM_TERM_PRIO = 16
    }

    public enum WAVEFormatTag : short
    {
        UNKNOWN,
        PCM,
        ADPCM,
        IEEE_FLOAT,
        DOLBY_AC2 = 48,
        GSM610,
        MSNAUDIO,
        MPEG = 80,
        MPEGLAYER3 = 85,
        DOLBY_AC3_SPDIF = 146,
        RAW_AAC1 = 255,
        MSAUDIO1 = 352,
        WMA,
        WMA_PRO,
        WMA_LOSSLESS,
        WMA_SPDIF,
        MPEG_ADTS_AAC = 5632,
        MPEG_RAW_AAC,
        MPEG_LOAS,
        MPEG_HEAAC = 5648,
        EXTENSIBLE = -2
    }

    [Flags]
    public enum BASSIOSNotify
    {
        BASS_IOSNOTIFY_INTERRUPT = 1,
        BASS_IOSNOTIFY_INTERRUPT_END = 2
    }
}
