
// This file has been generated by the GUI designer. Do not modify.
namespace MPfm.GTK
{
	public partial class SyncCloudWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Button btnLogin;
		private global::Gtk.Button btnLogout;
		private global::Gtk.Button btnPull;
		private global::Gtk.Button btnPush;
		private global::Gtk.Button btnDelete;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MPfm.GTK.SyncCloudWindow
			this.Name = "MPfm.GTK.SyncCloudWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SyncCloudWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MPfm.GTK.SyncCloudWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Sync (Cloud)");
			this.vbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Dropbox");
			this.vbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label3]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Dropbox");
			this.vbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label4]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Dropbox");
			this.vbox2.Add (this.label5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label5]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Dropbox");
			this.vbox2.Add (this.label6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label6]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnLogin = new global::Gtk.Button ();
			this.btnLogin.CanFocus = true;
			this.btnLogin.Name = "btnLogin";
			this.btnLogin.UseUnderline = true;
			this.btnLogin.Label = global::Mono.Unix.Catalog.GetString ("Enable Dropbox Sync");
			this.vbox2.Add (this.btnLogin);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnLogin]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnLogout = new global::Gtk.Button ();
			this.btnLogout.CanFocus = true;
			this.btnLogout.Name = "btnLogout";
			this.btnLogout.UseUnderline = true;
			this.btnLogout.Label = global::Mono.Unix.Catalog.GetString ("Disable Dropbox Sync");
			this.vbox2.Add (this.btnLogout);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnLogout]));
			w7.Position = 6;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnPull = new global::Gtk.Button ();
			this.btnPull.CanFocus = true;
			this.btnPull.Name = "btnPull";
			this.btnPull.UseUnderline = true;
			this.btnPull.Label = global::Mono.Unix.Catalog.GetString ("Pull");
			this.vbox2.Add (this.btnPull);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnPull]));
			w8.Position = 7;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnPush = new global::Gtk.Button ();
			this.btnPush.CanFocus = true;
			this.btnPush.Name = "btnPush";
			this.btnPush.UseUnderline = true;
			this.btnPush.Label = global::Mono.Unix.Catalog.GetString ("Push");
			this.vbox2.Add (this.btnPush);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnPush]));
			w9.Position = 8;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnDelete = new global::Gtk.Button ();
			this.btnDelete.CanFocus = true;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.UseUnderline = true;
			this.btnDelete.Label = global::Mono.Unix.Catalog.GetString ("Delete");
			this.vbox2.Add (this.btnDelete);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnDelete]));
			w10.Position = 9;
			w10.Expand = false;
			w10.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
