
// This file has been generated by the GUI designer. Do not modify.
namespace MPfm.GTK
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action actionExit;
		private global::Gtk.Action actionAbout;
		private global::Gtk.Action actionHelp;
		private global::Gtk.Action aboutAction;
		private global::Gtk.Action PlaybackAction;
		private global::Gtk.Action actionPlay;
		private global::Gtk.Action actionPause;
		private global::Gtk.Action actionStop;
		private global::Gtk.Action actionPrevious;
		private global::Gtk.Action actionNext;
		private global::Gtk.Action actionRepeatType;
		private global::Gtk.Action openAction;
		private global::Gtk.Action actionUpdateLibrary;
		private global::Gtk.Action actionSettings;
		private global::Gtk.Action actionEffects;
		private global::Gtk.Action WindowsAction;
		private global::Gtk.Action actionPlaylist;
		private global::Gtk.Action actionRemoveLoop;
		private global::Gtk.Action actionAddMarker;
		private global::Gtk.Action actionRemoveMarker;
		private global::Gtk.Action actionEditLoop;
		private global::Gtk.Action actionStopLoop;
		private global::Gtk.Action actionEditMarker;
		private global::Gtk.Action actionGoToMarker;
		private global::Gtk.Action actionAddFiles;
		private global::Gtk.Action actionAddFolder;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action actionPlayLoop;
		private global::Gtk.VBox vboxMain;
		private global::Gtk.MenuBar menubarMain;
		private global::Gtk.Toolbar toolbarMain;
		private global::Gtk.HPaned hpanedMain;
		private global::Gtk.VBox vboxLeft;
		private global::Gtk.Label lblLibraryBrowser;
		private global::Gtk.Label lblLibraryFilter;
		private global::Gtk.ComboBox cboSoundFormat;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView treeLibraryBrowser;
		private global::Gtk.VBox vboxRight;
		private global::Gtk.VBox vboxCurrentSong;
		private global::Gtk.Label lblCurrentSong;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Image imageAlbumCover;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox5;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label lblArtistName;
		private global::Gtk.Label lblAlbumTitle;
		private global::Gtk.Label lblSongTitle;
		private global::Gtk.Label lblSongFilePath;
		private global::Gtk.VBox vbox10;
		private global::Gtk.Label lblInformation;
		private global::Gtk.Label lblCurrentFileType;
		private global::Gtk.Label lblCurrentBitrate;
		private global::Gtk.Label lblCurrentSampleRate;
		private global::Gtk.HBox hbox6;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label lblPosition;
		private global::Gtk.Label lblCurrentPosition;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label lblLength;
		private global::Gtk.Label lblCurrentLength;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label lblSongPosition;
		private global::Gtk.HScale hscaleSongPosition;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Label lblTimeShifting;
		private global::Gtk.HScale hscaleTimeShifting;
		private global::Gtk.VBox vbox9;
		private global::Gtk.Label lblVolume;
		private global::Gtk.VScale vscaleVolume;
		private global::Gtk.VPaned vpanedLoopsMarkersSongBrowser;
		private global::Gtk.HPaned hpanedLoopsMarkers;
		private global::Gtk.VBox vboxLoops;
		private global::Gtk.Label lblLoops;
		private global::Gtk.Toolbar toolbarLoops;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TreeView treeLoops;
		private global::Gtk.VBox vboxLoops1;
		private global::Gtk.Label lblMarkers;
		private global::Gtk.Toolbar toolbarMarkers;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.TreeView treeMarkers;
		private global::Gtk.VBox vboxSongBrowser;
		private global::Gtk.Label lblSongBrowser;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button btnPlaySelectedSongs;
		private global::Gtk.Button btnEditSongMetadata;
		private global::Gtk.Button btnAddToPlaylist;
		private global::Gtk.Label lblSearchFor;
		private global::Gtk.Entry txtSearch;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeSongBrowser;
		private global::Gtk.Statusbar statusbar1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MPfm.GTK.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.actionExit = new global::Gtk.Action ("actionExit", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-quit");
			this.actionExit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.actionExit, null);
			this.actionAbout = new global::Gtk.Action ("actionAbout", global::Mono.Unix.Catalog.GetString ("About MPfm"), null, null);
			this.actionAbout.ShortLabel = global::Mono.Unix.Catalog.GetString ("About MPfm");
			w1.Add (this.actionAbout, null);
			this.actionHelp = new global::Gtk.Action ("actionHelp", global::Mono.Unix.Catalog.GetString ("Help"), null, "gtk-help");
			this.actionHelp.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.actionHelp, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About MPfm"), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About MPfm");
			w1.Add (this.aboutAction, null);
			this.PlaybackAction = new global::Gtk.Action ("PlaybackAction", global::Mono.Unix.Catalog.GetString ("Playback"), null, null);
			this.PlaybackAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Playback");
			w1.Add (this.PlaybackAction, null);
			this.actionPlay = new global::Gtk.Action ("actionPlay", global::Mono.Unix.Catalog.GetString ("Play"), null, "gtk-media-play");
			this.actionPlay.ShortLabel = global::Mono.Unix.Catalog.GetString ("Play");
			w1.Add (this.actionPlay, null);
			this.actionPause = new global::Gtk.Action ("actionPause", global::Mono.Unix.Catalog.GetString ("Pause"), null, "gtk-media-pause");
			this.actionPause.ShortLabel = global::Mono.Unix.Catalog.GetString ("Pause");
			w1.Add (this.actionPause, null);
			this.actionStop = new global::Gtk.Action ("actionStop", global::Mono.Unix.Catalog.GetString ("Stop"), null, "gtk-media-stop");
			this.actionStop.ShortLabel = global::Mono.Unix.Catalog.GetString ("Stop");
			w1.Add (this.actionStop, null);
			this.actionPrevious = new global::Gtk.Action ("actionPrevious", global::Mono.Unix.Catalog.GetString ("Previous Song"), null, "gtk-media-previous");
			this.actionPrevious.ShortLabel = global::Mono.Unix.Catalog.GetString ("Previous Song");
			w1.Add (this.actionPrevious, null);
			this.actionNext = new global::Gtk.Action ("actionNext", global::Mono.Unix.Catalog.GetString ("Next Song"), null, "gtk-media-next");
			this.actionNext.ShortLabel = global::Mono.Unix.Catalog.GetString ("Next Song");
			w1.Add (this.actionNext, null);
			this.actionRepeatType = new global::Gtk.Action ("actionRepeatType", global::Mono.Unix.Catalog.GetString ("Repeat Type (Off)"), null, "stock_repeat");
			this.actionRepeatType.ShortLabel = global::Mono.Unix.Catalog.GetString ("Repeat Type (Off)");
			w1.Add (this.actionRepeatType, null);
			this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open audio files..."), null, "gtk-open");
			this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open Audio Files");
			w1.Add (this.openAction, null);
			this.actionUpdateLibrary = new global::Gtk.Action ("actionUpdateLibrary", global::Mono.Unix.Catalog.GetString ("Update Library"), null, "gtk-refresh");
			this.actionUpdateLibrary.ShortLabel = global::Mono.Unix.Catalog.GetString ("Update Library");
			w1.Add (this.actionUpdateLibrary, null);
			this.actionSettings = new global::Gtk.Action ("actionSettings", global::Mono.Unix.Catalog.GetString ("Settings"), null, "gtk-preferences");
			this.actionSettings.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
			w1.Add (this.actionSettings, null);
			this.actionEffects = new global::Gtk.Action ("actionEffects", global::Mono.Unix.Catalog.GetString ("Effects"), null, "stock_volume");
			this.actionEffects.ShortLabel = global::Mono.Unix.Catalog.GetString ("Effects");
			w1.Add (this.actionEffects, null);
			this.WindowsAction = new global::Gtk.Action ("WindowsAction", global::Mono.Unix.Catalog.GetString ("Windows"), null, null);
			this.WindowsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Windows");
			w1.Add (this.WindowsAction, null);
			this.actionPlaylist = new global::Gtk.Action ("actionPlaylist", global::Mono.Unix.Catalog.GetString ("Playlist"), null, "gtk-dnd-multiple");
			this.actionPlaylist.ShortLabel = global::Mono.Unix.Catalog.GetString ("Playlist");
			w1.Add (this.actionPlaylist, null);
			this.actionRemoveLoop = new global::Gtk.Action ("actionRemoveLoop", null, null, "gtk-remove");
			w1.Add (this.actionRemoveLoop, null);
			this.actionAddMarker = new global::Gtk.Action ("actionAddMarker", null, null, "gtk-add");
			w1.Add (this.actionAddMarker, null);
			this.actionRemoveMarker = new global::Gtk.Action ("actionRemoveMarker", null, null, "gtk-remove");
			w1.Add (this.actionRemoveMarker, null);
			this.actionEditLoop = new global::Gtk.Action ("actionEditLoop", null, null, "gtk-edit");
			w1.Add (this.actionEditLoop, null);
			this.actionStopLoop = new global::Gtk.Action ("actionStopLoop", null, null, "gtk-media-stop");
			w1.Add (this.actionStopLoop, null);
			this.actionEditMarker = new global::Gtk.Action ("actionEditMarker", null, null, "gtk-edit");
			w1.Add (this.actionEditMarker, null);
			this.actionGoToMarker = new global::Gtk.Action ("actionGoToMarker", null, null, "gtk-go-forward");
			w1.Add (this.actionGoToMarker, null);
			this.actionAddFiles = new global::Gtk.Action ("actionAddFiles", global::Mono.Unix.Catalog.GetString ("Add files to library..."), null, "gtk-add");
			this.actionAddFiles.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add files to library...");
			w1.Add (this.actionAddFiles, null);
			this.actionAddFolder = new global::Gtk.Action ("actionAddFolder", global::Mono.Unix.Catalog.GetString ("Add folder to library..."), null, "gtk-add");
			this.actionAddFolder.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add folder to library...");
			w1.Add (this.actionAddFolder, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.actionPlayLoop = new global::Gtk.Action ("actionPlayLoop", null, null, "gtk-media-play");
			w1.Add (this.actionPlayLoop, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "MPfm.GTK.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MPfm: Music Player for Musicians");
			this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./icon48.png"));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 100;
			// Container child MPfm.GTK.MainWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubarMain'><menu name='FileAction' action='FileAction'><menuitem name='actionAddFiles' action='actionAddFiles'/><menuitem name='actionAddFolder' action='actionAddFolder'/><separator/><menuitem name='openAction' action='openAction'/><separator/><menuitem name='actionUpdateLibrary' action='actionUpdateLibrary'/><separator/><menuitem name='actionExit' action='actionExit'/></menu><menu name='PlaybackAction' action='PlaybackAction'><menuitem name='actionPlay' action='actionPlay'/><menuitem name='actionPause' action='actionPause'/><menuitem name='actionStop' action='actionStop'/><menuitem name='actionPrevious' action='actionPrevious'/><menuitem name='actionNext' action='actionNext'/><menuitem name='actionRepeatType' action='actionRepeatType'/></menu><menu name='WindowsAction' action='WindowsAction'/><menu name='HelpAction' action='HelpAction'><menuitem name='actionHelp' action='actionHelp'/><menuitem name='actionAbout' action='actionAbout'/></menu></menubar></ui>");
			this.menubarMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubarMain")));
			this.menubarMain.Name = "menubarMain";
			this.vboxMain.Add (this.menubarMain);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.menubarMain]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbarMain'><toolitem name='openAction' action='openAction'/><separator/><toolitem name='actionUpdateLibrary' action='actionUpdateLibrary'/><separator/><toolitem name='actionPlay' action='actionPlay'/><toolitem name='actionPause' action='actionPause'/><toolitem name='actionStop' action='actionStop'/><toolitem name='actionPrevious' action='actionPrevious'/><toolitem name='actionNext' action='actionNext'/><toolitem name='actionRepeatType' action='actionRepeatType'/><separator/><toolitem name='actionPlaylist' action='actionPlaylist'/><toolitem name='actionEffects' action='actionEffects'/><toolitem name='actionSettings' action='actionSettings'/></toolbar></ui>");
			this.toolbarMain = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbarMain")));
			this.toolbarMain.Name = "toolbarMain";
			this.toolbarMain.ShowArrow = false;
			this.toolbarMain.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.toolbarMain.IconSize = ((global::Gtk.IconSize)(2));
			this.vboxMain.Add (this.toolbarMain);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.toolbarMain]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hpanedMain = new global::Gtk.HPaned ();
			this.hpanedMain.CanFocus = true;
			this.hpanedMain.Name = "hpanedMain";
			this.hpanedMain.Position = 236;
			// Container child hpanedMain.Gtk.Paned+PanedChild
			this.vboxLeft = new global::Gtk.VBox ();
			this.vboxLeft.Name = "vboxLeft";
			this.vboxLeft.Spacing = 6;
			this.vboxLeft.BorderWidth = ((uint)(4));
			// Container child vboxLeft.Gtk.Box+BoxChild
			this.lblLibraryBrowser = new global::Gtk.Label ();
			this.lblLibraryBrowser.Name = "lblLibraryBrowser";
			this.lblLibraryBrowser.Xalign = 0F;
			this.lblLibraryBrowser.LabelProp = global::Mono.Unix.Catalog.GetString ("Library Browser");
			this.vboxLeft.Add (this.lblLibraryBrowser);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxLeft [this.lblLibraryBrowser]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vboxLeft.Gtk.Box+BoxChild
			this.lblLibraryFilter = new global::Gtk.Label ();
			this.lblLibraryFilter.Name = "lblLibraryFilter";
			this.lblLibraryFilter.Xalign = 0F;
			this.lblLibraryFilter.LabelProp = global::Mono.Unix.Catalog.GetString ("Filter by Sound Format:");
			this.vboxLeft.Add (this.lblLibraryFilter);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxLeft [this.lblLibraryFilter]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxLeft.Gtk.Box+BoxChild
			this.cboSoundFormat = global::Gtk.ComboBox.NewText ();
			this.cboSoundFormat.Name = "cboSoundFormat";
			this.vboxLeft.Add (this.cboSoundFormat);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxLeft [this.cboSoundFormat]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vboxLeft.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeLibraryBrowser = new global::Gtk.TreeView ();
			this.treeLibraryBrowser.CanFocus = true;
			this.treeLibraryBrowser.Name = "treeLibraryBrowser";
			this.GtkScrolledWindow1.Add (this.treeLibraryBrowser);
			this.vboxLeft.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxLeft [this.GtkScrolledWindow1]));
			w8.Position = 3;
			this.hpanedMain.Add (this.vboxLeft);
			global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.hpanedMain [this.vboxLeft]));
			w9.Resize = false;
			// Container child hpanedMain.Gtk.Paned+PanedChild
			this.vboxRight = new global::Gtk.VBox ();
			this.vboxRight.Name = "vboxRight";
			this.vboxRight.Spacing = 6;
			this.vboxRight.BorderWidth = ((uint)(4));
			// Container child vboxRight.Gtk.Box+BoxChild
			this.vboxCurrentSong = new global::Gtk.VBox ();
			this.vboxCurrentSong.Name = "vboxCurrentSong";
			this.vboxCurrentSong.Spacing = 6;
			// Container child vboxCurrentSong.Gtk.Box+BoxChild
			this.lblCurrentSong = new global::Gtk.Label ();
			this.lblCurrentSong.Name = "lblCurrentSong";
			this.lblCurrentSong.Xalign = 0F;
			this.lblCurrentSong.LabelProp = global::Mono.Unix.Catalog.GetString ("Current Song");
			this.vboxCurrentSong.Add (this.lblCurrentSong);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxCurrentSong [this.lblCurrentSong]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vboxCurrentSong.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.imageAlbumCover = new global::Gtk.Image ();
			this.imageAlbumCover.Name = "imageAlbumCover";
			this.imageAlbumCover.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
			this.hbox4.Add (this.imageAlbumCover);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.imageAlbumCover]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblArtistName = new global::Gtk.Label ();
			this.lblArtistName.Name = "lblArtistName";
			this.lblArtistName.Xalign = 0F;
			this.lblArtistName.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist Name");
			this.vbox4.Add (this.lblArtistName);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblArtistName]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblAlbumTitle = new global::Gtk.Label ();
			this.lblAlbumTitle.Name = "lblAlbumTitle";
			this.lblAlbumTitle.Xalign = 0F;
			this.lblAlbumTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Album Title");
			this.vbox4.Add (this.lblAlbumTitle);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblAlbumTitle]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblSongTitle = new global::Gtk.Label ();
			this.lblSongTitle.Name = "lblSongTitle";
			this.lblSongTitle.Xalign = 0F;
			this.lblSongTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Title");
			this.vbox4.Add (this.lblSongTitle);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblSongTitle]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblSongFilePath = new global::Gtk.Label ();
			this.lblSongFilePath.Name = "lblSongFilePath";
			this.lblSongFilePath.Xalign = 0F;
			this.lblSongFilePath.LabelProp = global::Mono.Unix.Catalog.GetString ("Song File Path");
			this.vbox4.Add (this.lblSongFilePath);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblSongFilePath]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			this.hbox5.Add (this.vbox4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox4]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.lblInformation = new global::Gtk.Label ();
			this.lblInformation.Name = "lblInformation";
			this.lblInformation.Xalign = 0F;
			this.lblInformation.LabelProp = global::Mono.Unix.Catalog.GetString ("Information");
			this.vbox10.Add (this.lblInformation);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.lblInformation]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.lblCurrentFileType = new global::Gtk.Label ();
			this.lblCurrentFileType.Name = "lblCurrentFileType";
			this.lblCurrentFileType.Xalign = 0F;
			this.lblCurrentFileType.LabelProp = global::Mono.Unix.Catalog.GetString ("FLAC");
			this.vbox10.Add (this.lblCurrentFileType);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.lblCurrentFileType]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.lblCurrentBitrate = new global::Gtk.Label ();
			this.lblCurrentBitrate.Name = "lblCurrentBitrate";
			this.lblCurrentBitrate.Xalign = 0F;
			this.lblCurrentBitrate.LabelProp = global::Mono.Unix.Catalog.GetString ("320kbps");
			this.vbox10.Add (this.lblCurrentBitrate);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.lblCurrentBitrate]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.lblCurrentSampleRate = new global::Gtk.Label ();
			this.lblCurrentSampleRate.Name = "lblCurrentSampleRate";
			this.lblCurrentSampleRate.Xalign = 0F;
			this.lblCurrentSampleRate.LabelProp = global::Mono.Unix.Catalog.GetString ("44100Hz");
			this.vbox10.Add (this.lblCurrentSampleRate);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.lblCurrentSampleRate]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			this.hbox5.Add (this.vbox10);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox10]));
			w21.PackType = ((global::Gtk.PackType)(1));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w22.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblPosition = new global::Gtk.Label ();
			this.lblPosition.Name = "lblPosition";
			this.lblPosition.Xalign = 0F;
			this.lblPosition.LabelProp = global::Mono.Unix.Catalog.GetString ("Position");
			this.vbox5.Add (this.lblPosition);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblPosition]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblCurrentPosition = new global::Gtk.Label ();
			this.lblCurrentPosition.Name = "lblCurrentPosition";
			this.lblCurrentPosition.Xalign = 0F;
			this.lblCurrentPosition.LabelProp = global::Mono.Unix.Catalog.GetString ("[Position]");
			this.vbox5.Add (this.lblCurrentPosition);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblCurrentPosition]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox6.Add (this.vbox5);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox5]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.lblLength = new global::Gtk.Label ();
			this.lblLength.Name = "lblLength";
			this.lblLength.Xalign = 0F;
			this.lblLength.LabelProp = global::Mono.Unix.Catalog.GetString ("Length");
			this.vbox6.Add (this.lblLength);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.lblLength]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.lblCurrentLength = new global::Gtk.Label ();
			this.lblCurrentLength.Name = "lblCurrentLength";
			this.lblCurrentLength.Xalign = 0F;
			this.lblCurrentLength.LabelProp = global::Mono.Unix.Catalog.GetString ("[Length]");
			this.vbox6.Add (this.lblCurrentLength);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.lblCurrentLength]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.hbox6.Add (this.vbox6);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox6]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblSongPosition = new global::Gtk.Label ();
			this.lblSongPosition.Name = "lblSongPosition";
			this.lblSongPosition.Xalign = 0F;
			this.lblSongPosition.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Position");
			this.vbox7.Add (this.lblSongPosition);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.lblSongPosition]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hscaleSongPosition = new global::Gtk.HScale (null);
			this.hscaleSongPosition.CanFocus = true;
			this.hscaleSongPosition.Name = "hscaleSongPosition";
			this.hscaleSongPosition.Adjustment.Upper = 100;
			this.hscaleSongPosition.Adjustment.PageIncrement = 10;
			this.hscaleSongPosition.Adjustment.StepIncrement = 1;
			this.hscaleSongPosition.Adjustment.Value = 42;
			this.hscaleSongPosition.DrawValue = false;
			this.hscaleSongPosition.Digits = 0;
			this.hscaleSongPosition.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox7.Add (this.hscaleSongPosition);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hscaleSongPosition]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.hbox6.Add (this.vbox7);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox7]));
			w31.Position = 2;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.lblTimeShifting = new global::Gtk.Label ();
			this.lblTimeShifting.Name = "lblTimeShifting";
			this.lblTimeShifting.Xalign = 0F;
			this.lblTimeShifting.LabelProp = global::Mono.Unix.Catalog.GetString ("Time Shifting");
			this.vbox8.Add (this.lblTimeShifting);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.lblTimeShifting]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hscaleTimeShifting = new global::Gtk.HScale (null);
			this.hscaleTimeShifting.CanFocus = true;
			this.hscaleTimeShifting.Name = "hscaleTimeShifting";
			this.hscaleTimeShifting.Adjustment.Lower = 50;
			this.hscaleTimeShifting.Adjustment.Upper = 150;
			this.hscaleTimeShifting.Adjustment.PageIncrement = 10;
			this.hscaleTimeShifting.Adjustment.StepIncrement = 1;
			this.hscaleTimeShifting.Adjustment.Value = 100;
			this.hscaleTimeShifting.DrawValue = true;
			this.hscaleTimeShifting.Digits = 0;
			this.hscaleTimeShifting.ValuePos = ((global::Gtk.PositionType)(0));
			this.vbox8.Add (this.hscaleTimeShifting);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hscaleTimeShifting]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox6.Add (this.vbox8);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox8]));
			w34.Position = 3;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.hbox4.Add (this.vbox3);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox3]));
			w36.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.lblVolume = new global::Gtk.Label ();
			this.lblVolume.Name = "lblVolume";
			this.lblVolume.Xalign = 0F;
			this.lblVolume.LabelProp = global::Mono.Unix.Catalog.GetString ("Volume");
			this.vbox9.Add (this.lblVolume);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.lblVolume]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vscaleVolume = new global::Gtk.VScale (null);
			this.vscaleVolume.TooltipMarkup = "Changes the playback volume (in percentage).";
			this.vscaleVolume.CanFocus = true;
			this.vscaleVolume.Name = "vscaleVolume";
			this.vscaleVolume.Inverted = true;
			this.vscaleVolume.Adjustment.Upper = 100;
			this.vscaleVolume.Adjustment.PageIncrement = 10;
			this.vscaleVolume.Adjustment.StepIncrement = 1;
			this.vscaleVolume.Adjustment.Value = 100;
			this.vscaleVolume.DrawValue = true;
			this.vscaleVolume.Digits = 0;
			this.vscaleVolume.ValuePos = ((global::Gtk.PositionType)(3));
			this.vbox9.Add (this.vscaleVolume);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vscaleVolume]));
			w38.Position = 1;
			this.hbox4.Add (this.vbox9);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox9]));
			w39.PackType = ((global::Gtk.PackType)(1));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.vboxCurrentSong.Add (this.hbox4);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vboxCurrentSong [this.hbox4]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			this.vboxRight.Add (this.vboxCurrentSong);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vboxRight [this.vboxCurrentSong]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vboxRight.Gtk.Box+BoxChild
			this.vpanedLoopsMarkersSongBrowser = new global::Gtk.VPaned ();
			this.vpanedLoopsMarkersSongBrowser.CanFocus = true;
			this.vpanedLoopsMarkersSongBrowser.Name = "vpanedLoopsMarkersSongBrowser";
			this.vpanedLoopsMarkersSongBrowser.Position = 150;
			// Container child vpanedLoopsMarkersSongBrowser.Gtk.Paned+PanedChild
			this.hpanedLoopsMarkers = new global::Gtk.HPaned ();
			this.hpanedLoopsMarkers.CanFocus = true;
			this.hpanedLoopsMarkers.Name = "hpanedLoopsMarkers";
			this.hpanedLoopsMarkers.Position = 350;
			// Container child hpanedLoopsMarkers.Gtk.Paned+PanedChild
			this.vboxLoops = new global::Gtk.VBox ();
			this.vboxLoops.Name = "vboxLoops";
			this.vboxLoops.Spacing = 6;
			// Container child vboxLoops.Gtk.Box+BoxChild
			this.lblLoops = new global::Gtk.Label ();
			this.lblLoops.Name = "lblLoops";
			this.lblLoops.Xalign = 0F;
			this.lblLoops.LabelProp = global::Mono.Unix.Catalog.GetString ("Loops");
			this.vboxLoops.Add (this.lblLoops);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vboxLoops [this.lblLoops]));
			w42.Position = 0;
			w42.Expand = false;
			w42.Fill = false;
			// Container child vboxLoops.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbarLoops'><toolitem name='actionPlayLoop' action='actionPlayLoop'/><toolitem name='actionStopLoop' action='actionStopLoop'/><toolitem name='actionEditLoop' action='actionEditLoop'/><toolitem name='actionRemoveLoop' action='actionRemoveLoop'/></toolbar></ui>");
			this.toolbarLoops = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbarLoops")));
			this.toolbarLoops.Name = "toolbarLoops";
			this.toolbarLoops.ShowArrow = false;
			this.toolbarLoops.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.toolbarLoops.IconSize = ((global::Gtk.IconSize)(1));
			this.vboxLoops.Add (this.toolbarLoops);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vboxLoops [this.toolbarLoops]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vboxLoops.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeLoops = new global::Gtk.TreeView ();
			this.treeLoops.CanFocus = true;
			this.treeLoops.Name = "treeLoops";
			this.GtkScrolledWindow2.Add (this.treeLoops);
			this.vboxLoops.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vboxLoops [this.GtkScrolledWindow2]));
			w45.Position = 2;
			this.hpanedLoopsMarkers.Add (this.vboxLoops);
			global::Gtk.Paned.PanedChild w46 = ((global::Gtk.Paned.PanedChild)(this.hpanedLoopsMarkers [this.vboxLoops]));
			w46.Resize = false;
			// Container child hpanedLoopsMarkers.Gtk.Paned+PanedChild
			this.vboxLoops1 = new global::Gtk.VBox ();
			this.vboxLoops1.Name = "vboxLoops1";
			this.vboxLoops1.Spacing = 6;
			// Container child vboxLoops1.Gtk.Box+BoxChild
			this.lblMarkers = new global::Gtk.Label ();
			this.lblMarkers.Name = "lblMarkers";
			this.lblMarkers.Xalign = 0F;
			this.lblMarkers.LabelProp = global::Mono.Unix.Catalog.GetString ("Markers");
			this.vboxLoops1.Add (this.lblMarkers);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vboxLoops1 [this.lblMarkers]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vboxLoops1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbarMarkers'><toolitem name='actionGoToMarker' action='actionGoToMarker'/><toolitem name='actionAddMarker' action='actionAddMarker'/><toolitem name='actionRemoveMarker' action='actionRemoveMarker'/><toolitem name='actionEditMarker' action='actionEditMarker'/></toolbar></ui>");
			this.toolbarMarkers = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbarMarkers")));
			this.toolbarMarkers.Name = "toolbarMarkers";
			this.toolbarMarkers.ShowArrow = false;
			this.toolbarMarkers.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.toolbarMarkers.IconSize = ((global::Gtk.IconSize)(1));
			this.vboxLoops1.Add (this.toolbarMarkers);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vboxLoops1 [this.toolbarMarkers]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			// Container child vboxLoops1.Gtk.Box+BoxChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.treeMarkers = new global::Gtk.TreeView ();
			this.treeMarkers.CanFocus = true;
			this.treeMarkers.Name = "treeMarkers";
			this.GtkScrolledWindow3.Add (this.treeMarkers);
			this.vboxLoops1.Add (this.GtkScrolledWindow3);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vboxLoops1 [this.GtkScrolledWindow3]));
			w50.Position = 2;
			this.hpanedLoopsMarkers.Add (this.vboxLoops1);
			this.vpanedLoopsMarkersSongBrowser.Add (this.hpanedLoopsMarkers);
			global::Gtk.Paned.PanedChild w52 = ((global::Gtk.Paned.PanedChild)(this.vpanedLoopsMarkersSongBrowser [this.hpanedLoopsMarkers]));
			w52.Resize = false;
			// Container child vpanedLoopsMarkersSongBrowser.Gtk.Paned+PanedChild
			this.vboxSongBrowser = new global::Gtk.VBox ();
			this.vboxSongBrowser.Name = "vboxSongBrowser";
			this.vboxSongBrowser.Spacing = 6;
			// Container child vboxSongBrowser.Gtk.Box+BoxChild
			this.lblSongBrowser = new global::Gtk.Label ();
			this.lblSongBrowser.Name = "lblSongBrowser";
			this.lblSongBrowser.Xalign = 0F;
			this.lblSongBrowser.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Browser");
			this.vboxSongBrowser.Add (this.lblSongBrowser);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vboxSongBrowser [this.lblSongBrowser]));
			w53.Position = 0;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vboxSongBrowser.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnPlaySelectedSongs = new global::Gtk.Button ();
			this.btnPlaySelectedSongs.CanFocus = true;
			this.btnPlaySelectedSongs.Name = "btnPlaySelectedSongs";
			this.btnPlaySelectedSongs.UseUnderline = true;
			// Container child btnPlaySelectedSongs.Gtk.Container+ContainerChild
			global::Gtk.Alignment w54 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w55 = new global::Gtk.HBox ();
			w55.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w56 = new global::Gtk.Image ();
			w56.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
			w55.Add (w56);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w58 = new global::Gtk.Label ();
			w58.LabelProp = global::Mono.Unix.Catalog.GetString ("Play selected songs");
			w58.UseUnderline = true;
			w55.Add (w58);
			w54.Add (w55);
			this.btnPlaySelectedSongs.Add (w54);
			this.hbox1.Add (this.btnPlaySelectedSongs);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnPlaySelectedSongs]));
			w62.Position = 0;
			w62.Expand = false;
			w62.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnEditSongMetadata = new global::Gtk.Button ();
			this.btnEditSongMetadata.CanFocus = true;
			this.btnEditSongMetadata.Name = "btnEditSongMetadata";
			this.btnEditSongMetadata.UseUnderline = true;
			// Container child btnEditSongMetadata.Gtk.Container+ContainerChild
			global::Gtk.Alignment w63 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w64 = new global::Gtk.HBox ();
			w64.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w65 = new global::Gtk.Image ();
			w65.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w64.Add (w65);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w67 = new global::Gtk.Label ();
			w67.LabelProp = global::Mono.Unix.Catalog.GetString ("Edit song metadata");
			w67.UseUnderline = true;
			w64.Add (w67);
			w63.Add (w64);
			this.btnEditSongMetadata.Add (w63);
			this.hbox1.Add (this.btnEditSongMetadata);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnEditSongMetadata]));
			w71.Position = 1;
			w71.Expand = false;
			w71.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnAddToPlaylist = new global::Gtk.Button ();
			this.btnAddToPlaylist.CanFocus = true;
			this.btnAddToPlaylist.Name = "btnAddToPlaylist";
			this.btnAddToPlaylist.UseUnderline = true;
			// Container child btnAddToPlaylist.Gtk.Container+ContainerChild
			global::Gtk.Alignment w72 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w73 = new global::Gtk.HBox ();
			w73.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w74 = new global::Gtk.Image ();
			w74.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w73.Add (w74);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w76 = new global::Gtk.Label ();
			w76.LabelProp = global::Mono.Unix.Catalog.GetString ("Add to playlist");
			w76.UseUnderline = true;
			w73.Add (w76);
			w72.Add (w73);
			this.btnAddToPlaylist.Add (w72);
			this.hbox1.Add (this.btnAddToPlaylist);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnAddToPlaylist]));
			w80.Position = 2;
			w80.Expand = false;
			w80.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblSearchFor = new global::Gtk.Label ();
			this.lblSearchFor.Name = "lblSearchFor";
			this.lblSearchFor.Xalign = 0F;
			this.lblSearchFor.LabelProp = global::Mono.Unix.Catalog.GetString ("Search for:");
			this.hbox1.Add (this.lblSearchFor);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblSearchFor]));
			w81.Position = 3;
			w81.Expand = false;
			w81.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtSearch = new global::Gtk.Entry ();
			this.txtSearch.CanFocus = true;
			this.txtSearch.Name = "txtSearch";
			this.txtSearch.IsEditable = true;
			this.txtSearch.InvisibleChar = '•';
			this.hbox1.Add (this.txtSearch);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtSearch]));
			w82.Position = 4;
			this.vboxSongBrowser.Add (this.hbox1);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vboxSongBrowser [this.hbox1]));
			w83.Position = 1;
			w83.Expand = false;
			w83.Fill = false;
			// Container child vboxSongBrowser.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeSongBrowser = new global::Gtk.TreeView ();
			this.treeSongBrowser.CanFocus = true;
			this.treeSongBrowser.Name = "treeSongBrowser";
			this.GtkScrolledWindow.Add (this.treeSongBrowser);
			this.vboxSongBrowser.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vboxSongBrowser [this.GtkScrolledWindow]));
			w85.Position = 2;
			this.vpanedLoopsMarkersSongBrowser.Add (this.vboxSongBrowser);
			this.vboxRight.Add (this.vpanedLoopsMarkersSongBrowser);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vboxRight [this.vpanedLoopsMarkersSongBrowser]));
			w87.Position = 1;
			this.hpanedMain.Add (this.vboxRight);
			this.vboxMain.Add (this.hpanedMain);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hpanedMain]));
			w89.Position = 2;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vboxMain.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.statusbar1]));
			w90.Position = 3;
			w90.Expand = false;
			w90.Fill = false;
			this.Add (this.vboxMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultHeight = 646;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.actionExit.Activated += new global::System.EventHandler (this.OnExitActionActivated);
			this.actionAbout.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
			this.actionHelp.Activated += new global::System.EventHandler (this.OnHelpActionContentsActivated);
			this.aboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
			this.actionPlay.Activated += new global::System.EventHandler (this.OnActionPlayActivated);
			this.actionPause.Activated += new global::System.EventHandler (this.OnActionPauseActivated);
			this.actionStop.Activated += new global::System.EventHandler (this.OnActionStopActivated);
			this.actionPrevious.Activated += new global::System.EventHandler (this.OnActionPreviousActivated);
			this.actionNext.Activated += new global::System.EventHandler (this.OnActionNextActivated);
			this.actionRepeatType.Activated += new global::System.EventHandler (this.OnActionRepeatTypeActivated);
			this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
			this.actionUpdateLibrary.Activated += new global::System.EventHandler (this.OnActionUpdateLibraryActivated);
			this.actionSettings.Activated += new global::System.EventHandler (this.OnActionSettingsActivated);
			this.actionEffects.Activated += new global::System.EventHandler (this.OnActionEffectsActivated);
			this.actionPlaylist.Activated += new global::System.EventHandler (this.OnActionPlaylistActivated);
			this.actionAddFiles.Activated += new global::System.EventHandler (this.OnActionAddFilesActivated);
			this.actionAddFolder.Activated += new global::System.EventHandler (this.OnActionAddFolderActivated);
			this.cboSoundFormat.Changed += new global::System.EventHandler (this.OnSoundFormatChanged);
			this.treeLibraryBrowser.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeLibraryBrowserRowActivated);
			this.treeLibraryBrowser.CursorChanged += new global::System.EventHandler (this.OnTreeLibraryBrowserCursorChanged);
			this.hscaleSongPosition.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnSongPositionButtonPressEvent);
			this.hscaleSongPosition.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnSongPositionButtonReleaseEvent);
			this.hscaleSongPosition.MoveSlider += new global::Gtk.MoveSliderHandler (this.OnSongPositionMoveSlider);
			this.hscaleSongPosition.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnSongPositionChangeValue);
			this.hscaleTimeShifting.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnSongPositionButtonPressEvent);
			this.hscaleTimeShifting.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnSongPositionButtonReleaseEvent);
			this.hscaleTimeShifting.MoveSlider += new global::Gtk.MoveSliderHandler (this.OnSongPositionMoveSlider);
			this.hscaleTimeShifting.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnSongPositionChangeValue);
			this.vscaleVolume.ValueChanged += new global::System.EventHandler (this.OnVolumeValueChanged);
		}
	}
}
