
// This file has been generated by the GUI designer. Do not modify.
namespace MPfm.GTK
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action actionExit;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action actionAbout;
		private global::Gtk.Action helpAction;
		private global::Gtk.Action actionAbout1;
		private global::Gtk.Action PlaybackAction;
		private global::Gtk.Action actionPlay;
		private global::Gtk.Action actionPause;
		private global::Gtk.Action actionStop;
		private global::Gtk.Action actionPrevious;
		private global::Gtk.Action actionNext;
		private global::Gtk.Action RepeatTypeOffAction;
		private global::Gtk.Action actionOpen;
		private global::Gtk.Action applyAction;
		private global::Gtk.Action disconnectAction;
		private global::Gtk.Action actionUpdateLibrary;
		private global::Gtk.Action preferencesAction;
		private global::Gtk.Action PlayAction;
		private global::Gtk.Action executeAction;
		private global::Gtk.RadioAction unindentAction;
		private global::Gtk.ToggleAction zoomInAction;
		private global::Gtk.Action EffectsAction;
		private global::Gtk.Action WindowsAction;
		private global::Gtk.Action dndMultipleAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubarMain;
		private global::Gtk.Toolbar toolbarMain;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox4;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Expander expander5;
		private global::Gtk.VBox vbox13;
		private global::Gtk.Label lblLibrary1;
		private global::Gtk.ComboBox combobox1;
		private global::Gtk.Label GtkLabel22;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Expander expander6;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Image image19;
		private global::Gtk.VBox vbox14;
		private global::Gtk.HBox hbox12;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label lblArtistName;
		private global::Gtk.Label lblAlbumTitle;
		private global::Gtk.Label lblSongTitle;
		private global::Gtk.Label lblSongFilePath;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Expander expander10;
		private global::Gtk.Label lblCurrentPosition;
		private global::Gtk.Label GtkLabel26;
		private global::Gtk.Expander expander9;
		private global::Gtk.Label lblLength;
		private global::Gtk.Label GtkLabel19;
		private global::Gtk.Expander expander3;
		private global::Gtk.HScale hscaleSongPosition;
		private global::Gtk.Label GtkLabel20;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Expander expander7;
		private global::Gtk.VScale vscaleVolume;
		private global::Gtk.Label GtkLabel24;
		private global::Gtk.Label GtkLabel23;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button btnOpen;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.Button btnUpdateLibrary;
		private global::Gtk.VSeparator vseparator2;
		private global::Gtk.Label lblRepeatType;
		private global::Gtk.VSeparator vseparator3;
		private global::Gtk.Button btnPlaylist;
		private global::Gtk.Button btnEffects;
		private global::Gtk.Button btnSettings;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeSongBrowser;
		private global::Gtk.Statusbar statusbar1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MPfm.GTK.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.actionExit = new global::Gtk.Action ("actionExit", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-quit");
			this.actionExit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.actionExit, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.actionAbout = new global::Gtk.Action ("actionAbout", global::Mono.Unix.Catalog.GetString ("About MPfm"), null, null);
			this.actionAbout.ShortLabel = global::Mono.Unix.Catalog.GetString ("About MPfm");
			w1.Add (this.actionAbout, null);
			this.helpAction = new global::Gtk.Action ("helpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, "gtk-help");
			this.helpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.helpAction, null);
			this.actionAbout1 = new global::Gtk.Action ("actionAbout1", global::Mono.Unix.Catalog.GetString ("About MPfm"), null, null);
			this.actionAbout1.ShortLabel = global::Mono.Unix.Catalog.GetString ("About MPfm");
			w1.Add (this.actionAbout1, null);
			this.PlaybackAction = new global::Gtk.Action ("PlaybackAction", global::Mono.Unix.Catalog.GetString ("Playback"), null, null);
			this.PlaybackAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Playback");
			w1.Add (this.PlaybackAction, null);
			this.actionPlay = new global::Gtk.Action ("actionPlay", global::Mono.Unix.Catalog.GetString ("Play"), null, "gtk-media-play");
			this.actionPlay.ShortLabel = global::Mono.Unix.Catalog.GetString ("Play");
			w1.Add (this.actionPlay, null);
			this.actionPause = new global::Gtk.Action ("actionPause", global::Mono.Unix.Catalog.GetString ("Pause"), null, "gtk-media-pause");
			this.actionPause.ShortLabel = global::Mono.Unix.Catalog.GetString ("Pause");
			w1.Add (this.actionPause, null);
			this.actionStop = new global::Gtk.Action ("actionStop", global::Mono.Unix.Catalog.GetString ("Stop"), null, "gtk-media-stop");
			this.actionStop.ShortLabel = global::Mono.Unix.Catalog.GetString ("Stop");
			w1.Add (this.actionStop, null);
			this.actionPrevious = new global::Gtk.Action ("actionPrevious", global::Mono.Unix.Catalog.GetString ("Previous Song"), null, "gtk-media-previous");
			this.actionPrevious.ShortLabel = global::Mono.Unix.Catalog.GetString ("Previous Song");
			w1.Add (this.actionPrevious, null);
			this.actionNext = new global::Gtk.Action ("actionNext", global::Mono.Unix.Catalog.GetString ("Next Song"), null, "gtk-media-next");
			this.actionNext.ShortLabel = global::Mono.Unix.Catalog.GetString ("Next Song");
			w1.Add (this.actionNext, null);
			this.RepeatTypeOffAction = new global::Gtk.Action ("RepeatTypeOffAction", global::Mono.Unix.Catalog.GetString ("Repeat Type (Off)"), null, "stock_repeat");
			this.RepeatTypeOffAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Repeat Type (Off)");
			w1.Add (this.RepeatTypeOffAction, null);
			this.actionOpen = new global::Gtk.Action ("actionOpen", global::Mono.Unix.Catalog.GetString ("Open Audio Files"), null, "gtk-open");
			this.actionOpen.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open Audio Files");
			w1.Add (this.actionOpen, null);
			this.applyAction = new global::Gtk.Action ("applyAction", null, null, "gtk-apply");
			w1.Add (this.applyAction, null);
			this.disconnectAction = new global::Gtk.Action ("disconnectAction", null, null, "gtk-disconnect");
			w1.Add (this.disconnectAction, null);
			this.actionUpdateLibrary = new global::Gtk.Action ("actionUpdateLibrary", global::Mono.Unix.Catalog.GetString ("Update Library"), null, "gtk-refresh");
			this.actionUpdateLibrary.ShortLabel = global::Mono.Unix.Catalog.GetString ("Update Library");
			w1.Add (this.actionUpdateLibrary, null);
			this.preferencesAction = new global::Gtk.Action ("preferencesAction", null, null, "gtk-preferences");
			w1.Add (this.preferencesAction, null);
			this.PlayAction = new global::Gtk.Action ("PlayAction", global::Mono.Unix.Catalog.GetString ("Play"), null, null);
			this.PlayAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Play");
			w1.Add (this.PlayAction, null);
			this.executeAction = new global::Gtk.Action ("executeAction", null, null, "gtk-execute");
			w1.Add (this.executeAction, null);
			this.unindentAction = new global::Gtk.RadioAction ("unindentAction", null, null, "gtk-unindent", 0);
			this.unindentAction.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			w1.Add (this.unindentAction, null);
			this.zoomInAction = new global::Gtk.ToggleAction ("zoomInAction", null, null, "gtk-zoom-in");
			w1.Add (this.zoomInAction, null);
			this.EffectsAction = new global::Gtk.Action ("EffectsAction", global::Mono.Unix.Catalog.GetString ("Effects"), null, "stock_volume");
			this.EffectsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Effects");
			w1.Add (this.EffectsAction, null);
			this.WindowsAction = new global::Gtk.Action ("WindowsAction", global::Mono.Unix.Catalog.GetString ("Windows"), null, null);
			this.WindowsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Windows");
			w1.Add (this.WindowsAction, null);
			this.dndMultipleAction = new global::Gtk.Action ("dndMultipleAction", global::Mono.Unix.Catalog.GetString ("Playlist"), null, "gtk-dnd-multiple");
			this.dndMultipleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Playlist");
			w1.Add (this.dndMultipleAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "MPfm.GTK.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MPfm: Music Player for Musicians");
			this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./icon48.png"));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 100;
			// Container child MPfm.GTK.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubarMain'><menu name='FileAction' action='FileAction'><menuitem name='actionExit' action='actionExit'/></menu><menu name='PlaybackAction' action='PlaybackAction'><menuitem name='actionPlay' action='actionPlay'/><menuitem name='actionPause' action='actionPause'/><menuitem name='actionStop' action='actionStop'/><menuitem name='actionPrevious' action='actionPrevious'/><menuitem name='actionNext' action='actionNext'/><menuitem name='RepeatTypeOffAction' action='RepeatTypeOffAction'/></menu><menu name='WindowsAction' action='WindowsAction'/><menu name='HelpAction' action='HelpAction'><menuitem name='helpAction' action='helpAction'/><menuitem name='actionAbout1' action='actionAbout1'/></menu></menubar></ui>");
			this.menubarMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubarMain")));
			this.menubarMain.Name = "menubarMain";
			this.vbox1.Add (this.menubarMain);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubarMain]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbarMain'><toolitem name='actionOpen' action='actionOpen'/><separator/><toolitem name='actionUpdateLibrary' action='actionUpdateLibrary'/><separator/><toolitem name='actionPlay' action='actionPlay'/><toolitem name='actionPause' action='actionPause'/><toolitem name='actionStop' action='actionStop'/><toolitem name='actionPrevious' action='actionPrevious'/><toolitem name='actionNext' action='actionNext'/><toolitem name='RepeatTypeOffAction' action='RepeatTypeOffAction'/><separator/><toolitem name='dndMultipleAction' action='dndMultipleAction'/><toolitem name='EffectsAction' action='EffectsAction'/><toolitem name='preferencesAction' action='preferencesAction'/></toolbar></ui>");
			this.toolbarMain = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbarMain")));
			this.toolbarMain.Name = "toolbarMain";
			this.toolbarMain.ShowArrow = false;
			this.toolbarMain.ToolbarStyle = ((global::Gtk.ToolbarStyle)(2));
			this.toolbarMain.IconSize = ((global::Gtk.IconSize)(1));
			this.vbox1.Add (this.toolbarMain);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbarMain]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 236;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.expander5 = new global::Gtk.Expander (null);
			this.expander5.CanFocus = true;
			this.expander5.Name = "expander5";
			this.expander5.Expanded = true;
			// Container child expander5.Gtk.Container+ContainerChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.lblLibrary1 = new global::Gtk.Label ();
			this.lblLibrary1.Name = "lblLibrary1";
			this.lblLibrary1.Xalign = 0F;
			this.lblLibrary1.LabelProp = global::Mono.Unix.Catalog.GetString ("Filter by Sound Format:");
			this.vbox13.Add (this.lblLibrary1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.lblLibrary1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("All"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("FLAC"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("MP3"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("MPC"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("OGG"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("WAV"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("WV"));
			this.combobox1.Name = "combobox1";
			this.combobox1.Active = 0;
			this.vbox13.Add (this.combobox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.combobox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.expander5.Add (this.vbox13);
			this.GtkLabel22 = new global::Gtk.Label ();
			this.GtkLabel22.Name = "GtkLabel22";
			this.GtkLabel22.LabelProp = global::Mono.Unix.Catalog.GetString ("Library");
			this.GtkLabel22.UseUnderline = true;
			this.expander5.LabelWidget = this.GtkLabel22;
			this.vbox5.Add (this.expander5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.expander5]));
			w7.Position = 0;
			this.hpaned1.Add (this.vbox5);
			global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox5]));
			w8.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.expander6 = new global::Gtk.Expander (null);
			this.expander6.CanFocus = true;
			this.expander6.Name = "expander6";
			this.expander6.Expanded = true;
			// Container child expander6.Gtk.Container+ContainerChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.image19 = new global::Gtk.Image ();
			this.image19.Name = "image19";
			this.hbox10.Add (this.image19);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.image19]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblArtistName = new global::Gtk.Label ();
			this.lblArtistName.Name = "lblArtistName";
			this.lblArtistName.Xalign = 0F;
			this.lblArtistName.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist Name");
			this.vbox4.Add (this.lblArtistName);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblArtistName]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblAlbumTitle = new global::Gtk.Label ();
			this.lblAlbumTitle.Name = "lblAlbumTitle";
			this.lblAlbumTitle.Xalign = 0F;
			this.lblAlbumTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Album Title");
			this.vbox4.Add (this.lblAlbumTitle);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblAlbumTitle]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblSongTitle = new global::Gtk.Label ();
			this.lblSongTitle.Name = "lblSongTitle";
			this.lblSongTitle.Xalign = 0F;
			this.lblSongTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Title");
			this.vbox4.Add (this.lblSongTitle);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblSongTitle]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblSongFilePath = new global::Gtk.Label ();
			this.lblSongFilePath.Name = "lblSongFilePath";
			this.lblSongFilePath.Xalign = 0F;
			this.lblSongFilePath.LabelProp = global::Mono.Unix.Catalog.GetString ("Song File Path");
			this.vbox4.Add (this.lblSongFilePath);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblSongFilePath]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox12.Add (this.vbox4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.vbox4]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.expander10 = new global::Gtk.Expander (null);
			this.expander10.CanFocus = true;
			this.expander10.Name = "expander10";
			this.expander10.Expanded = true;
			// Container child expander10.Gtk.Container+ContainerChild
			this.lblCurrentPosition = new global::Gtk.Label ();
			this.lblCurrentPosition.Name = "lblCurrentPosition";
			this.lblCurrentPosition.Xalign = 0F;
			this.lblCurrentPosition.LabelProp = global::Mono.Unix.Catalog.GetString ("[Position]");
			this.expander10.Add (this.lblCurrentPosition);
			this.GtkLabel26 = new global::Gtk.Label ();
			this.GtkLabel26.Name = "GtkLabel26";
			this.GtkLabel26.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Position");
			this.GtkLabel26.UseUnderline = true;
			this.expander10.LabelWidget = this.GtkLabel26;
			this.vbox6.Add (this.expander10);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.expander10]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.expander9 = new global::Gtk.Expander (null);
			this.expander9.CanFocus = true;
			this.expander9.Name = "expander9";
			this.expander9.Expanded = true;
			// Container child expander9.Gtk.Container+ContainerChild
			this.lblLength = new global::Gtk.Label ();
			this.lblLength.Name = "lblLength";
			this.lblLength.Xalign = 0F;
			this.lblLength.LabelProp = global::Mono.Unix.Catalog.GetString ("[Length]");
			this.expander9.Add (this.lblLength);
			this.GtkLabel19 = new global::Gtk.Label ();
			this.GtkLabel19.Name = "GtkLabel19";
			this.GtkLabel19.LabelProp = global::Mono.Unix.Catalog.GetString ("Length");
			this.GtkLabel19.UseUnderline = true;
			this.expander9.LabelWidget = this.GtkLabel19;
			this.vbox6.Add (this.expander9);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.expander9]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox12.Add (this.vbox6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.vbox6]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox14.Add (this.hbox12);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox12]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.expander3 = new global::Gtk.Expander (null);
			this.expander3.CanFocus = true;
			this.expander3.Name = "expander3";
			this.expander3.Expanded = true;
			// Container child expander3.Gtk.Container+ContainerChild
			this.hscaleSongPosition = new global::Gtk.HScale (null);
			this.hscaleSongPosition.CanFocus = true;
			this.hscaleSongPosition.Name = "hscaleSongPosition";
			this.hscaleSongPosition.Adjustment.Upper = 100;
			this.hscaleSongPosition.Adjustment.PageIncrement = 10;
			this.hscaleSongPosition.Adjustment.StepIncrement = 1;
			this.hscaleSongPosition.Adjustment.Value = 40;
			this.hscaleSongPosition.DrawValue = false;
			this.hscaleSongPosition.Digits = 0;
			this.hscaleSongPosition.ValuePos = ((global::Gtk.PositionType)(2));
			this.expander3.Add (this.hscaleSongPosition);
			this.GtkLabel20 = new global::Gtk.Label ();
			this.GtkLabel20.Name = "GtkLabel20";
			this.GtkLabel20.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Position");
			this.GtkLabel20.UseUnderline = true;
			this.expander3.LabelWidget = this.GtkLabel20;
			this.vbox14.Add (this.expander3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.expander3]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox10.Add (this.vbox14);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbox14]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.expander7 = new global::Gtk.Expander (null);
			this.expander7.CanFocus = true;
			this.expander7.Name = "expander7";
			this.expander7.Expanded = true;
			// Container child expander7.Gtk.Container+ContainerChild
			this.vscaleVolume = new global::Gtk.VScale (null);
			this.vscaleVolume.TooltipMarkup = "Changes the playback volume (in percentage).";
			this.vscaleVolume.CanFocus = true;
			this.vscaleVolume.Name = "vscaleVolume";
			this.vscaleVolume.Inverted = true;
			this.vscaleVolume.Adjustment.Upper = 100;
			this.vscaleVolume.Adjustment.PageIncrement = 10;
			this.vscaleVolume.Adjustment.StepIncrement = 1;
			this.vscaleVolume.Adjustment.Value = 100;
			this.vscaleVolume.DrawValue = true;
			this.vscaleVolume.Digits = 0;
			this.vscaleVolume.ValuePos = ((global::Gtk.PositionType)(3));
			this.expander7.Add (this.vscaleVolume);
			this.GtkLabel24 = new global::Gtk.Label ();
			this.GtkLabel24.Name = "GtkLabel24";
			this.GtkLabel24.LabelProp = global::Mono.Unix.Catalog.GetString ("Volume");
			this.GtkLabel24.UseUnderline = true;
			this.expander7.LabelWidget = this.GtkLabel24;
			this.hbox11.Add (this.expander7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.expander7]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox10.Add (this.hbox11);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.hbox11]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			this.expander6.Add (this.hbox10);
			this.GtkLabel23 = new global::Gtk.Label ();
			this.GtkLabel23.Name = "GtkLabel23";
			this.GtkLabel23.LabelProp = global::Mono.Unix.Catalog.GetString ("Current Song");
			this.GtkLabel23.UseUnderline = true;
			this.expander6.LabelWidget = this.GtkLabel23;
			this.vbox2.Add (this.expander6);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.expander6]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnOpen = new global::Gtk.Button ();
			this.btnOpen.TooltipMarkup = "Opens audio file(s) from your hard disk.";
			this.btnOpen.CanFocus = true;
			this.btnOpen.Name = "btnOpen";
			this.btnOpen.UseUnderline = true;
			// Container child btnOpen.Gtk.Container+ContainerChild
			global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w30 = new global::Gtk.HBox ();
			w30.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			w30.Add (w31);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w33 = new global::Gtk.Label ();
			w33.LabelProp = global::Mono.Unix.Catalog.GetString ("Open Audio Files");
			w33.UseUnderline = true;
			w30.Add (w33);
			w29.Add (w30);
			this.btnOpen.Add (w29);
			this.hbox1.Add (this.btnOpen);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnOpen]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator1]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnUpdateLibrary = new global::Gtk.Button ();
			this.btnUpdateLibrary.TooltipMarkup = "Updates the audio file library.";
			this.btnUpdateLibrary.CanFocus = true;
			this.btnUpdateLibrary.Name = "btnUpdateLibrary";
			this.btnUpdateLibrary.UseUnderline = true;
			// Container child btnUpdateLibrary.Gtk.Container+ContainerChild
			global::Gtk.Alignment w39 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w40 = new global::Gtk.HBox ();
			w40.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w41 = new global::Gtk.Image ();
			w41.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			w40.Add (w41);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w43 = new global::Gtk.Label ();
			w43.LabelProp = global::Mono.Unix.Catalog.GetString ("Update Library");
			w43.UseUnderline = true;
			w40.Add (w43);
			w39.Add (w40);
			this.btnUpdateLibrary.Add (w39);
			this.hbox1.Add (this.btnUpdateLibrary);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnUpdateLibrary]));
			w47.Position = 2;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.hbox1.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator2]));
			w48.Position = 3;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblRepeatType = new global::Gtk.Label ();
			this.lblRepeatType.TooltipMarkup = "Indicates the current player repeat type";
			this.lblRepeatType.Name = "lblRepeatType";
			this.lblRepeatType.LabelProp = global::Mono.Unix.Catalog.GetString ("[RepeatType]");
			this.hbox1.Add (this.lblRepeatType);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblRepeatType]));
			w49.Position = 10;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator ();
			this.vseparator3.Name = "vseparator3";
			this.hbox1.Add (this.vseparator3);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator3]));
			w50.Position = 11;
			w50.Expand = false;
			w50.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnPlaylist = new global::Gtk.Button ();
			this.btnPlaylist.TooltipMarkup = "Opens the Playlist window.";
			this.btnPlaylist.CanFocus = true;
			this.btnPlaylist.Name = "btnPlaylist";
			this.btnPlaylist.UseUnderline = true;
			this.btnPlaylist.Label = global::Mono.Unix.Catalog.GetString ("Playlist");
			this.hbox1.Add (this.btnPlaylist);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnPlaylist]));
			w51.Position = 12;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnEffects = new global::Gtk.Button ();
			this.btnEffects.TooltipMarkup = "Opens the Effects window.";
			this.btnEffects.CanFocus = true;
			this.btnEffects.Name = "btnEffects";
			this.btnEffects.UseUnderline = true;
			this.btnEffects.Label = global::Mono.Unix.Catalog.GetString ("Effects");
			this.hbox1.Add (this.btnEffects);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnEffects]));
			w52.Position = 13;
			w52.Expand = false;
			w52.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSettings = new global::Gtk.Button ();
			this.btnSettings.TooltipMarkup = "Opens the Settings window.";
			this.btnSettings.CanFocus = true;
			this.btnSettings.Name = "btnSettings";
			this.btnSettings.UseUnderline = true;
			this.btnSettings.Label = global::Mono.Unix.Catalog.GetString ("Settings");
			this.hbox1.Add (this.btnSettings);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnSettings]));
			w53.Position = 14;
			w53.Expand = false;
			w53.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w54.Position = 1;
			w54.Expand = false;
			w54.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeSongBrowser = new global::Gtk.TreeView ();
			this.treeSongBrowser.CanFocus = true;
			this.treeSongBrowser.Name = "treeSongBrowser";
			this.GtkScrolledWindow.Add (this.treeSongBrowser);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w56.Position = 2;
			this.hpaned1.Add (this.vbox2);
			this.hbox4.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hpaned1]));
			w58.Position = 0;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w59.Position = 0;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
			w60.Position = 0;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w61.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
			w62.Position = 3;
			w62.Expand = false;
			w62.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultHeight = 748;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.actionExit.Activated += new global::System.EventHandler (this.OnExitActionActivated);
			this.actionAbout.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
			this.helpAction.Activated += new global::System.EventHandler (this.OnHelpActionContentsActivated);
			this.actionAbout1.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
			this.actionPlay.Activated += new global::System.EventHandler (this.OnActionPlayActivated);
			this.actionPause.Activated += new global::System.EventHandler (this.OnPauseClicked);
			this.actionStop.Activated += new global::System.EventHandler (this.OnStopClicked);
			this.actionPrevious.Activated += new global::System.EventHandler (this.OnPreviousClicked);
			this.actionNext.Activated += new global::System.EventHandler (this.OnNextClicked);
			this.RepeatTypeOffAction.Activated += new global::System.EventHandler (this.OnRepeatClicked);
			this.actionOpen.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
			this.hscaleSongPosition.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnSongPositionButtonPressEvent);
			this.hscaleSongPosition.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnSongPositionButtonReleaseEvent);
			this.hscaleSongPosition.MoveSlider += new global::Gtk.MoveSliderHandler (this.OnSongPositionMoveSlider);
			this.hscaleSongPosition.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnSongPositionChangeValue);
			this.vscaleVolume.ValueChanged += new global::System.EventHandler (this.OnVolumeValueChanged);
			this.btnOpen.Clicked += new global::System.EventHandler (this.OnOpenActionActivated);
			this.btnUpdateLibrary.Clicked += new global::System.EventHandler (this.OnUpdateLibraryClicked);
			this.btnPlaylist.Clicked += new global::System.EventHandler (this.OnPlaylistClicked);
			this.btnEffects.Clicked += new global::System.EventHandler (this.OnEffectsClicked);
			this.btnSettings.Clicked += new global::System.EventHandler (this.OnSettingsClicked);
		}
	}
}
