
// This file has been generated by the GUI designer. Do not modify.
namespace MPfm.GTK
{
	public partial class UpdateLibraryWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MPfm.GTK.UpdateLibraryWindow
			this.Name = "MPfm.GTK.UpdateLibraryWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("UpdateLibraryWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
