
// This file has been generated by the GUI designer. Do not modify.
namespace MPfm.GTK
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action actionExit;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action actionAbout;
		private global::Gtk.Action helpAction;
		private global::Gtk.Action aboutAction;
		private global::Gtk.Action PlaybackAction;
		private global::Gtk.Action actionPlay;
		private global::Gtk.Action actionPause;
		private global::Gtk.Action actionStop;
		private global::Gtk.Action actionPrevious;
		private global::Gtk.Action actionNext;
		private global::Gtk.Action actionRepeatType;
		private global::Gtk.Action actionOpen;
		private global::Gtk.Action applyAction;
		private global::Gtk.Action disconnectAction;
		private global::Gtk.Action actionUpdateLibrary;
		private global::Gtk.Action actionSettings;
		private global::Gtk.Action PlayAction;
		private global::Gtk.Action executeAction;
		private global::Gtk.RadioAction unindentAction;
		private global::Gtk.ToggleAction zoomInAction;
		private global::Gtk.Action actionEffects;
		private global::Gtk.Action WindowsAction;
		private global::Gtk.Action actionPlaylist;
		private global::Gtk.Action addAction;
		private global::Gtk.Action removeAction;
		private global::Gtk.Action editAction;
		private global::Gtk.Action mediaPlayAction;
		private global::Gtk.Action mediaStopAction;
		private global::Gtk.Action goForwardAction;
		private global::Gtk.Action mediaPlayAction1;
		private global::Gtk.Action editAction1;
		private global::Gtk.Action addAction1;
		private global::Gtk.VBox vboxMain;
		private global::Gtk.MenuBar menubarMain;
		private global::Gtk.Toolbar toolbarMain;
		private global::Gtk.HPaned hpanedMain;
		private global::Gtk.VBox vboxLeft;
		private global::Gtk.Label lblLibrary;
		private global::Gtk.Label lblLibraryFilter;
		private global::Gtk.ComboBox cboSoundFormat;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView treeSongBrowser1;
		private global::Gtk.VBox vboxRight;
		private global::Gtk.VBox vboxCurrentSong;
		private global::Gtk.Label lblCurrentSong;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Image image286;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox5;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label lblArtistName;
		private global::Gtk.Label lblAlbumTitle;
		private global::Gtk.Label lblSongTitle;
		private global::Gtk.Label lblSongFilePath;
		private global::Gtk.HBox hbox6;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label lblPosition;
		private global::Gtk.Label lblCurrentPosition;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label lblLength;
		private global::Gtk.Label lblCurrentLength;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label lblSongPosition;
		private global::Gtk.HScale hscaleSongPosition;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Label lblTimeShifting;
		private global::Gtk.HScale hscaleTimeShifting;
		private global::Gtk.VBox vbox9;
		private global::Gtk.Label lblVolume;
		private global::Gtk.VScale vscaleVolume;
		private global::Gtk.VPaned vpanedLoopsMarkersSongBrowser;
		private global::Gtk.HPaned hpanedLoopsMarkers;
		private global::Gtk.VBox vboxLoops;
		private global::Gtk.Label lblLoops;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Button button1;
		private global::Gtk.Button button4;
		private global::Gtk.Button button5;
		private global::Gtk.Button button6;
		private global::Gtk.Button button9;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TreeView treeSongBrowser2;
		private global::Gtk.VBox vboxLoops1;
		private global::Gtk.Label lblMarkers;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button button3;
		private global::Gtk.Button button7;
		private global::Gtk.Button button8;
		private global::Gtk.Button button10;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.TreeView treeSongBrowser3;
		private global::Gtk.VBox vboxSongBrowser;
		private global::Gtk.Label lblSongBrowser;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button button2;
		private global::Gtk.Button button11;
		private global::Gtk.Button button12;
		private global::Gtk.Label lblSearchFor;
		private global::Gtk.Entry entry1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeSongBrowser;
		private global::Gtk.Statusbar statusbar1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MPfm.GTK.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.actionExit = new global::Gtk.Action ("actionExit", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-quit");
			this.actionExit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.actionExit, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.actionAbout = new global::Gtk.Action ("actionAbout", global::Mono.Unix.Catalog.GetString ("About MPfm"), null, null);
			this.actionAbout.ShortLabel = global::Mono.Unix.Catalog.GetString ("About MPfm");
			w1.Add (this.actionAbout, null);
			this.helpAction = new global::Gtk.Action ("helpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, "gtk-help");
			this.helpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.helpAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About MPfm"), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About MPfm");
			w1.Add (this.aboutAction, null);
			this.PlaybackAction = new global::Gtk.Action ("PlaybackAction", global::Mono.Unix.Catalog.GetString ("Playback"), null, null);
			this.PlaybackAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Playback");
			w1.Add (this.PlaybackAction, null);
			this.actionPlay = new global::Gtk.Action ("actionPlay", global::Mono.Unix.Catalog.GetString ("Play"), null, "gtk-media-play");
			this.actionPlay.ShortLabel = global::Mono.Unix.Catalog.GetString ("Play");
			w1.Add (this.actionPlay, null);
			this.actionPause = new global::Gtk.Action ("actionPause", global::Mono.Unix.Catalog.GetString ("Pause"), null, "gtk-media-pause");
			this.actionPause.ShortLabel = global::Mono.Unix.Catalog.GetString ("Pause");
			w1.Add (this.actionPause, null);
			this.actionStop = new global::Gtk.Action ("actionStop", global::Mono.Unix.Catalog.GetString ("Stop"), null, "gtk-media-stop");
			this.actionStop.ShortLabel = global::Mono.Unix.Catalog.GetString ("Stop");
			w1.Add (this.actionStop, null);
			this.actionPrevious = new global::Gtk.Action ("actionPrevious", global::Mono.Unix.Catalog.GetString ("Previous Song"), null, "gtk-media-previous");
			this.actionPrevious.ShortLabel = global::Mono.Unix.Catalog.GetString ("Previous Song");
			w1.Add (this.actionPrevious, null);
			this.actionNext = new global::Gtk.Action ("actionNext", global::Mono.Unix.Catalog.GetString ("Next Song"), null, "gtk-media-next");
			this.actionNext.ShortLabel = global::Mono.Unix.Catalog.GetString ("Next Song");
			w1.Add (this.actionNext, null);
			this.actionRepeatType = new global::Gtk.Action ("actionRepeatType", global::Mono.Unix.Catalog.GetString ("Repeat Type (Off)"), null, "stock_repeat");
			this.actionRepeatType.ShortLabel = global::Mono.Unix.Catalog.GetString ("Repeat Type (Off)");
			w1.Add (this.actionRepeatType, null);
			this.actionOpen = new global::Gtk.Action ("actionOpen", global::Mono.Unix.Catalog.GetString ("Open Audio Files"), null, "gtk-open");
			this.actionOpen.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open Audio Files");
			w1.Add (this.actionOpen, null);
			this.applyAction = new global::Gtk.Action ("applyAction", null, null, "gtk-apply");
			w1.Add (this.applyAction, null);
			this.disconnectAction = new global::Gtk.Action ("disconnectAction", null, null, "gtk-disconnect");
			w1.Add (this.disconnectAction, null);
			this.actionUpdateLibrary = new global::Gtk.Action ("actionUpdateLibrary", global::Mono.Unix.Catalog.GetString ("Update Library"), null, "gtk-refresh");
			this.actionUpdateLibrary.ShortLabel = global::Mono.Unix.Catalog.GetString ("Update Library");
			w1.Add (this.actionUpdateLibrary, null);
			this.actionSettings = new global::Gtk.Action ("actionSettings", global::Mono.Unix.Catalog.GetString ("Settings"), null, "gtk-preferences");
			this.actionSettings.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
			w1.Add (this.actionSettings, null);
			this.PlayAction = new global::Gtk.Action ("PlayAction", global::Mono.Unix.Catalog.GetString ("Play"), null, null);
			this.PlayAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Play");
			w1.Add (this.PlayAction, null);
			this.executeAction = new global::Gtk.Action ("executeAction", null, null, "gtk-execute");
			w1.Add (this.executeAction, null);
			this.unindentAction = new global::Gtk.RadioAction ("unindentAction", null, null, "gtk-unindent", 0);
			this.unindentAction.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			w1.Add (this.unindentAction, null);
			this.zoomInAction = new global::Gtk.ToggleAction ("zoomInAction", null, null, "gtk-zoom-in");
			w1.Add (this.zoomInAction, null);
			this.actionEffects = new global::Gtk.Action ("actionEffects", global::Mono.Unix.Catalog.GetString ("Effects"), null, "stock_volume");
			this.actionEffects.ShortLabel = global::Mono.Unix.Catalog.GetString ("Effects");
			w1.Add (this.actionEffects, null);
			this.WindowsAction = new global::Gtk.Action ("WindowsAction", global::Mono.Unix.Catalog.GetString ("Windows"), null, null);
			this.WindowsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Windows");
			w1.Add (this.WindowsAction, null);
			this.actionPlaylist = new global::Gtk.Action ("actionPlaylist", global::Mono.Unix.Catalog.GetString ("Playlist"), null, "gtk-dnd-multiple");
			this.actionPlaylist.ShortLabel = global::Mono.Unix.Catalog.GetString ("Playlist");
			w1.Add (this.actionPlaylist, null);
			this.addAction = new global::Gtk.Action ("addAction", null, null, "gtk-add");
			w1.Add (this.addAction, null);
			this.removeAction = new global::Gtk.Action ("removeAction", null, null, "gtk-remove");
			w1.Add (this.removeAction, null);
			this.editAction = new global::Gtk.Action ("editAction", null, null, "gtk-edit");
			w1.Add (this.editAction, null);
			this.mediaPlayAction = new global::Gtk.Action ("mediaPlayAction", null, null, "gtk-media-play");
			w1.Add (this.mediaPlayAction, null);
			this.mediaStopAction = new global::Gtk.Action ("mediaStopAction", null, null, "gtk-media-stop");
			w1.Add (this.mediaStopAction, null);
			this.goForwardAction = new global::Gtk.Action ("goForwardAction", null, null, "gtk-go-forward");
			w1.Add (this.goForwardAction, null);
			this.mediaPlayAction1 = new global::Gtk.Action ("mediaPlayAction1", null, null, "gtk-media-play");
			w1.Add (this.mediaPlayAction1, null);
			this.editAction1 = new global::Gtk.Action ("editAction1", null, null, "gtk-edit");
			w1.Add (this.editAction1, null);
			this.addAction1 = new global::Gtk.Action ("addAction1", null, null, "gtk-add");
			w1.Add (this.addAction1, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "MPfm.GTK.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MPfm: Music Player for Musicians");
			this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./icon48.png"));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 100;
			// Container child MPfm.GTK.MainWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubarMain'><menu name='FileAction' action='FileAction'><menuitem name='actionExit' action='actionExit'/></menu><menu name='PlaybackAction' action='PlaybackAction'><menuitem name='actionPlay' action='actionPlay'/><menuitem name='actionPause' action='actionPause'/><menuitem name='actionStop' action='actionStop'/><menuitem name='actionPrevious' action='actionPrevious'/><menuitem name='actionNext' action='actionNext'/><menuitem name='actionRepeatType' action='actionRepeatType'/></menu><menu name='WindowsAction' action='WindowsAction'/><menu name='HelpAction' action='HelpAction'><menuitem name='helpAction' action='helpAction'/><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
			this.menubarMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubarMain")));
			this.menubarMain.Name = "menubarMain";
			this.vboxMain.Add (this.menubarMain);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.menubarMain]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbarMain'><toolitem name='actionOpen' action='actionOpen'/><separator/><toolitem name='actionUpdateLibrary' action='actionUpdateLibrary'/><separator/><toolitem name='actionPlay' action='actionPlay'/><toolitem name='actionPause' action='actionPause'/><toolitem name='actionStop' action='actionStop'/><toolitem name='actionPrevious' action='actionPrevious'/><toolitem name='actionNext' action='actionNext'/><toolitem name='actionRepeatType' action='actionRepeatType'/><separator/><toolitem name='actionPlaylist' action='actionPlaylist'/><toolitem name='actionEffects' action='actionEffects'/><toolitem name='actionSettings' action='actionSettings'/></toolbar></ui>");
			this.toolbarMain = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbarMain")));
			this.toolbarMain.Name = "toolbarMain";
			this.toolbarMain.ShowArrow = false;
			this.toolbarMain.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.toolbarMain.IconSize = ((global::Gtk.IconSize)(2));
			this.vboxMain.Add (this.toolbarMain);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.toolbarMain]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hpanedMain = new global::Gtk.HPaned ();
			this.hpanedMain.CanFocus = true;
			this.hpanedMain.Name = "hpanedMain";
			this.hpanedMain.Position = 236;
			// Container child hpanedMain.Gtk.Paned+PanedChild
			this.vboxLeft = new global::Gtk.VBox ();
			this.vboxLeft.Name = "vboxLeft";
			this.vboxLeft.Spacing = 6;
			this.vboxLeft.BorderWidth = ((uint)(4));
			// Container child vboxLeft.Gtk.Box+BoxChild
			this.lblLibrary = new global::Gtk.Label ();
			this.lblLibrary.Name = "lblLibrary";
			this.lblLibrary.Xalign = 0F;
			this.lblLibrary.LabelProp = global::Mono.Unix.Catalog.GetString ("Library");
			this.vboxLeft.Add (this.lblLibrary);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxLeft [this.lblLibrary]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vboxLeft.Gtk.Box+BoxChild
			this.lblLibraryFilter = new global::Gtk.Label ();
			this.lblLibraryFilter.Name = "lblLibraryFilter";
			this.lblLibraryFilter.Xalign = 0F;
			this.lblLibraryFilter.LabelProp = global::Mono.Unix.Catalog.GetString ("Filter by Sound Format:");
			this.vboxLeft.Add (this.lblLibraryFilter);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxLeft [this.lblLibraryFilter]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxLeft.Gtk.Box+BoxChild
			this.cboSoundFormat = global::Gtk.ComboBox.NewText ();
			this.cboSoundFormat.AppendText (global::Mono.Unix.Catalog.GetString ("All"));
			this.cboSoundFormat.AppendText (global::Mono.Unix.Catalog.GetString ("FLAC"));
			this.cboSoundFormat.AppendText (global::Mono.Unix.Catalog.GetString ("MP3"));
			this.cboSoundFormat.AppendText (global::Mono.Unix.Catalog.GetString ("MPC"));
			this.cboSoundFormat.AppendText (global::Mono.Unix.Catalog.GetString ("OGG"));
			this.cboSoundFormat.AppendText (global::Mono.Unix.Catalog.GetString ("WAV"));
			this.cboSoundFormat.AppendText (global::Mono.Unix.Catalog.GetString ("WV"));
			this.cboSoundFormat.Name = "cboSoundFormat";
			this.cboSoundFormat.Active = 0;
			this.vboxLeft.Add (this.cboSoundFormat);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxLeft [this.cboSoundFormat]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vboxLeft.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeSongBrowser1 = new global::Gtk.TreeView ();
			this.treeSongBrowser1.CanFocus = true;
			this.treeSongBrowser1.Name = "treeSongBrowser1";
			this.GtkScrolledWindow1.Add (this.treeSongBrowser1);
			this.vboxLeft.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxLeft [this.GtkScrolledWindow1]));
			w8.Position = 3;
			this.hpanedMain.Add (this.vboxLeft);
			global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.hpanedMain [this.vboxLeft]));
			w9.Resize = false;
			// Container child hpanedMain.Gtk.Paned+PanedChild
			this.vboxRight = new global::Gtk.VBox ();
			this.vboxRight.Name = "vboxRight";
			this.vboxRight.Spacing = 6;
			this.vboxRight.BorderWidth = ((uint)(4));
			// Container child vboxRight.Gtk.Box+BoxChild
			this.vboxCurrentSong = new global::Gtk.VBox ();
			this.vboxCurrentSong.Name = "vboxCurrentSong";
			this.vboxCurrentSong.Spacing = 6;
			// Container child vboxCurrentSong.Gtk.Box+BoxChild
			this.lblCurrentSong = new global::Gtk.Label ();
			this.lblCurrentSong.Name = "lblCurrentSong";
			this.lblCurrentSong.Xalign = 0F;
			this.lblCurrentSong.LabelProp = global::Mono.Unix.Catalog.GetString ("Current Song");
			this.vboxCurrentSong.Add (this.lblCurrentSong);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxCurrentSong [this.lblCurrentSong]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vboxCurrentSong.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.image286 = new global::Gtk.Image ();
			this.image286.Name = "image286";
			this.image286.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
			this.hbox4.Add (this.image286);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.image286]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblArtistName = new global::Gtk.Label ();
			this.lblArtistName.Name = "lblArtistName";
			this.lblArtistName.Xalign = 0F;
			this.lblArtistName.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist Name");
			this.vbox4.Add (this.lblArtistName);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblArtistName]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblAlbumTitle = new global::Gtk.Label ();
			this.lblAlbumTitle.Name = "lblAlbumTitle";
			this.lblAlbumTitle.Xalign = 0F;
			this.lblAlbumTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Album Title");
			this.vbox4.Add (this.lblAlbumTitle);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblAlbumTitle]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblSongTitle = new global::Gtk.Label ();
			this.lblSongTitle.Name = "lblSongTitle";
			this.lblSongTitle.Xalign = 0F;
			this.lblSongTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Title");
			this.vbox4.Add (this.lblSongTitle);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblSongTitle]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblSongFilePath = new global::Gtk.Label ();
			this.lblSongFilePath.Name = "lblSongFilePath";
			this.lblSongFilePath.Xalign = 0F;
			this.lblSongFilePath.LabelProp = global::Mono.Unix.Catalog.GetString ("Song File Path");
			this.vbox4.Add (this.lblSongFilePath);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblSongFilePath]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			this.hbox5.Add (this.vbox4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox4]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblPosition = new global::Gtk.Label ();
			this.lblPosition.Name = "lblPosition";
			this.lblPosition.Xalign = 0F;
			this.lblPosition.LabelProp = global::Mono.Unix.Catalog.GetString ("Position");
			this.vbox5.Add (this.lblPosition);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblPosition]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblCurrentPosition = new global::Gtk.Label ();
			this.lblCurrentPosition.Name = "lblCurrentPosition";
			this.lblCurrentPosition.Xalign = 0F;
			this.lblCurrentPosition.LabelProp = global::Mono.Unix.Catalog.GetString ("[Position]");
			this.vbox5.Add (this.lblCurrentPosition);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblCurrentPosition]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox6.Add (this.vbox5);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox5]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.lblLength = new global::Gtk.Label ();
			this.lblLength.Name = "lblLength";
			this.lblLength.Xalign = 0F;
			this.lblLength.LabelProp = global::Mono.Unix.Catalog.GetString ("Length");
			this.vbox6.Add (this.lblLength);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.lblLength]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.lblCurrentLength = new global::Gtk.Label ();
			this.lblCurrentLength.Name = "lblCurrentLength";
			this.lblCurrentLength.Xalign = 0F;
			this.lblCurrentLength.LabelProp = global::Mono.Unix.Catalog.GetString ("[Length]");
			this.vbox6.Add (this.lblCurrentLength);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.lblCurrentLength]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox6.Add (this.vbox6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox6]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblSongPosition = new global::Gtk.Label ();
			this.lblSongPosition.Name = "lblSongPosition";
			this.lblSongPosition.Xalign = 0F;
			this.lblSongPosition.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Position");
			this.vbox7.Add (this.lblSongPosition);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.lblSongPosition]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hscaleSongPosition = new global::Gtk.HScale (null);
			this.hscaleSongPosition.CanFocus = true;
			this.hscaleSongPosition.Name = "hscaleSongPosition";
			this.hscaleSongPosition.Adjustment.Upper = 100;
			this.hscaleSongPosition.Adjustment.PageIncrement = 10;
			this.hscaleSongPosition.Adjustment.StepIncrement = 1;
			this.hscaleSongPosition.Adjustment.Value = 40;
			this.hscaleSongPosition.DrawValue = false;
			this.hscaleSongPosition.Digits = 0;
			this.hscaleSongPosition.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox7.Add (this.hscaleSongPosition);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hscaleSongPosition]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox6.Add (this.vbox7);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox7]));
			w26.Position = 2;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.lblTimeShifting = new global::Gtk.Label ();
			this.lblTimeShifting.Name = "lblTimeShifting";
			this.lblTimeShifting.Xalign = 0F;
			this.lblTimeShifting.LabelProp = global::Mono.Unix.Catalog.GetString ("Time Shifting");
			this.vbox8.Add (this.lblTimeShifting);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.lblTimeShifting]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hscaleTimeShifting = new global::Gtk.HScale (null);
			this.hscaleTimeShifting.CanFocus = true;
			this.hscaleTimeShifting.Name = "hscaleTimeShifting";
			this.hscaleTimeShifting.Adjustment.Lower = 50;
			this.hscaleTimeShifting.Adjustment.Upper = 150;
			this.hscaleTimeShifting.Adjustment.PageIncrement = 10;
			this.hscaleTimeShifting.Adjustment.StepIncrement = 1;
			this.hscaleTimeShifting.Adjustment.Value = 100;
			this.hscaleTimeShifting.DrawValue = true;
			this.hscaleTimeShifting.Digits = 0;
			this.hscaleTimeShifting.ValuePos = ((global::Gtk.PositionType)(0));
			this.vbox8.Add (this.hscaleTimeShifting);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hscaleTimeShifting]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.hbox6.Add (this.vbox8);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox8]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.hbox4.Add (this.vbox3);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox3]));
			w31.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.lblVolume = new global::Gtk.Label ();
			this.lblVolume.Name = "lblVolume";
			this.lblVolume.Xalign = 0F;
			this.lblVolume.LabelProp = global::Mono.Unix.Catalog.GetString ("Volume");
			this.vbox9.Add (this.lblVolume);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.lblVolume]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vscaleVolume = new global::Gtk.VScale (null);
			this.vscaleVolume.TooltipMarkup = "Changes the playback volume (in percentage).";
			this.vscaleVolume.CanFocus = true;
			this.vscaleVolume.Name = "vscaleVolume";
			this.vscaleVolume.Inverted = true;
			this.vscaleVolume.Adjustment.Upper = 100;
			this.vscaleVolume.Adjustment.PageIncrement = 10;
			this.vscaleVolume.Adjustment.StepIncrement = 1;
			this.vscaleVolume.Adjustment.Value = 100;
			this.vscaleVolume.DrawValue = true;
			this.vscaleVolume.Digits = 0;
			this.vscaleVolume.ValuePos = ((global::Gtk.PositionType)(3));
			this.vbox9.Add (this.vscaleVolume);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vscaleVolume]));
			w33.Position = 1;
			this.hbox4.Add (this.vbox9);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox9]));
			w34.PackType = ((global::Gtk.PackType)(1));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			this.vboxCurrentSong.Add (this.hbox4);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vboxCurrentSong [this.hbox4]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.vboxRight.Add (this.vboxCurrentSong);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vboxRight [this.vboxCurrentSong]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vboxRight.Gtk.Box+BoxChild
			this.vpanedLoopsMarkersSongBrowser = new global::Gtk.VPaned ();
			this.vpanedLoopsMarkersSongBrowser.CanFocus = true;
			this.vpanedLoopsMarkersSongBrowser.Name = "vpanedLoopsMarkersSongBrowser";
			this.vpanedLoopsMarkersSongBrowser.Position = 150;
			// Container child vpanedLoopsMarkersSongBrowser.Gtk.Paned+PanedChild
			this.hpanedLoopsMarkers = new global::Gtk.HPaned ();
			this.hpanedLoopsMarkers.CanFocus = true;
			this.hpanedLoopsMarkers.Name = "hpanedLoopsMarkers";
			this.hpanedLoopsMarkers.Position = 350;
			// Container child hpanedLoopsMarkers.Gtk.Paned+PanedChild
			this.vboxLoops = new global::Gtk.VBox ();
			this.vboxLoops.Name = "vboxLoops";
			this.vboxLoops.Spacing = 6;
			// Container child vboxLoops.Gtk.Box+BoxChild
			this.lblLoops = new global::Gtk.Label ();
			this.lblLoops.Name = "lblLoops";
			this.lblLoops.Xalign = 0F;
			this.lblLoops.LabelProp = global::Mono.Unix.Catalog.GetString ("Loops");
			this.vboxLoops.Add (this.lblLoops);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vboxLoops [this.lblLoops]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vboxLoops.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			// Container child button1.Gtk.Container+ContainerChild
			global::Gtk.Alignment w38 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w39 = new global::Gtk.HBox ();
			w39.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w40 = new global::Gtk.Image ();
			w40.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
			w39.Add (w40);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w42 = new global::Gtk.Label ();
			w42.LabelProp = global::Mono.Unix.Catalog.GetString ("Play");
			w42.UseUnderline = true;
			w39.Add (w42);
			w38.Add (w39);
			this.button1.Add (w38);
			this.hbox2.Add (this.button1);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button1]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			// Container child button4.Gtk.Container+ContainerChild
			global::Gtk.Alignment w47 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w48 = new global::Gtk.HBox ();
			w48.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w49 = new global::Gtk.Image ();
			w49.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-stop", global::Gtk.IconSize.Menu);
			w48.Add (w49);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w51 = new global::Gtk.Label ();
			w51.LabelProp = global::Mono.Unix.Catalog.GetString ("Stop");
			w51.UseUnderline = true;
			w48.Add (w51);
			w47.Add (w48);
			this.button4.Add (w47);
			this.hbox2.Add (this.button4);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button4]));
			w55.Position = 1;
			w55.Expand = false;
			w55.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			// Container child button5.Gtk.Container+ContainerChild
			global::Gtk.Alignment w56 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w57 = new global::Gtk.HBox ();
			w57.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w58 = new global::Gtk.Image ();
			w58.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w57.Add (w58);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w60 = new global::Gtk.Label ();
			w60.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w60.UseUnderline = true;
			w57.Add (w60);
			w56.Add (w57);
			this.button5.Add (w56);
			this.hbox2.Add (this.button5);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button5]));
			w64.Position = 2;
			w64.Expand = false;
			w64.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			// Container child button6.Gtk.Container+ContainerChild
			global::Gtk.Alignment w65 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w66 = new global::Gtk.HBox ();
			w66.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w67 = new global::Gtk.Image ();
			w67.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w66.Add (w67);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w69 = new global::Gtk.Label ();
			w69.LabelProp = global::Mono.Unix.Catalog.GetString ("Edit");
			w69.UseUnderline = true;
			w66.Add (w69);
			w65.Add (w66);
			this.button6.Add (w65);
			this.hbox2.Add (this.button6);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button6]));
			w73.Position = 3;
			w73.Expand = false;
			w73.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button ();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			// Container child button9.Gtk.Container+ContainerChild
			global::Gtk.Alignment w74 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w75 = new global::Gtk.HBox ();
			w75.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w76 = new global::Gtk.Image ();
			w76.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w75.Add (w76);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w78 = new global::Gtk.Label ();
			w78.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove");
			w78.UseUnderline = true;
			w75.Add (w78);
			w74.Add (w75);
			this.button9.Add (w74);
			this.hbox2.Add (this.button9);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button9]));
			w82.Position = 4;
			w82.Expand = false;
			w82.Fill = false;
			this.vboxLoops.Add (this.hbox2);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vboxLoops [this.hbox2]));
			w83.Position = 1;
			w83.Expand = false;
			w83.Fill = false;
			// Container child vboxLoops.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeSongBrowser2 = new global::Gtk.TreeView ();
			this.treeSongBrowser2.CanFocus = true;
			this.treeSongBrowser2.Name = "treeSongBrowser2";
			this.GtkScrolledWindow2.Add (this.treeSongBrowser2);
			this.vboxLoops.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vboxLoops [this.GtkScrolledWindow2]));
			w85.Position = 2;
			this.hpanedLoopsMarkers.Add (this.vboxLoops);
			global::Gtk.Paned.PanedChild w86 = ((global::Gtk.Paned.PanedChild)(this.hpanedLoopsMarkers [this.vboxLoops]));
			w86.Resize = false;
			// Container child hpanedLoopsMarkers.Gtk.Paned+PanedChild
			this.vboxLoops1 = new global::Gtk.VBox ();
			this.vboxLoops1.Name = "vboxLoops1";
			this.vboxLoops1.Spacing = 6;
			// Container child vboxLoops1.Gtk.Box+BoxChild
			this.lblMarkers = new global::Gtk.Label ();
			this.lblMarkers.Name = "lblMarkers";
			this.lblMarkers.Xalign = 0F;
			this.lblMarkers.LabelProp = global::Mono.Unix.Catalog.GetString ("Markers");
			this.vboxLoops1.Add (this.lblMarkers);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vboxLoops1 [this.lblMarkers]));
			w87.Position = 0;
			w87.Expand = false;
			w87.Fill = false;
			// Container child vboxLoops1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			// Container child button3.Gtk.Container+ContainerChild
			global::Gtk.Alignment w88 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w89 = new global::Gtk.HBox ();
			w89.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w90 = new global::Gtk.Image ();
			w90.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w89.Add (w90);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w92 = new global::Gtk.Label ();
			w92.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w92.UseUnderline = true;
			w89.Add (w92);
			w88.Add (w89);
			this.button3.Add (w88);
			this.hbox3.Add (this.button3);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button3]));
			w96.Position = 0;
			w96.Expand = false;
			w96.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			// Container child button7.Gtk.Container+ContainerChild
			global::Gtk.Alignment w97 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w98 = new global::Gtk.HBox ();
			w98.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w99 = new global::Gtk.Image ();
			w99.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w98.Add (w99);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w101 = new global::Gtk.Label ();
			w101.LabelProp = global::Mono.Unix.Catalog.GetString ("Edit");
			w101.UseUnderline = true;
			w98.Add (w101);
			w97.Add (w98);
			this.button7.Add (w97);
			this.hbox3.Add (this.button7);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button7]));
			w105.Position = 1;
			w105.Expand = false;
			w105.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			// Container child button8.Gtk.Container+ContainerChild
			global::Gtk.Alignment w106 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w107 = new global::Gtk.HBox ();
			w107.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w108 = new global::Gtk.Image ();
			w108.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w107.Add (w108);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w110 = new global::Gtk.Label ();
			w110.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove");
			w110.UseUnderline = true;
			w107.Add (w110);
			w106.Add (w107);
			this.button8.Add (w106);
			this.hbox3.Add (this.button8);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button8]));
			w114.Position = 2;
			w114.Expand = false;
			w114.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button ();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			// Container child button10.Gtk.Container+ContainerChild
			global::Gtk.Alignment w115 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w116 = new global::Gtk.HBox ();
			w116.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w117 = new global::Gtk.Image ();
			w117.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			w116.Add (w117);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w119 = new global::Gtk.Label ();
			w119.LabelProp = global::Mono.Unix.Catalog.GetString ("Go to");
			w119.UseUnderline = true;
			w116.Add (w119);
			w115.Add (w116);
			this.button10.Add (w115);
			this.hbox3.Add (this.button10);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button10]));
			w123.Position = 3;
			w123.Expand = false;
			w123.Fill = false;
			this.vboxLoops1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.vboxLoops1 [this.hbox3]));
			w124.Position = 1;
			w124.Expand = false;
			w124.Fill = false;
			// Container child vboxLoops1.Gtk.Box+BoxChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.treeSongBrowser3 = new global::Gtk.TreeView ();
			this.treeSongBrowser3.CanFocus = true;
			this.treeSongBrowser3.Name = "treeSongBrowser3";
			this.GtkScrolledWindow3.Add (this.treeSongBrowser3);
			this.vboxLoops1.Add (this.GtkScrolledWindow3);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.vboxLoops1 [this.GtkScrolledWindow3]));
			w126.Position = 2;
			this.hpanedLoopsMarkers.Add (this.vboxLoops1);
			this.vpanedLoopsMarkersSongBrowser.Add (this.hpanedLoopsMarkers);
			global::Gtk.Paned.PanedChild w128 = ((global::Gtk.Paned.PanedChild)(this.vpanedLoopsMarkersSongBrowser [this.hpanedLoopsMarkers]));
			w128.Resize = false;
			// Container child vpanedLoopsMarkersSongBrowser.Gtk.Paned+PanedChild
			this.vboxSongBrowser = new global::Gtk.VBox ();
			this.vboxSongBrowser.Name = "vboxSongBrowser";
			this.vboxSongBrowser.Spacing = 6;
			// Container child vboxSongBrowser.Gtk.Box+BoxChild
			this.lblSongBrowser = new global::Gtk.Label ();
			this.lblSongBrowser.Name = "lblSongBrowser";
			this.lblSongBrowser.Xalign = 0F;
			this.lblSongBrowser.LabelProp = global::Mono.Unix.Catalog.GetString ("Song Browser");
			this.vboxSongBrowser.Add (this.lblSongBrowser);
			global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.vboxSongBrowser [this.lblSongBrowser]));
			w129.Position = 0;
			w129.Expand = false;
			w129.Fill = false;
			// Container child vboxSongBrowser.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			// Container child button2.Gtk.Container+ContainerChild
			global::Gtk.Alignment w130 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w131 = new global::Gtk.HBox ();
			w131.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w132 = new global::Gtk.Image ();
			w132.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
			w131.Add (w132);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w134 = new global::Gtk.Label ();
			w134.LabelProp = global::Mono.Unix.Catalog.GetString ("Play selected songs");
			w134.UseUnderline = true;
			w131.Add (w134);
			w130.Add (w131);
			this.button2.Add (w130);
			this.hbox1.Add (this.button2);
			global::Gtk.Box.BoxChild w138 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
			w138.Position = 0;
			w138.Expand = false;
			w138.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button11 = new global::Gtk.Button ();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			// Container child button11.Gtk.Container+ContainerChild
			global::Gtk.Alignment w139 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w140 = new global::Gtk.HBox ();
			w140.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w141 = new global::Gtk.Image ();
			w141.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w140.Add (w141);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w143 = new global::Gtk.Label ();
			w143.LabelProp = global::Mono.Unix.Catalog.GetString ("Edit song metadata");
			w143.UseUnderline = true;
			w140.Add (w143);
			w139.Add (w140);
			this.button11.Add (w139);
			this.hbox1.Add (this.button11);
			global::Gtk.Box.BoxChild w147 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button11]));
			w147.Position = 1;
			w147.Expand = false;
			w147.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button12 = new global::Gtk.Button ();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			// Container child button12.Gtk.Container+ContainerChild
			global::Gtk.Alignment w148 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w149 = new global::Gtk.HBox ();
			w149.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w150 = new global::Gtk.Image ();
			w150.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w149.Add (w150);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w152 = new global::Gtk.Label ();
			w152.LabelProp = global::Mono.Unix.Catalog.GetString ("Add to playlist");
			w152.UseUnderline = true;
			w149.Add (w152);
			w148.Add (w149);
			this.button12.Add (w148);
			this.hbox1.Add (this.button12);
			global::Gtk.Box.BoxChild w156 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button12]));
			w156.Position = 2;
			w156.Expand = false;
			w156.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblSearchFor = new global::Gtk.Label ();
			this.lblSearchFor.Name = "lblSearchFor";
			this.lblSearchFor.Xalign = 0F;
			this.lblSearchFor.LabelProp = global::Mono.Unix.Catalog.GetString ("Search for:");
			this.hbox1.Add (this.lblSearchFor);
			global::Gtk.Box.BoxChild w157 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblSearchFor]));
			w157.Position = 3;
			w157.Expand = false;
			w157.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.hbox1.Add (this.entry1);
			global::Gtk.Box.BoxChild w158 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry1]));
			w158.Position = 4;
			this.vboxSongBrowser.Add (this.hbox1);
			global::Gtk.Box.BoxChild w159 = ((global::Gtk.Box.BoxChild)(this.vboxSongBrowser [this.hbox1]));
			w159.Position = 1;
			w159.Expand = false;
			w159.Fill = false;
			// Container child vboxSongBrowser.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeSongBrowser = new global::Gtk.TreeView ();
			this.treeSongBrowser.CanFocus = true;
			this.treeSongBrowser.Name = "treeSongBrowser";
			this.GtkScrolledWindow.Add (this.treeSongBrowser);
			this.vboxSongBrowser.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w161 = ((global::Gtk.Box.BoxChild)(this.vboxSongBrowser [this.GtkScrolledWindow]));
			w161.Position = 2;
			this.vpanedLoopsMarkersSongBrowser.Add (this.vboxSongBrowser);
			this.vboxRight.Add (this.vpanedLoopsMarkersSongBrowser);
			global::Gtk.Box.BoxChild w163 = ((global::Gtk.Box.BoxChild)(this.vboxRight [this.vpanedLoopsMarkersSongBrowser]));
			w163.Position = 1;
			this.hpanedMain.Add (this.vboxRight);
			this.vboxMain.Add (this.hpanedMain);
			global::Gtk.Box.BoxChild w165 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hpanedMain]));
			w165.Position = 2;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vboxMain.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w166 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.statusbar1]));
			w166.Position = 3;
			w166.Expand = false;
			w166.Fill = false;
			this.Add (this.vboxMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultHeight = 748;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.actionExit.Activated += new global::System.EventHandler (this.OnExitActionActivated);
			this.actionAbout.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
			this.helpAction.Activated += new global::System.EventHandler (this.OnHelpActionContentsActivated);
			this.aboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
			this.actionPlay.Activated += new global::System.EventHandler (this.OnActionPlayActivated);
			this.actionPause.Activated += new global::System.EventHandler (this.OnActionPauseActivated);
			this.actionStop.Activated += new global::System.EventHandler (this.OnActionStopActivated);
			this.actionPrevious.Activated += new global::System.EventHandler (this.OnActionPreviousActivated);
			this.actionNext.Activated += new global::System.EventHandler (this.OnActionNextActivated);
			this.actionRepeatType.Activated += new global::System.EventHandler (this.OnActionRepeatTypeActivated);
			this.actionOpen.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
			this.actionUpdateLibrary.Activated += new global::System.EventHandler (this.OnActionUpdateLibraryActivated);
			this.actionSettings.Activated += new global::System.EventHandler (this.OnActionSettingsActivated);
			this.actionEffects.Activated += new global::System.EventHandler (this.OnActionEffectsActivated);
			this.actionPlaylist.Activated += new global::System.EventHandler (this.OnActionPlaylistActivated);
			this.hscaleSongPosition.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnSongPositionButtonPressEvent);
			this.hscaleSongPosition.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnSongPositionButtonReleaseEvent);
			this.hscaleSongPosition.MoveSlider += new global::Gtk.MoveSliderHandler (this.OnSongPositionMoveSlider);
			this.hscaleSongPosition.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnSongPositionChangeValue);
			this.hscaleTimeShifting.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnSongPositionButtonPressEvent);
			this.hscaleTimeShifting.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnSongPositionButtonReleaseEvent);
			this.hscaleTimeShifting.MoveSlider += new global::Gtk.MoveSliderHandler (this.OnSongPositionMoveSlider);
			this.hscaleTimeShifting.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnSongPositionChangeValue);
			this.vscaleVolume.ValueChanged += new global::System.EventHandler (this.OnVolumeValueChanged);
		}
	}
}
