
// This file has been generated by the GUI designer. Do not modify.
namespace MPfm.GTK
{
	public partial class SyncWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label lblTitle;
		private global::Gtk.Label lblSubtitle;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeViewDevices;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button btnRefreshDeviceList;
		private global::Gtk.ProgressBar progressBar;
		private global::Gtk.Button btnSyncLibraryWithDevice;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MPfm.GTK.SyncWindow
			this.Name = "MPfm.GTK.SyncWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SyncWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MPfm.GTK.SyncWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 4;
			this.vbox1.BorderWidth = ((uint)(8));
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblTitle = new global::Gtk.Label ();
			this.lblTitle.Name = "lblTitle";
			this.lblTitle.Xalign = 0F;
			this.lblTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Sync library with other devices");
			this.vbox1.Add (this.lblTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblTitle]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblSubtitle = new global::Gtk.Label ();
			this.lblSubtitle.Name = "lblSubtitle";
			this.lblSubtitle.Xalign = 0F;
			this.lblSubtitle.LabelProp = global::Mono.Unix.Catalog.GetString ("My IP address is: 192.168.1.101");
			this.vbox1.Add (this.lblSubtitle);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblSubtitle]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeViewDevices = new global::Gtk.TreeView ();
			this.treeViewDevices.CanFocus = true;
			this.treeViewDevices.Name = "treeViewDevices";
			this.GtkScrolledWindow.Add (this.treeViewDevices);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w4.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnRefreshDeviceList = new global::Gtk.Button ();
			this.btnRefreshDeviceList.CanFocus = true;
			this.btnRefreshDeviceList.Name = "btnRefreshDeviceList";
			this.btnRefreshDeviceList.UseUnderline = true;
			this.btnRefreshDeviceList.Label = global::Mono.Unix.Catalog.GetString ("Refresh device list");
			this.hbox1.Add (this.btnRefreshDeviceList);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnRefreshDeviceList]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.progressBar = new global::Gtk.ProgressBar ();
			this.progressBar.Name = "progressBar";
			this.hbox1.Add (this.progressBar);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.progressBar]));
			w6.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSyncLibraryWithDevice = new global::Gtk.Button ();
			this.btnSyncLibraryWithDevice.CanFocus = true;
			this.btnSyncLibraryWithDevice.Name = "btnSyncLibraryWithDevice";
			this.btnSyncLibraryWithDevice.UseUnderline = true;
			this.btnSyncLibraryWithDevice.Label = global::Mono.Unix.Catalog.GetString ("Connect to device");
			this.hbox1.Add (this.btnSyncLibraryWithDevice);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnSyncLibraryWithDevice]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 444;
			this.DefaultHeight = 300;
			this.Show ();
			this.btnRefreshDeviceList.Clicked += new global::System.EventHandler (this.OnSyncRefreshDeviceList);
		}
	}
}
