
// This file has been generated by the GUI designer. Do not modify.
namespace MPfm.GTK
{
	public partial class SyncMenuWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label lblTitle;
		private global::Gtk.Label lblSubtitle;
		private global::Gtk.Button btnSync;
		private global::Gtk.Label lblLoading;
		private global::Gtk.ProgressBar progressBar;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeView;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label lblTotal;
		private global::Gtk.Label lblFreeSpace;
		private global::Gtk.Button btnSelectAll;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MPfm.GTK.SyncMenuWindow
			this.Name = "MPfm.GTK.SyncMenuWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SyncMenuWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MPfm.GTK.SyncMenuWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 4;
			this.vbox2.BorderWidth = ((uint)(8));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblTitle = new global::Gtk.Label ();
			this.lblTitle.Name = "lblTitle";
			this.lblTitle.Xalign = 0F;
			this.lblTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Sync library with");
			this.vbox4.Add (this.lblTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblTitle]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblSubtitle = new global::Gtk.Label ();
			this.lblSubtitle.Name = "lblSubtitle";
			this.lblSubtitle.Xalign = 0F;
			this.lblSubtitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose audio files to sync");
			this.vbox4.Add (this.lblSubtitle);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblSubtitle]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox4]));
			w3.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnSync = new global::Gtk.Button ();
			this.btnSync.CanFocus = true;
			this.btnSync.Name = "btnSync";
			this.btnSync.UseUnderline = true;
			// Container child btnSync.Gtk.Container+ContainerChild
			global::Gtk.Alignment w4 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w5 = new global::Gtk.HBox ();
			w5.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			w5.Add (w6);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w8 = new global::Gtk.Label ();
			w8.LabelProp = global::Mono.Unix.Catalog.GetString ("Sync");
			w8.UseUnderline = true;
			w5.Add (w8);
			w4.Add (w5);
			this.btnSync.Add (w4);
			this.hbox3.Add (this.btnSync);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnSync]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblLoading = new global::Gtk.Label ();
			this.lblLoading.Name = "lblLoading";
			this.lblLoading.LabelProp = global::Mono.Unix.Catalog.GetString ("Loading...");
			this.vbox2.Add (this.lblLoading);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblLoading]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.progressBar = new global::Gtk.ProgressBar ();
			this.progressBar.Name = "progressBar";
			this.vbox2.Add (this.progressBar);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.progressBar]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeView = new global::Gtk.TreeView ();
			this.treeView.CanFocus = true;
			this.treeView.Name = "treeView";
			this.GtkScrolledWindow.Add (this.treeView);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w17.Position = 3;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblTotal = new global::Gtk.Label ();
			this.lblTotal.Name = "lblTotal";
			this.lblTotal.Xalign = 0F;
			this.lblTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total: 0 files (0.0 MB)");
			this.vbox3.Add (this.lblTotal);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblTotal]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblFreeSpace = new global::Gtk.Label ();
			this.lblFreeSpace.Name = "lblFreeSpace";
			this.lblFreeSpace.Xalign = 0F;
			this.lblFreeSpace.LabelProp = global::Mono.Unix.Catalog.GetString ("Free space: 3204.3 MB");
			this.vbox3.Add (this.lblFreeSpace);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblFreeSpace]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
			w20.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnSelectAll = new global::Gtk.Button ();
			this.btnSelectAll.CanFocus = true;
			this.btnSelectAll.Name = "btnSelectAll";
			this.btnSelectAll.UseUnderline = true;
			this.btnSelectAll.Label = global::Mono.Unix.Catalog.GetString ("Select all");
			this.hbox2.Add (this.btnSelectAll);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnSelectAll]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w22.Position = 4;
			w22.Expand = false;
			w22.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 640;
			this.DefaultHeight = 475;
			this.Show ();
		}
	}
}
