
// This file has been generated by the GUI designer. Do not modify.
namespace MPfm.GTK
{
	public partial class SyncDownloadWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label lblTitle;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label lblStatus;
		private global::Gtk.ProgressBar progressBar;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label lblCurrentFile;
		private global::Gtk.ProgressBar progressBarCurrentFile;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label lblFilesDownloadedValue;
		private global::Gtk.Label lblFilesDownloaded;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label lblDownloadSpeedValue;
		private global::Gtk.Label lblDownloadSpeed;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label lblErrorsValue;
		private global::Gtk.Label lblErrors;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Button btnCancel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MPfm.GTK.SyncDownloadWindow
			this.Name = "MPfm.GTK.SyncDownloadWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SyncDownloadWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MPfm.GTK.SyncDownloadWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 4;
			this.vbox2.BorderWidth = ((uint)(8));
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblTitle = new global::Gtk.Label ();
			this.lblTitle.Name = "lblTitle";
			this.lblTitle.Xalign = 0F;
			this.lblTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Sync library with");
			this.vbox2.Add (this.lblTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblTitle]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.lblStatus = new global::Gtk.Label ();
			this.lblStatus.Name = "lblStatus";
			this.lblStatus.Xalign = 0F;
			this.lblStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("Downloading files...");
			this.vbox6.Add (this.lblStatus);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.lblStatus]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.progressBar = new global::Gtk.ProgressBar ();
			this.progressBar.Name = "progressBar";
			this.vbox6.Add (this.progressBar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.progressBar]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox2.Add (this.vbox6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox6]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(10));
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblCurrentFile = new global::Gtk.Label ();
			this.lblCurrentFile.Name = "lblCurrentFile";
			this.lblCurrentFile.Xalign = 0F;
			this.lblCurrentFile.LabelProp = global::Mono.Unix.Catalog.GetString ("01 - Test.mp3");
			this.vbox7.Add (this.lblCurrentFile);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.lblCurrentFile]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.progressBarCurrentFile = new global::Gtk.ProgressBar ();
			this.progressBarCurrentFile.Name = "progressBarCurrentFile";
			this.vbox7.Add (this.progressBarCurrentFile);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.progressBarCurrentFile]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox2.Add (this.vbox7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox7]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(10));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblFilesDownloadedValue = new global::Gtk.Label ();
			this.lblFilesDownloadedValue.Name = "lblFilesDownloadedValue";
			this.lblFilesDownloadedValue.Xalign = 0F;
			this.lblFilesDownloadedValue.LabelProp = global::Mono.Unix.Catalog.GetString ("12/45");
			this.vbox3.Add (this.lblFilesDownloadedValue);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblFilesDownloadedValue]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblFilesDownloaded = new global::Gtk.Label ();
			this.lblFilesDownloaded.Name = "lblFilesDownloaded";
			this.lblFilesDownloaded.Xalign = 0F;
			this.lblFilesDownloaded.LabelProp = global::Mono.Unix.Catalog.GetString ("files downloaded");
			this.vbox3.Add (this.lblFilesDownloaded);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblFilesDownloaded]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblDownloadSpeedValue = new global::Gtk.Label ();
			this.lblDownloadSpeedValue.Name = "lblDownloadSpeedValue";
			this.lblDownloadSpeedValue.Xalign = 0F;
			this.lblDownloadSpeedValue.LabelProp = global::Mono.Unix.Catalog.GetString ("2452 kb/s");
			this.vbox4.Add (this.lblDownloadSpeedValue);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblDownloadSpeedValue]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblDownloadSpeed = new global::Gtk.Label ();
			this.lblDownloadSpeed.Name = "lblDownloadSpeed";
			this.lblDownloadSpeed.Xalign = 0F;
			this.lblDownloadSpeed.LabelProp = global::Mono.Unix.Catalog.GetString ("download speed");
			this.vbox4.Add (this.lblDownloadSpeed);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblDownloadSpeed]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(12));
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblErrorsValue = new global::Gtk.Label ();
			this.lblErrorsValue.Name = "lblErrorsValue";
			this.lblErrorsValue.Xalign = 0F;
			this.lblErrorsValue.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.vbox5.Add (this.lblErrorsValue);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblErrorsValue]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblErrors = new global::Gtk.Label ();
			this.lblErrors.Name = "lblErrors";
			this.lblErrors.Xalign = 0F;
			this.lblErrors.LabelProp = global::Mono.Unix.Catalog.GetString ("errors");
			this.vbox5.Add (this.lblErrors);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblErrors]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.hbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox5]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			w16.Padding = ((uint)(12));
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseStock = true;
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = "gtk-cancel";
			this.hbox4.Add (this.btnCancel);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnCancel]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(8));
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 473;
			this.DefaultHeight = 307;
			this.Show ();
			this.btnCancel.Clicked += new global::System.EventHandler (this.OnClickCancel);
		}
	}
}
